### ISSUE TITLE
Use module names to create namespaces for systems

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#101]
**Describe the problem you are trying to solve.**
Modules typically register private systems that needed for the implementation of some feature, but that are not exposed publicly by the module. These systems are however registered with the world, meaning that their names can potentially clash with with other modules.

This is problematic, especially for private systems, as applications (should) have no knowledge about module internals. To address this, modules should be namespaced.

**Describe the solution you'd like**
Currently, a system declaration looks similar to this:

```c
ECS_SYSTEM(world, Move, EcsOnUpdate, Position, Velocity);
```

A namespace could be added to the macro:

```c
ECS_SYSTEM(world, MyNamespace, Move, EcsOnUpdate, Position, Velocity);
```

But this would be tedious to do for every system. It is also error prone, as there is no guarantee that systems in the same module will end up in the same namespace.

An alternative approach would be to have the `ECS_MODULE` macro define a variable that contains the module name, like:

```c
#define ECS_MODULE(id) ...\
    const char *_ecs_namespace = #id;
```

And then modify the `ECS_SYSTEM` macro so that it passes the namespace into the `ecs_new_system` function:

```c
#define ECS_SYSTEM(world, id, kind, __VARARGS__) \
    ecs_new_system(world, _ecs_namespace, #id, kind, #__VARARGS__, id);
```

For systems that are not defined in a module this local `_ecs_namespace` variable would not be defined. To address this, a new global variable with the same name could be introduced that contains the value `NULL`.

With this approach, systems defined in a module will automatically get `_ecs_namespace` from the module as the local variable masks the global variable. Systems not defined in a module will see the global variable, and will get `NULL` for the namespace argument.

The namespace argument should be stored in a separate `EcsNamespace` component. That way code that only relies on the component that contains the entity id (`EcsId`) won't break, and the component does not need to concatenate the namespace string with the name string (which would mean having to do resource mgmt).

A new function `ecs_lookup_w_namespace` function should be created so that it can look for entities in a specific namespace. In addition to matching the `EcsId` component, it should also match the `EcsNamespace` component if a value is provided that is not `NULL`.

`ecs_lookup_w_namespace` should be used in the `ecs_new_system` function so that when it checks if the system already exists, it won't match systems from other modules.

This mechanism could eventually be extended to components as well.

**Comment by teksoc-1** [comment]
@SanderMertens I believe this issue is not limited to Systems, but also private internal Components and Tags. For example `MyTag` will suffer the same name space collision problem if other modules also use the same Tag. Example:

```
Module 1

System
ECS_SYSTEM(world, Module1System, EcsOnUpdate, A, !MyTag)

``` 
Module 2
ECS_SYSTEM(world, Module2System, EcsOnUpdate, A, !MyTag)
```

**Comment by SanderMertens** [comment]
@teksoc-1 Yes you're right. I think I will add a namespace to each of the declarative macros (systems, components, tags, entities, prefabs, types).
