### ISSUE TITLE
how to support fixed-point number?

### ISSUE THREAD

**Issue by yafacex** [SanderMertens/flecs#1013]
how to support fixed-point number gracely?I want to ensure calculate consistency in different devices.
especially when i use flecs-cs, one decimal both stores in c and c#.

**Comment by SanderMertens** [comment]
You can override the type flecs uses for tracking time with an integer type (defined here https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L42), for example:

```cpp
#define ecs_ftime_t uint64_t
```

**Comment by yafacex** [comment]
> You can override the type flecs uses for tracking time with an integer type (defined here https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L42), for example:
> 
> ```c++
> #define ecs_ftime_t uint64_t
> ```

thanks
