### ISSUE TITLE
Child don't destroy when parent destroy. (child has a other relations(<256) with parent)

### ISSUE THREAD

**Issue by Esp9527** [SanderMertens/flecs#1024]
**Describe the bug**
Child don't destroy when parent destroy. (child has a other relations(<256) with parent)
version 3.2.5 

**To Reproduce**
`
    
    #include "flecs.h"
    #include <map>
    #include <iostream>
    
    namespace component {
        enum class Cate {
            None,
            Player,
            Monster
        };
        struct Relataions {
            struct CastOf{};
        };
    }
    
    template<int i>
    struct TP{
        int v;
    };
    
    template<int i>
    void Register(flecs::world& world) {
        if constexpr( i > 0) {
            world.component<TP<i>>();
            Register<i-1>(world);
        }
    }
    
    int main() {
        using namespace component;
    
        flecs::world world;
        world.component<Cate>()
                .constant("None", Cate::None)
                .constant("Player", Cate::Player)
                .constant("Monster", Cate::Monster);
    
        // register low(<256) id
        // Register<256>(world);
    
        auto cf = world.component<Relataions::CastOf>();
        std::cout << cf.name() << " : " << cf.id() << std::endl;
    
        world.observer<>("ObjectsDestroy")
                .term<component::Cate>(flecs::Wildcard)
                .event(flecs::OnRemove)
                .each([](flecs::iter &it, size_t index){
                    auto entity = it.entity(index);
                    auto cate = it.pair(1).second();
                    std::cout << "[object] destroy " << entity.id() << std::endl;
                });
    
        // monster is children of player
        auto player = world.entity().add(Cate::Player);
        auto monster = world.entity().add(Cate::Monster).child_of(player);
    
        monster.add<Relataions::CastOf>(player);
    
        player.destruct();
        world.app().run();
    
        return 0;
    }

`

**Expected behavior**
expect : player destroy, monster  destroy
real:  player destroy, monster don't destroy

**Additional context**
if world.component<Relations::CastOf>().id()  > 256, 
      result is ok

**Comment by SanderMertens** [comment]
Fixed!
