### ISSUE TITLE
Memory leak in new_row_system/row_systems_deinit

### ISSUE THREAD

**Issue by Maykeye** [SanderMertens/flecs#103]
**Describe the bug**
`new_row_system` [allocates memory](https://github.com/SanderMertens/flecs/blob/f39d9a48b5185cc394ee216b58a76f27cb9187b8/src/system.c#L108) for signature: `system_data->base.signature = strdup(sig);`
[row_systems_deinit](https://github.com/SanderMertens/flecs/blob/f39d9a48b5185cc394ee216b58a76f27cb9187b8/src/world.c#L449) doesn't clear it. Nor it is' cleared anywhere else. 

**To Reproduce**
Execute `ecs_fini(ecs_init());` while running leak detector of your choice (e.g. valgrind).
Since ecs_init creates two systems EcsInitPrefab and EcsSetPrefab, there will be strdup with no free. 

**Expected behavior**
No memory leak. 

**Additional context**
Commit: f39d9a48b5185cc394ee216b58a76f27cb9187b8
Similar leak seems to be in new_col_system/col_systems_deinit (but it's not triggered by such primitive example)

**Comment by SanderMertens** [comment]
Fixed!

**Comment by Maykeye** [comment]
That can actually trigger another bug now in extreme setup: strdup always uses OS-provided `malloc`.

ecs_os_free, aka ecs_os_api.{free,malloc} OTOH potentially can be overridden with custom allocator, and since memory for signature was not allocated by the same custom `ecs_os_api.malloc()`, but by OS, ecs_os_free will do whatever custom allocator does when it tries to free invalid pointer.

**Comment by SanderMertens** [comment]
@Maykeye you are absolutely right- I just created #106 for this.
