### ISSUE TITLE
Memoryleak: on_activate_components, on_enable_components are not freed

### ISSUE THREAD

**Issue by Maykeye** [SanderMertens/flecs#104]
**Describe the bug**
ecs_init [allocates](https://github.com/SanderMertens/flecs/blob/f39d9a48b5185cc394ee216b58a76f27cb9187b8/src/world.c#L672) on_activate_components and on_enable_components, but they are never freed in ecs_fini

**To Reproduce**
`ecs_fini(ecs_init())` in memory leak detector

**Expected behavior**
No memory leak

**Comment by SanderMertens** [comment]
Fixed!
