### ISSUE TITLE
Bug: add enum to entity with existing components causes component data to change

### ISSUE THREAD

**Issue by Indra-db** [SanderMertens/flecs#1045]
**Describe the bug**
adding an enum to an entity with components causes the data of the component to change.

**To Reproduce**
1. go to table.cpp in tests
2. add enum 
```c++
enum Number {
    One = 1,
    Two = 2,
    Three = 3
};
```
3. goto `Table_get_T` test
4. change it to
```c++
void Table_get_T(void) {
    flecs::world ecs;

    flecs::entity e = ecs.entity()
        .set<Position>({10, 20})
        .set<Velocity>({1, 2})
        .set<Number>(Number::One); //---> .add(Number::One) has the same effect
    ecs.entity()
        .set<Position>({20, 30})
        .set<Velocity>({2, 3});
        //.set<Number>(Number::Two);
    ecs.entity()
        .set<Position>({30, 40})
        .set<Velocity>({3, 4});
        //.set<Number>(Number::Three);

    flecs::table table = e.table();
    Position *p = table.get<Position>();
    test_assert(p != NULL);
    test_int(p[0].x, 10);
    test_int(p[0].y, 20);
    test_int(p[1].x, 20);
    test_int(p[1].y, 30);
    test_int(p[2].x, 30);
    test_int(p[2].y, 40);

    Velocity *v = table.get<Velocity>();
    test_assert(v != NULL);
    test_int(v[0].x, 1);
    test_int(v[0].y, 2);
    test_int(v[1].x, 2);
    test_int(v[1].y, 3);
    test_int(v[2].x, 3);
    test_int(v[2].y, 4);
    }
``` 

   
   5. run test with 
`bake run test/cpp_api -- -j 4`

**Expected behavior**
expected behaviour: test passes
actual behaviour: 
`FAIL: Table.get_T:363: p[1].x (0) != 20`

-> removing the .set or .add line makes the test pass again. 

**Additional context**

Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	22H2
Installed on	‎1/‎29/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by SanderMertens** [comment]
This is not a bug. Because the first entity has different components from the other two entiites, it is in a different table.
