### ISSUE TITLE
Excessive Entities Registered During Enum Constant Registration on MSVC Compiler

### ISSUE THREAD

**Issue by Indra-db** [SanderMertens/flecs#1047]
**Describe the bug**
Upon registering an enum constant using the MSVC compiler, 128 entities are registered irrespective of the actual field count within the enum. This was observable while utilizing a minimal code snippet, where only two enum fields were present but resulted in the registration of 128 entities.

**To Reproduce**
1. Execute the provided code snippet on a system utilizing the MSVC compiler.

```
enum Movement {
    Walking,
    Running
};

int main(int, char* []) {

    flecs::world ecs;
    //flecs::world ecs2;

    auto e = ecs.entity();

    std::cout << e.id() << std::endl;
    flecs::entity ee = ecs.entity().add<Movement>();
    auto e2 = ecs.entity();

    std::cout << e2.id() << std::endl;

return 0;
}
```
2. Upon execution, observe the entity IDs output to the console.
3. During debugging, specifically monitor the entity constant registration phase and notice the registration of 128 entities for the registered enum.

**Expected behavior**
The expected outcome should be the registration of only two entities correlating to the enum fields: Walking and Running, rather than an arbitrary 128 entities.

**Actual Behavior:**
The system registers 128 entities for each registered enum, yielding entity IDs 549 and 680 in this particular instance

**Additional context**

compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64.

Observable both in Flecs 3.2.4 and 3.2.7. Other releases not tested.

This bug is also viewable on the explorer, showing that too many entities have been registered under the enum.
![image](https://github.com/SanderMertens/flecs/assets/60851042/3fa7e376-cf2b-4811-b5c4-0f0f112885af)

**Comment by SanderMertens** [comment]
I'm not able to reproduce the issue using msvc 19.35. How did you build the code?

**Comment by Indra-db** [comment]
@SanderMertens just building with visual studio. 
[flecs_bug.zip](https://github.com/SanderMertens/flecs/files/12739372/flecs_bug.zip)
this is the repro solution

**Comment by Indra-db** [comment]
Made some new observations:

The bug persists on platform toolset v142
Microsoft Visual Studio Community 2019
Version 16.11.29
prints
549
680
810

does not persist on platform toolset v143
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4
prints
548
553
556

**Comment by Indra-db** [comment]
updated Visual studio Community 2019 Version 16.11.30, the bug still persists on there

**Comment by SanderMertens** [comment]
Fixed!

**Comment by Esp9527** [comment]
My Windows _MSC_VER= 1929,  I found same bug. ( flecs version master)

if I changed enum.hpp code 1930 to 1929, the bug will fix.

so there need change 1930 to 1929?

@SanderMertens
