### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by WEREMSOFT** [SanderMertens/flecs#105]
When I submit a pull request, some tests run on my code. Where are this tests and how can I run them in my local environment? I will need to update them once I finish the fix. 

Thanks.

**Comment by SanderMertens** [comment]
Currently running tests is only supported if you are using bake. On Linux you can just do:
```
bake test
```

There is a known issue on Windows that prevents bake from running tests with "bake test", but you should be able to run the tests by following the same steps as in the AppVeyor script:
https://github.com/SanderMertens/flecs/blob/master/appveyor.yml

**Comment by WEREMSOFT** [comment]
There was something wrong with my system. I follow the instructions for building Bake once more and it worked.

I was able to successfully run the tests.
