### ISSUE TITLE
The strings.flecs example shows error in the explorer

### ISSUE THREAD

**Issue by sh-dave** [SanderMertens/flecs#1076]
**Describe the bug**

An error is shown for the example code:  invalid assignment, '(Shader,Vertex)' is not a type

**To Reproduce**

1. Copy the code of the [examples/plecs/strings.flecs](https://github.com/SanderMertens/flecs/blob/master/examples/plecs/strings.flecs) file and paste it into the Editor dialog of https://flecs.dev/explorer
2. See error mentioned above

**Expected behavior**

Example code should not result in an error :scream:

**Comment by SanderMertens** [comment]
Fixed!
