### ISSUE TITLE
Abnormal CPU rise when observer 

### ISSUE THREAD

**Issue by Esp9527** [SanderMertens/flecs#1077]
**Describe the bug**
Abnormal CPU rise when observer 
i make entity add tag in other-entity'observer (10000/s)
cpu will raise with the sum of other-entity?

**To Reproduce**
`

    #include <flecs.h>
    #include <vector>
    
    struct AttrChanged{
    };
    
    struct Attack{
        uint64_t attacker = 0;
        int tick = 0;
    };
    
    struct Player{
        int _null = 0;
    };
    
    int main() {
    
        flecs::world world;
    
        world.system<Player>()
                .each([](flecs::entity e, Player& player) {
                    auto attack = e.world().entity();
                    attack.set<Attack>({ e.id()});
                });
    
        world.observer<Attack>()
                .event(flecs::OnSet)
                .each([](flecs::entity e, Attack& q) {
                    auto player = e.world().entity(q.attacker);
                    player.add<AttrChanged>();
                });
    
        world.system<Attack>()
                .each([](flecs::entity e, Attack& q) {
                    if(++q.tick >= 1000){
                        e.destruct();
                    }
                });
    
        std::vector<uint64_t> v;
        for(int i = 0; i < 500; ++i){
            auto p = world.entity();
            p.set<Player>({i});
            v.push_back(p.id());
        }
        world.app().target_fps(20).run();
        return 0;
    }
`
**Expected behavior**
there are 500 player create attack every tick

the sum of player is fixed = 500
the life of attack is fixed = 50 sec (1000 tick)
the grow of attack is fixed = 10000/s
the max-sum of attack is 500 000
one thread Cpu will grow to 100% On My PC after 50 SEC

if don't player.add<AttrChanged>(), cpu will lease many
if make life of attack =100 tick , cpu will lease many

AttrChanged is set on player, so is player cause attack-flecs-table do some things?

**Additional context**
Add any other context about the problem here (operating system, hardware, ...).

**Comment by SanderMertens** [comment]
Did you try to reproduce this on v3.2.9? It fixes a performance issue that sounds just like what you're describing.

**Comment by Esp9527** [comment]
yes, fixed on v3.209

**Comment by Esp9527** [comment]
yes, fixed on v3.2.9, thanks
