### ISSUE TITLE
Pair id gives error when deserialized from json

### ISSUE THREAD

**Issue by xubury** [SanderMertens/flecs#1083]
**Describe the bug**
When deserializing a json that have pair id, `from_json` will give error saying id is not a type.

**To Reproduce**
```
flecs::entity_to_json_desc_t desc{};
desc.serialize_ids     = true;
desc.serialize_values  = true;
desc.serialize_path    = false;
desc.serialize_private = true;
desc.serialize_label   = false;
auto  e    = ecs.entity("potato");
const char *json = e.to_json(&desc).c_str();
std::cout << json << std::endl;
auto prefab = ecs.prefab();
prefab.from_json(json);
```
Output:
```
{"ids":[["flecs.core.Identifier", "flecs.core.Name"]], "values":[0]}
error: cursor.c: 178: cannot open scope for entity 'Identifier' which is not a type
```

**Expected behavior**
No error when using `from_json`

**Additional context**
flecs v3.2.7 compiler vs2019

**Comment by SanderMertens** [comment]
This doesn't work because the `Identifier` type isn't described with the reflection framework which is on purpose, assigning the name of an entity this way is not supported (`Identifier` does more than just storing the name).

Instead try adding `{"name": "my_entity", ...`
