### ISSUE TITLE
Correct way to manually specify entity ids

### ISSUE THREAD

**Issue by rvkennedy** [SanderMertens/flecs#1088]
In the manual (https://www.flecs.dev/flecs/md_docs_Manual.html#autotoc_md146) it says that "Applications do not have to rely on ecs_new and ecs_delete to create and delete entity identifiers. Entity ids may be used directly, like in this example:" 

`ecs_add(world, 42, Position);`

But this causes a failure in entity.c, as ecs_is_alive(world,entity) is false.
Is there actually a way to create entities with manually-specified ids?

**Comment by SanderMertens** [comment]
Ah, that bit of the manual is a bit outdated, I'll make sure to update it.

You now need to make sure that the id is alive before you use it, which you can do with:
```cpp
ecs_ensure(world, 42);
```
