### ISSUE TITLE
Assignment within conditional expression error

### ISSUE THREAD

**Issue by Bizes** [SanderMertens/flecs#1090]
I am trying to write some ECS systems with flecs for Unreal 5.3 and got an "assignment within conditional expression" error.

Source\FlecsLibrary\Public\flecs.h(23181): error C4706: assignment within conditional expression
Source\FlecsLibrary\Public\flecs.h(23181): error C4706: assignment within conditional expression

**To Reproduce**
Create flecs entity and add components? I am not 100% sure what I changed to get this error because two days ago it worked and the only things I changed was adding a few more systems and components.

Error seems to come from this line in flecs.h(23181)
`       
        bool has_components;
 if ((has_components = get_ptrs(world, r, table, ptrs))) {
`

Changing it to
`        bool has_components= get_ptrs(world, r, table, ptrs);
        if ((has_components )) {
`
fixes it for me.

I also had it in another line in flecs.h, I think it was 23157.

Dont know if this is a bug in Unreal/ VS2022 but it works with this workaround. I also think the workaround will break anything.
If not feel free to remove the issue report.

**Comment by SanderMertens** [comment]
Fixed! I wasn't seeing this error in CI so I just fixed the two statements you mentioned. Let me know if the issue persists!
