### ISSUE TITLE
Rickroll in community resource link in README.md

### ISSUE THREAD

**Issue by tjamaan** [SanderMertens/flecs#1098]
Not sure if intentional but the bitly link for "Flecs based 3D game engine with editor" in README.md leads to a rickroll.

https://github.com/SanderMertens/flecs/blob/438bde47817863db3f43ff494db1cc77a40840a4/README.md?plain=1#L170

**Comment by copygirl** [comment]
Intentional, see #974.

**Comment by tjamaan** [comment]
lmao
