### ISSUE TITLE
make a version of ECS_SYSTEM macro that takes a Lambda

### ISSUE THREAD

**Issue by redstonedash** [SanderMertens/flecs#111]
I was developing my game in flecs when I realized that it would significantly improve my work flow if I could have my function body directly next to where I register my system. I tried to use a Lambda expression and set it to a function pointer but i got the error.
`no suitable conversion function from "lambda []void (ecs_rows_t *rows)->void" to "ecs_entity_t" exists`
 when looking into the macro it seems it was never meant for this kind of thing

It would be really nice if something like this would work
```
auto moveptr = [](ecs_rows_t *rows) {
		ECS_COLUMN(rows, SharedTransform, t, 1);
		for (int i = 0; i < rows->count; i++) {
			*t[i].m = MatrixMultiply(*t[i].m, MatrixTranslate(1 * GetFrameTime(), 0, 0));
		}}
	;
	ECS_SYSTEM(gameState, moveptr, EcsOnUpdate, SharedTransform);
```

however really anyway I could get the same result (function body being adjacent to registering the system)  would be good.

**Comment by SanderMertens** [comment]
@redstonedash I am currently working on a C++ binding that will let you do all of these things, and a lot more! It is on this branch:

https://github.com/SanderMertens/flecs/blob/cpp_prototype/include/flecs/flecs_cpp.h

With this binding you can write your code like this:

```c++
    flecs::world world(argc, argv);

    flecs::component<Position>(world, "Position");
    flecs::component<Velocity>(world, "Velocity");

    flecs::system<Position&, const Velocity>(world, "Move")
        .action([](auto rows, auto p, auto v) {
            for (auto row : rows) {
                p[row].x += v[row].x;
                p[row].y += v[row].y;
            }
        });
```

**Comment by redstonedash** [comment]
yea that pretty much solves the problem
