### ISSUE TITLE
README link is broken

### ISSUE THREAD

**Issue by vkensou** [SanderMertens/flecs#1153]
**Describe the bug**
README link is broken.

**To Reproduce**
1. Go to README.md
2. Go to Resources block >> Resources provided by the community ❤️ Block
3. Click on '[Flecs based 3D game engine with editor](https://bit.ly/3T9cc1o)'

**Expected behavior**
Link to a repository of "Flecs based 3D game engine with editor"

**Comment by SanderMertens** [comment]
🤫
