### ISSUE TITLE
filter_builder() assert fail, when use term().or_()

### ISSUE THREAD

**Issue by hallomorld** [SanderMertens/flecs#1169]
**Describe the bug**
filter_builder() assert fail, when use 
         .term<TagA>().or_()
         .term<StructB>()
This issue is problematic in flecs 3.2.10 or later. The old version works fine.

**To Reproduce**
flecs 3.2.10 or more new
`
      
      #include <flecs.h>
      
      struct TagA {
      };
      
      struct StructB {
          int i = 0;
      };
      
      int main(int argc, char *argv[]) {
      
          flecs::world w;
          w.component<TagA>();
          w.component<StructB>();
      
          auto filter = w.filter_builder<>()
                  .term<TagA>().or_()
                  .term<StructB>()
                  .build();
      
          filter.each([](flecs::iter &iter, size_t index) {});
      
          w.app().run();
          return 0;
      }

`

**Expected behavior**
`
    fatal: filter.c: 1391: assert: filter_terms <= term_count INTERNAL_ERROR
`

**Comment by SanderMertens** [comment]
Oh wow, that's a bad one to fly under the radar of the test suite! Taking a look.

**Comment by SanderMertens** [comment]
Fixed!
