### ISSUE TITLE
Add flecs.c and flecs.h as download artefacts for releases

### ISSUE THREAD

**Issue by coderedart** [SanderMertens/flecs#1214]
**Describe the problem you are trying to solve.**
When target a certain version, it helps to have readily downloadable sources (not *all*, but just the header and c files) attached as downloadable assets with each release/tag. 

The source archives are really huge (33 MB compressed) and aren't really necessary when you just need the header and source file.

**Describe the solution you'd like**
There's two useful solutions:
### Add flecs.h and flecs.c as assets to github releases
This is obvious and not much needs to be said.

### Have a separate repo that contains just flecs.c and flecs.h
This current repo is already huge (100+ MB for a full clone). A fresh repo with *only* `flecs.c` and `flecs.h` (maybe a README?) would be a really lightweight option to use as a git dependency. 

This allows people to just fork that repo and "sync" with the parent repo every now and then to keep up to date. Or maybe use that repo as a submodule to vendor in dependencies.
For example, most rust projects that contain raw C bindings, often add the C library repo as a submodule. eg: [glfw-sys](https://github.com/PistonDevelopers/glfw-sys) or [rusty-v8](https://github.com/denoland/rusty_v8) or [zlib](https://github.com/rust-lang/libz-sys/tree/main/src) etc..

Use an action like https://github.com/cpina/push-to-another-repository-example/blob/main/.github/workflows/ci.yml to just push files to the new repo on every tag. Once setup, its more or less fully automated.

**Comment by copygirl** [comment]
In case it helps: In git you can do a sparse clone. The following command only grabs top-level files from a specific release:
```
git clone --sparse --filter=blob:none --depth 1 --branch v3.2.11 https://github.com/SanderMertens/flecs.git
```
Also I wonder how feasible it is just to manually grab the files you need:
```
wget https://raw.githubusercontent.com/SanderMertens/flecs/v3.2.11/flecs.c
wget https://raw.githubusercontent.com/SanderMertens/flecs/v3.2.11/flecs.h
wget https://raw.githubusercontent.com/SanderMertens/flecs/v3.2.11/LICENSE
wget https://raw.githubusercontent.com/SanderMertens/flecs/v3.2.11/README.md
```

**Comment by coderedart** [comment]
You can always use shallow/sparse clones or github's API to get them. Its just easier (and more accessible to beginners) to download them directly from releases page. I don't think we will hit them anytime soon, but direct downloads (or clones)  of github repos (or specific files) have API limits placed on them. github releases have no such limits in bandwidth or number of downloads. 

The same with having a separate repo for those specific files. easier to deal with by just forking it, instead of using submodules. But this is not as important and can be manually maintained as easily by third-parties.

**Comment by SanderMertens** [comment]
Hm, I'm not sure if adding the source files to the release adds that much value. The zip files are a bit large as a result of the images used in documentation, but 30MB is not _that_ large.

I'll reduce the size of the images which should bring down the overall size of the zip.
