### ISSUE TITLE
[v4] Wildcard observers not receiving events

### ISSUE THREAD

**Issue by xentripetal** [SanderMertens/flecs#1229]
**Describe the bug**
Observers using wildcard events no longer receive any events.

**To Reproduce**
```c
#include "flecs.h"

typedef struct {
    int x, y;
} Position;

void OnPosition(ecs_iter_t* it) {
    printf("Called\n");
}

int main(void) {
    ecs_world_t* world = ecs_init();
    ECS_COMPONENT(world, Position);
    ECS_OBSERVER(world, OnPosition, EcsOnAdd, Position); // Change to EcsWildcard and it doesn't print anything.

    ecs_entity_t e = ecs_new(world);
    ecs_add(world, e, Position);
}
```
**Expected behavior**
Wildcard event observers should be called for any event affecting that component. https://github.com/SanderMertens/flecs/blob/v4/docs/ObserversManual.md#multi-event-observers

**Additional context**
- https://github.com/BeanCheeseBurrito/Flecs.NET/issues/30

**Comment by SanderMertens** [comment]
Fixed!
