### ISSUE TITLE
Support generic lambdas as `each` callbacks

### ISSUE THREAD

**Issue by indianakernick** [SanderMertens/flecs#1233]
## Problem

Implementing systems with an `each` callback requires repeating the component types. For example:

```cpp
world.system<FirstDescriptiveComponentName, const SecondDescriptiveComponentName>()
  .each([](FirstDescriptiveComponentName &a, const SecondDescriptiveComponentName &b) {
    // ...
  });
```

## Solution

It would be cleaner to use `auto` and pass a generic lambda to `each`.

```cpp
world.system<FirstDescriptiveComponentName, const SecondDescriptiveComponentName>()
  .each([](auto &a, auto &b) {
    // ...
  });
```

This doesn't work because the type of the `operator()` function is used to determine the arity (via `function_traits`). Directly determining the arity of a generic function isn't really possible (because what's the arity of `auto...`?). Instead, `each_delegate` could check if the given function can be called with a set of arguments. For the entity + components version, that could look like this:

```cpp
    template <template<typename X, typename = int> class ColumnType, 
        typename... Args, if_t< 
            sizeof...(Components) == sizeof...(Args)> = 0>
    static auto invoke_callback(
        ecs_iter_t *iter, const Func& func, size_t, Terms&, Args... comps)
    -> decltype(func(
        std::declval<flecs::entity>(),
        (std::declval<ColumnType<remove_reference_t<Components>>>().get_row())...
    ), void())
```

I made this change to my local copy and it seemed to work OK for me. This is inspired by EnTT's `each` which supports generic lambdas.

## Wider change

There are other places where this sort of change could be beneficial. All places that check for function arity in the same way are candidates. `iter` and `find` are another two examples.

**Comment by SanderMertens** [comment]
That would be nice! I don't think I'll have to work on this in the near term, but I will accept a PR that enables this, provided that:

- It maintains C++11 compatibility
- It doesn't break existing code (e.g. all tests pass)

**Comment by SanderMertens** [comment]
Merged!
