### ISSUE TITLE
Flecs Script doesn't properly close 'with' block (except in templates)

### ISSUE THREAD

**Issue by CorbinSteele** [SanderMertens/flecs#1328]
**Describe the bug**
Within a Flecs Script: using a 'with' block results in the component or tag being attached to all entities _following_ the 'with' scope, rather than only the entities within its scope. This bug occurs anytime after any template has been declared, and does _not_ occur _within_ a template.

**To Reproduce**
1. Create or modify a script to possess the following (using the explorer is easiest):
```
template arbitrary {}

ParentEntity {
  with flecs.components.transform.Position3(1, 2, 3) {
    EntityWithPosition {}
  }
  EntityWithoutPosition {}
}
EntityDefinitelyWithoutPosition {}
```
2. Notice that _all_ entities other than "ParentEntity" have a Position3 component, with the provided value.
3. Note that the declaration of at least one template anywhere before the with block is **necessary** to reproduce this bug. The name and contents of the template are irrelevant, and the template does not need to have any instantiations.
4. Note that the "ParentEntity" itself is _not_ necessary to reproduce this bug. I've only included it to make the wide-ranging effects of the bug more clear.

**Expected behavior**
I would expect a Position3 component only on "EntityWithPosition" and not on "EntityWithoutPosition" or "EntityDefinitelyWithoutPosition" or any other later entity.

**Additional context**
This bug exists in both 4.0.0 and 4.0.1. It affects both Components and Tags, and happens if there is a 'with' block directly in any entity or Prefab. It does _not_ affect templates: those seem to behave exactly as I would expect.

**Possibly relevant, but probably not**
Bizarrely, if you add another template declaration _after_ the bug has begun (i.e. after the 'with' block), add an entity within it, and then end the template: future entities will still be created with a Position3 component, but its values will be changed in strange ways. Not replaced, mind you, but modified. The original z value of the Position3 _does_ affect it. Add the following code to the end of the reproduction example script to see this for yourself, if you think the resultant values might be insightful:
```
template ArbitraryTemplate {
  something_here_is_necessary_but_the_name_is_irrelevant {}
}

EntityWithBizarrePosition {}
```
The Position3 component on "EntityWithBizarrePosition" ends up approximately with the following values (the first value is the initial Position3 specified in the script; the x and y values don't seem to matter):
(, , 0)     -> (0, 0, 0)
(, , 1)     -> (0, 0, 0.50)
(, , 2-7)     -> (0, 0, 2.02) // all values from 2-7 are the same; in general, the resultant values seem grouped by 4-bit ranges
(, , 8-31)     -> (0, 0, 8.06)
(, , 32-127)   ->  (0, 0, 32.25)
(, , 128-511) -> (0, 0, 129.00)
(, , 512-2047) -> (0, 0, 516.01) // the pattern continues, implying some form of consistent bit manipulation I can't recognize

**Comment by SanderMertens** [comment]
Fixed!
