### ISSUE TITLE
System rate seems to be broken

### ISSUE THREAD

**Issue by bgie** [SanderMertens/flecs#1338]
**Describe the bug**
When applying a simple rate to a system, the system callback is never iterated. 
The reduction does not seem to matter, even a rate of 1 causes this.

**To Reproduce**
```
#include <flecs.h>
#include <iostream>

struct Position {
    float x, y;
};

int main(int argc, char* argv[])
{
    flecs::world world;

    world.system<Position>()
        .rate(2)
        .each([](Position & p){
        std::cout << "  position " << p.x << " " << p.y << std::endl;
    });

    world.entity().set<Position>({1.0,2.0});

    for(int i = 0; i < 10; i++) {
        std::cout << "Iteration " << i << std::endl;
        world.progress();
    }
  return 0;
}
```

**Expected behavior**
Every second iteration of progress should invoke the system callback, resulting in 5 printouts of the entity's position.
In reality, the system is never invoked.
Even if rate is set to 1, the system callback is never invoked.

**Additional context**
flecs v4.0.1
also tested on v4.0.2-alpha

**Comment by bgie** [comment]
I rewrote my mimimal reproducable example in the form of a test, like in /test/cpp/src/System.cpp
Haven't yet figured out how to run these tests though.

```
void System_rate(void) {
    flecs::world world;

    int invoked = 0;

    world.system<MyTag>()
        .rate(2)
        .each([&](flecs::entity e, MyTag) {
            invoked ++;
        });

    world.entity()
        .add<MyTag>();

    world.progress();
    world.progress();

    test_int(invoked, 1);
}
```

**Comment by dungeon2567** [comment]
I think rate is times per second. You need to pass delta time to progress else it will use realtime

**Comment by bgie** [comment]
Do not think so. [Documentation](https://www.flecs.dev/flecs/md_docs_2Systems.html#rate) has a minimal example, and does not mention times per second or delta time.

Consider the comment in the code example ` .rate(2) // Run every other frame`

**Comment by bgie** [comment]
Debugged it myself and found the cause.

In `timer.c` the function `ProgressRateFilters` does not reach any of the `inc=true` lines because setting a rate on a system with no tick source, sets the tick source to the system itself. (This is done in `flecs_system_init_timer`)  This means the source tick for the rate filter is retrieved from the system itself, but it looks like the system itself never emits ticks.

It looks like this should be the job of another function `ProgressTickSource`. But it mentions in a comment that it only queries entities without a filter. This means every system without rate or interval can act as a tick source. But if a rate is applied to a system, `ProgressTickSource` does not process it.


Possible fixes:
- In `ProgressRateFilters` the `if (src) {` can be changed into `if (src && src != it->entities[i]) {`
- In `flecs_system_init_timer` the `if (!tick_source) {` block can be removed.

I dont know which one to pick, there could be side effects.

**Workaround** without patching the code:
- create a separate system without rate or interval just for the ticks. Set that system as the tick source for systems that need to use a rate.

**Comment by SanderMertens** [comment]
Fixed!

**Comment by bgie** [comment]
Awesome, thanks!
