### ISSUE TITLE
Specifying that the last system writes a component type causes an abort

### ISSUE THREAD

**Issue by Gaspard--** [SanderMertens/flecs#1339]
**Describe the bug**
Specifying that the last system writes a component type causes an abort on world destruction.

**To Reproduce**
```cpp
void System_final_system_writes(void) {
    flecs::world world;
    struct A{
        int x;
    };

    world.system("Test")
        .write<A>()
        .run([](flecs::iter&){});
    world.progress();
}
```
Output:
```
fatal: stack_allocator.c: 187: assert: stack->cursor_count == 0 a stack allocator leak is most likely due to an unterminated iteration: call ecs_iter_fini to fix (LEAK_DETECTED)
```

**Expected behavior**
The code above should be a no-op instead.

**Additional context**
N/A

**Comment by Gaspard--** [comment]
I pushed the offending test here: https://github.com/Gaspard--/flecs/tree/final_system_writes_bug
This isn't a major issue since the use case is quite nonexistent, so I'm not going to investigate. It may point to a deeper underlying issue though.

**Comment by SanderMertens** [comment]
Fixed!
