### ISSUE TITLE
crash before invoking on_remove hook of sparse component

### ISSUE THREAD

**Issue by jpeletier** [SanderMertens/flecs#1359]
**Describe the bug**
When deleting an entity that has a sparse component and the sparse component has an `on_remove` hook declared, Flecs crashes with `fatal: iter.c: 119: assert: !(idr->flags & EcsIdIsSparse) use ecs_field_at to access fields for sparse components (INVALID_OPERATION)` assert error.

**To Reproduce**
```cpp
  flecs::world ecs;
  struct Attribute {
    int value;
  };

  auto attribute = ecs.component<Attribute>().add(flecs::Sparse);
  ecs.component<Attribute>().on_remove(
      [](flecs::entity e, Attribute &attr) { std::cout << "Attibute removed" << std::endl; });

  auto e = ecs.entity().add<Attribute>();

  e.destruct(); // fatal: iter.c: 119: assert: !(idr->flags & EcsIdIsSparse) 
                // use ecs_field_at to access fields for sparse components (INVALID_OPERATION)
```

**Expected behavior**
hook is called normally, as if the component wasn't sparse.

**Comment by SanderMertens** [comment]
Fixed!
