### ISSUE TITLE
uninitialized static data

### ISSUE THREAD

**Issue by Indra-db** [SanderMertens/flecs#1361]
for the units addon, all types are defined as `ECS_DECLARE(EcsCenti)`
which translated to `ecs_entity_t EcsCenti, FLECS_IDEcsCentiID_;`

when importing units module with `FlecsUnitsImport` , you only set `EcsCenti` variable, and `FLECS_IDEcsCentiID_` remains 0 initialized.

these statics are also duplicated due to it, and for example exposed twice when generating bindings for it

<img width="492" alt="image" src="https://github.com/user-attachments/assets/1806debb-913b-4859-abe7-8be39ecc3579">

Up to you how you would like to solve this, either by removing the `FLECS_IDxxxID_` variant or setting `Ecsx = FLECS_IDxxxID_`

**Comment by Indra-db** [comment]
Hm. I should have filed this as a bug instead, instead of a blank issue. My first thought was "this isn't really a bug bug" , but on second thought, it is

**Comment by SanderMertens** [comment]
Fixed!
