### ISSUE TITLE
When using components in a relationship pair, data is mixed if writing to first or second for the same pair

### ISSUE THREAD

**Issue by jpeletier** [SanderMertens/flecs#1384]
**Describe the bug**
When both elements of a pair are components and different entities are set with data in either first or second, data is put in the same column and considered the same in queries. Flecs detects when components are of different size and aborts, but if both happen to be of the same size, execution continues but data is reinterpreted.

**To Reproduce**
```cpp

// the example assumes sizeof(int) == sizeof(float); true in GCC x64 / Linux.

  struct A {
    int value;
  };

  struct B {
    float value;
  };

  assert( sizeof(A) == sizeof(B) );

  auto e1 = ecs.entity("E1");
  auto e2 = ecs.entity("E2");

  auto a = ecs.component<A>();
  auto b = ecs.component<B>();

  e1.set<A>(b, {.value = 3});
  e2.set_second<B>(a, {.value = 4.0});

  std::cout << "first query (A,B) with 'B' containing data:" << std::endl;
  ecs.query_builder<const B>()
    .term_at(0).first(a).second(b)
    .build().each([](flecs::entity e, const B &b) {

    std::cout << "e=" << e.name().c_str() << " value = " << b.value << std::endl;

  });

  std::cout << "second query (A,B), with A containing data:" << std::endl;
  ecs.query_builder<const A>()
    .term_at(0).second(b)
    .build().each([](flecs::entity e, const A &a) {
    
    std::cout << "e=" << e.name().c_str() << " value = " << a.value << std::endl;
  
});
```

Output is:

```
first query (A,B) with 'B' containing data:
e=E1 value = 4.2039e-45 <-- int reinterpreted as float
e=E2 value = 4
second query (A,B), with A containing data:
e=E1 value = 3
e=E2 value = 1082130432 <-- float reinterpreted as int.
```

**Expected behavior**
I was expecting the following at first:
```
first query (A,B) with 'B' containing data:
e=E2 value = 4
second query (A,B), with 'A' containing data:
e=E1 value = 3
```

But really, I think that if data has been already set on the first element of a given pair, the pair should acquire the type of the first element during the lifetime of the world; and therefore any subsequent set must be also on the first element. If the condition is not satisfied, the program should abort as may be this is a programming error:

```cpp
  e1.set<A>(b, {.value = 3}); // ok, first time we see (A,B)
  e2.set_second<B>(a, {.value = 4.0}); // crash now, does not make sense.
```

Perhaps this is a non-issue. Nevertheless I believe it should at least be documented somewhere, as a caveat or possible pitfall and wanted to let everyone know just in case :-)

### EDIT:

`ecs_get_type_info(ecs, ecs_pair(a, b));` resolves the tie and returns `A` as the underlying type for this particular example, therefore I would actually expect:
```cpp
  e2.set_second<B>(a, {.value = 4.0});
```
to crash outright, since the underlying type for the pair is `A`, this operation should not be allowed.

**Comment by jpeletier** [comment]
Yes, what you mention is documented here: https://www.flecs.dev/flecs/md_docs_2Relationships.html#relationship-components

I understand this is a programmer error, but no warning or error is given, other than receiving garbage data in queries, which is confusing.

**Comment by copygirl** [comment]
From what I understand, Flecs can figure out the type of a pair given two type parameters, so in theory it could be possible to assert that, which would require using a `set<A, B>(value)` function (which I'm unsure if that exists). Using `set<A>` and `set_second<B>` doesn't give the compiler enough information to check if what you're doing is correct.

And I also don't believe it would be possible to get any sort of compile time type checking in a query through the chained `.term_at(0).first(a).second(b)` functions.

**Comment by jpeletier** [comment]
Well, I was not expecting a compile-time error, but at least some sort of runtime-error / abort.

Actually, I found out that:

```cpp
  auto ti = ecs_get_type_info(ecs, ecs_pair(a, b));
  std::cout << "name:" << ti->name << std::endl;
```
Prints `name: A`, therefore Flecs already understands that for this specific pair in my example, where both types are components the underlying data type should be A. and:

```cpp
 e2.set_second<B>(a, {.value = 4});
```
should crash.

Perhaps `set` should check when setting a pair with first:
```cpp
 assert( ecs_get_type_info(ecs, ecs_pair(first, second))->component == first );
```
and set_second should check:
```cpp
 assert( ecs_get_type_info(ecs, ecs_pair(first, second))->component == second );
```

at runtime.

**Comment by copygirl** [comment]
You're right. It may be worth considering runtime debug asserts for this.

**Comment by Indra-db** [comment]
@copygirl @jpeletier 

Something worth considering, what the Rust API does for flecs,

I panic when calling a bunch of functions like 
  ecs.query_builder<const B>()
    .term_at(0).first(a).second(b)
    
when referencing a type parameter
   
this because rust has to be type safe by default

code in question:

`
fn check_term_access_validity<'a>(term: &impl TermBuilderImpl<'a>) {
    if term.current_term_index() < term.count_generic_terms()
        && term.current_term_ref_mode() != TermRefMode::Src
    {
        panic!("This function should only be used on terms that are not part of the generic type signature. ")
    }
}

    /// * C++ API: `term_builder_i::first`
    fn set_first<T: ComponentId>(&mut self) -> &mut Self {
        check_term_access_validity(self);
        self.set_first_id(T::id(self.world()))
    }
`

**Comment by SanderMertens** [comment]
@jpeletier the behavior that determines which type a pair assumes is documented here: https://www.flecs.dev/flecs/md_docs_2Relationships.html#relationship-components

I think this can be caught early by an assert. Will take a look.

**Comment by jpeletier** [comment]
Yes, I am aware of that. Every now and then come back to re-read it! :-)

I wonder if the solution is too expensive, I can't think of anything other than:

`set` should check when setting a pair with first:
```cpp
 assert( ecs_get_type_info(ecs, ecs_pair(first, second))->component == first );
```
and `set_second` should check:
```cpp
 assert( ecs_get_type_info(ecs, ecs_pair(first, second))->component == second );
```

But that implies bringing over type info at a performance penalty. Is there any bitmask wizardry that could return the pair's type?

**Comment by SanderMertens** [comment]
Unfortunately not, the asserts you're suggesting would be the right way to do it. It would add performance overhead in debug mode, though it shouldn't be prohibitive.

**Comment by Indra-db** [comment]
@jpeletier if you want suggestions on how Rust API does it:

```rs
pub fn set_id<T>(self, data: T, id: impl IntoId) -> Self
{
    let world = self.world.world_ptr_mut();
    let id = *id.into();
    let data_id = T::id(self.world);
    let id_data_id = unsafe { sys::ecs_get_typeid(world, id) };
    if data_id != id_data_id {
        panic!("Data type does not match id type. For pairs this is the first element occurrence that is not a zero-size
    }
 ```
 
 ```rs
 pub fn set_first<First>(self, first: First, second: impl Into<Entity>) -> Self
{
    let world_ptr = self.world.world_ptr_mut();
    let first_id = First::id(self.world);
    let second_id = *second.into();
    let pair_id = ecs_pair(first_id, second_id);
    let data_id = unsafe { sys::ecs_get_typeid(world_ptr, pair_id) };
    if data_id != first_id {
        panic!("First type does not match id data type. For pairs this is the first element occurrence that is not a zero-
    }
```

```rs
pub fn add_id(self, id: impl IntoId) -> Self {
    let id = *id.into();
    let world = self.world.world_ptr_mut();
    check_add_id_validity(world, id);
    unsafe { sys::ecs_add_id(world, *self.id, id) }
    self
}
```
where
```rs
pub(crate) fn check_add_id_validity(world: *const sys::ecs_world_t, id: u64) {
    let is_valid_id = unsafe { sys::ecs_id_is_valid(world, id) };

    if !is_valid_id {
        panic!("Id is not a valid component, pair or entity.");
    }

    let is_not_tag = unsafe { sys::ecs_get_typeid(world, id) != 0 };

    if is_not_tag {
        assert!(has_default_hook(world,id),"Id is not a zero-sized type (ZST) such as a Tag or Entity or does not implement the Default hook for a non ZST type. Default hooks are automatically implemented if the type has a Default trait.");
    }
}
```

**Comment by Indra-db** [comment]
most (hopefully all) of these safety regards, have been solved in the rust API, since rust requires it, so feel free to take a peek there or ask me

**Comment by SanderMertens** [comment]
Fixed!
