### ISSUE TITLE
flecs for C++ without bake?

### ISSUE THREAD

**Issue by NIKEA-SOFT** [SanderMertens/flecs#143]
Hello, is it possible to use Flecs without Bake? 
I tried to compile static lib via cmake and successfully linked it to the project replacing stdint.h with cstdint, however, when compiling I get a bunch of errors saying that the called functions were not found. In other words, he does not see the .lib file that I linked.

MSVC, С++17, Win x64

**Comment by NIKEA-SOFT** [comment]
I managed to load flecs files into the project as .h, .c files. I fixed a couple of errors and it seems to work, but what are the consequences of this use?

**Comment by NIKEA-SOFT** [comment]
It's bug here? column's type is int32_t but ecs_vector_count return uint32_t, here need cast ecs_vector_count to int32_t before use unary minus?
https://github.com/SanderMertens/flecs/blob/ea0470b9f5cc91fd8ff234349cf14e304acb9e79/src/column_system.c#L287

Here to 
https://github.com/SanderMertens/flecs/blob/ea0470b9f5cc91fd8ff234349cf14e304acb9e79/src/system.c#L612

**Comment by SanderMertens** [comment]
@NIKEA-SOFT Building flecs without bake is fully supported! Note that the repository also has CMake, Meson and Bazel build files.

Re the signed/unsigned mismatch, that has been fixed on the bleeding_edge branch, and will be merged into master for the next minor release.

**Comment by NIKEA-SOFT** [comment]
> @NIKEA-SOFT Building flecs without bake is fully supported! Note that the repository also has CMake, Meson and Bazel build files.
> 
> Re the signed/unsigned mismatch, that has been fixed on the bleeding_edge branch, and will be merged into master for the next minor release.

Yes, Flecs works if you integrate it into the project, however, I still could not add modules to the project.

**Comment by SanderMertens** [comment]
@NIKEA-SOFT the easiest way to use the modules is to also add their sources to the project. 

There is another way that requires you to tell Flecs how to map a module id (like `flecs.systems.admin`) to a library name `libflecs_systems_admin.so`.

To do this, you have to override a function pointer in the `os_api`, which you can do like this:

```c
// Set default calls, like malloc, free
ecs_os_set_api_defaults();

// Obtain a private writable copy of the os_api struct
ecs_os_api_t os_api = ecs_os_api;

// Override call that maps module id to library name
os_api.module_to_dl = my_module_to_dll;

// Set the custom API callbacks
ecs_os_set_api(&os_api);
```

The `my_module_to_dll` function can be implemented like this:

```c
static
char* bake_module_to_dl(
    const char *module_id)
{
   if (!strcmp(module_id, "flecs.systems.admin") {
       return strdup("libflecs_systems_admin.so");
   } else {
       // whatever other rules you'd like to add
   }
}
```
Once you've done that, you can use the `ecs_import_from_library` function:

```c
if (ecs_import_from_library(world, "flecs.systems.admin", NULL, 0)) {
    // err
}
```

You can now also use the following functions:
```c
ecs_enable_admin(world, 9090);
ecs_enable_console(world);
```

**Comment by SanderMertens** [comment]
Closing this issue, feel free to reopen if you're still having issues. 

Note that for Flecs v2, the build process has become a lot simpler as you can now simply add flecs.c and flecs.h to your project.
