### ISSUE TITLE
Custom module path can cause entity deletions

### ISSUE THREAD

**Issue by nimble0** [SanderMertens/flecs#1432]
**Describe the bug**
Using a module path different to the CPP class path can cause entity deletions. Specifically it happens when the path does not include the namespaces of the CPP class path.

These entity deletions can then cause unpredictability in system execution order.

This was introduced in 9a8c826fa1d84de402b6832ffcdfdccd8e104636

**To Reproduce**
Changed hello_world example:
```
#include <hello_world.h>
#include <iostream>

namespace outer {

struct Module
{
	Module(flecs::world& world)
	{
		world.module<Module>("::MyModule");
		// No issues because paths includes outer namespace
		// world.module<Module>("::outer::MyModule");
		// world.module<Module>("::outer::inner::MyModule");

		for(int i = 0; i < 5; ++i)
		{
			auto e = world.entity();
			std::cout << "created entity " << e << "\n";
		}
	}
};

}


int main(int, char *[]) {
	// Create the world
	flecs::world ecs;

	ecs.import<outer::Module>();
}
```

**Expected behavior**
```
created entity 541
created entity 542
created entity 543
created entity 544
created entity 545
```

**Actual behavior**
```
created entity 4294967836
created entity 541
created entity 542
created entity 543
created entity 544
```

**Comment by SanderMertens** [comment]
Fixed!

**Comment by nimble0** [comment]
The fix appears to still recycle ids, in a way, just without increasing the generation.

**Example**
```cpp
#include <hello_world.h>
#include <iostream>

namespace outer {

struct Module
{
	Module(flecs::world& world)
	{
		world.module<Module>("::MyModule");
	}
};

}


int main(int, char *[]) {
	// Create the world
	flecs::world ecs;

	ecs.import<outer::Module>();

	ecs.set_entity_range(5000, 0);

	for(int i = 0; i < 5; ++i)
	{
		auto e = ecs.entity();
		std::cout << "created entity " << e << "\n";
	}
}
```

**Output**
```
created entity 496
created entity 5000
created entity 5001
created entity 5002
created entity 5003
```

**Comment by SanderMertens** [comment]
Yes, that is because of how the code works when you are providing a name to a module that is in a different scope than the type. What happens is:

- `import<outer::Module>()` is called -> code doesn't have the name yet
- `outer::Module` entity is created and set as scope for module contents
- module ctor changes name to `::MyModule`
- `outer` parent is no longer necessary, so needs to be deleted

Not sure if there's a way around this.

EDIT: the actual failure here is that an entity is recycled that is outside of the configured range. That's something I'm hoping to address soon.

**Comment by nimble0** [comment]
Yes, the entity range not being fully enforced is the real issue. Currently I'm working around this by creating new entities until I start getting entities within the entity range.

After reading your explanation, I found this example involving nested namespaces where it still exhibits the original issue.

**Example**
```cpp
#include <hello_world.h>
#include <iostream>

namespace outer::outer2 {

struct Module
{
	Module(flecs::world& world)
	{
		world.module<Module>("::MyModule");
	}
};

}


int main(int, char *[]) {
	// Create the world
	flecs::world ecs;

	ecs.import<outer::outer2::Module>();

	for(int i = 0; i < 5; ++i)
	{
		auto e = ecs.entity();
		std::cout << "created entity " << e << "\n";
	}
}
```

**Output**
```
created entity 496
created entity 497
created entity 4294967795
created entity 4294967794
created entity 502
```

**Comment by SanderMertens** [comment]
@nimble0 I'm closing this issue as I just landed a new ranges API that guarantees that entities are always returned in the right range. Let me know if you're still running into issues.

More details: https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-16444174

**Comment by nimble0** [comment]
Oh, I thought you reopened the issue for the example involving nested namespaces?

**Comment by SanderMertens** [comment]
I reopened it because of this: 

> Yes, the entity range not being fully enforced is the real issue.
