### ISSUE TITLE
Target FPS has several types and produces warnings

### ISSUE THREAD

**Issue by Maykeye** [SanderMertens/flecs#144]
**Describe the bug**
When compiling with a compiler which frowns between float<->uint32_t implicit conversions, code produces warnings because target fps is float in some places, integer in other:

* [flecs.hpp:world::ecs_set_target_fps](https://github.com/SanderMertens/flecs/blob/cfbf87728b7fc3a4688f888416717213cf0a0085/include/flecs/flecs.hpp#L365) expects std::uint32_t fps target_fps
* [flecs.hpp:world::get_target_fps](https://github.com/SanderMertens/flecs/blob/cfbf87728b7fc3a4688f888416717213cf0a0085/include/flecs/flecs.hpp#L369) returns std::uint32_t
* [flecs.h:ecs_set_target_fps](https://github.com/SanderMertens/flecs/blob/cfbf87728b7fc3a4688f888416717213cf0a0085/include/flecs.h#L486) expects float fps
* [flecs.h:ecs_get_target_fps](https://github.com/SanderMertens/flecs/blob/cfbf87728b7fc3a4688f888416717213cf0a0085/include/flecs.h#L497) returns uint32_t

**To Reproduce**
1) Compile in VS2017 c++ file with `#include <flecs.h>
2) get `>e:\work\vs2017.libs\flecs\include\flecs\flecs.hpp(361): warning C4244: 'argument': conversion from 'uint32_t' to 'float', possible loss of data`

**Expected behavior**
Same types everywhere with no warnings

**Additional context**
Related to #70 (compiler warnings with Visual Studio 2017), but if #70 it's one time problem - you compile the library and forget about it as you use compiled `lib`, here warnings produced every time you include the header in actual projects.

**Comment by SanderMertens** [comment]
Thanks for reporting! I'll change the type to float everywhere.
