### ISSUE TITLE
Readme.md and Manual.md don't mention that static linking requires FLECS_STATIC

### ISSUE THREAD

**Issue by Maykeye** [SanderMertens/flecs#148]
**Describe the bug**
If library is built statically, FLECS_STATIC macro should be used, otherwise linker will print cryptic errors about unresolved external symbols will appear in VS2017:

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	LNK2019	unresolved external symbol __imp_ecs_fini referenced in function "void __cdecl Test(void)" (?Test@@YAXXZ)	SFMLTest	e:\work\sfmltest\SFMLTest\Globals.obj	1	

However FLECS_STATIC is not mentioned in README.md so one have to manually grep through source code to find where and how `FLECS_EXPORT` is defined

**To Reproduce**
1) Build static library (with cmake then using generated solution in VS2017)
2) Link it in the project
3) Include flecs.h without defining  FLECS_STATIC 
4) See the error

**Expected behavior**
Readme/manual should mention FLECS_STATIC at some point

**Additional context**
Win10, VS2017

**Comment by AbdullahAmrSobh** [comment]
thanks Maykeye.
yes this is not mentioned in the Manual and if it was not for you i would not have got this library to work.

**Comment by SanderMertens** [comment]
Hi all, sorry for the late reply. Flecs v2 is around the corner, and it will no longer be necessary to define FLECS_STATIC for compiling a static library. Instead I use the `flecs_EXPORTS` macro that cmake defines automatically, so everything should work out of the box.

Here's an example cmake project in v2:
https://github.com/SanderMertens/flecs/tree/v2_in_progress/examples/build/cmake

Closing this issue.
