### ISSUE TITLE
Lua scripted system

### ISSUE THREAD

**Issue by alex-rass-88** [SanderMertens/flecs#152]
There is an idea to use lua for systems. For use in multiple threads, I need to initialize a VM for each thread. How can I do this better? Is there a way for each worker to add a callback to initialize thread-specific data (Lua VM for example)?

**Comment by ArnCarveris** [comment]
Checkout this: https://github.com/GamerJie/light_c

**Comment by alex-rass-88** [comment]
This implementation creates a new VM for each system, not for the thread.

**Comment by alex-rass-88** [comment]
I found a solution for myself. Each thread has an index. You just need to associate the thread index with the VM index . ecs_get_thread_index helps with this.

**Comment by SanderMertens** [comment]
@alex-rass-88 That sounds interesting, would you mind describing how you're integrating the Lua VM with the Flecs thread id? Could be interesting for other users, as this is a topic that pops up somewhat regularly.

**Comment by alex-rass-88** [comment]
After call ecs_set_threads(world, N), Flecs create threads and associate it with indexes.
Index 0 - main thread (https://github.com/SanderMertens/flecs/blob/master/src/worker.c#L117)
We create states: lua_State states[N], where N - number of threads. Add the API needed for each Lua  state. When executing the system where we need to call the script, we get the stream index (i = ecs_get_thread_index(world)) and run the script in the states [i] state . Each thread uses its own Lua state. The only condition is not to use global variables.

I bad speak english, but I think the basic idea is understandable.

**Comment by SanderMertens** [comment]
I'm closing this issue for now. I think this is an interesting idea, but will have to be implemented as a separate module / repository. Feel free to join the Discord (link in README) if you'd like to discuss further!
