### ISSUE TITLE
Bake command fails to create flecs project

### ISSUE THREAD

**Issue by jackwlee01** [SanderMertens/flecs#16]
Following the getting started instructions, the following command fails:

bake new my_app -t flecs

with the following error:

error template 'flecs' not found.

This is happening on MacOS 0.14.1.

**Comment by SanderMertens** [comment]
Oh, that sounds like a bake issue. Let me look into it!

**Comment by SanderMertens** [comment]
Fixed the issue, thanks for reporting it! Templates were not installed when projects were cloned. It should work after you update bake.

**Comment by SanderMertens** [comment]
I'll close this issue as it has been some time. If you're still having problems with this, feel free to file a new one!
