### ISSUE TITLE
Decide when to merge based on system inputs / outputs

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#163]
**Describe the problem you are trying to solve.**
Flecs stages data to allow for making structural modifications (add / remove / new / delete) while iterating over plain arrays. This lets applications use the regular Flecs API while iterating, without having to resort to out of bound data structures like a command buffer.

Staged data needs to be merged back into the main stage. Currently Flecs merges after each phase (OnUpdate, PostUpdate, ...). In practice this is not intuitive, as a system only sees structural modifications of previous systems in the previous phase, but not of the current phase. There are a few ways applications can address this issue:

- Make sure systems that require structural changes are in different phases (non intuitive, and there are only so many phases)
- Explicitly read from the stage with `ecs_get` (not performant, impacts system reusability)
- Use manual systems and run / merge manually (prevents using a lot of other Flecs features, systems aren't reusable)

None of these solutions are very usable. An ideal solution would allow for:
- a system to see all of the previous (structural) changes in the main stage so that it doesn't need to know whether to get changes from the main stage or not
- a system to declare what it is reading & writing _outside_ of the matched components, so that Flecs can decide when a merge is necessary.

A solution should _not_ rely on explicit system dependencies as this couples systems and makes them less reusable.

**Describe the solution you'd like**
A system should be able to declare the components it is reading / writing but not matching with. For example, a system may match with entities that have `Position, Velocity`, and add a tag `Moved`. This signature could look like this:

```
ECS_SYSTEM(world, Move, EcsOnUpdate, [out] Position, [in] Velocity, [out] .Moved);
```

Here, the signature explicitly states that `Moved` is not matched with (an empty FROM modifier), but that it is an `out` component, meaning that the system will either add or set it.

If a subsequent system matches with `Moved` using either `in` or `inout` (default) Flecs will know that a merge is needed:

```
// Need to merge changes made by Move before running PrintMoved
ECS_SYSTEM(world, PrintMoved, EcsOnUpdate, Moved);
```

Additionally, a system may also declare which components it is reading without matching with them:

```
ECS_SYSTEM(world, PrintUnits, EcsOnUpdate, Unit, [in] .Moved);
```

This indicates that `Move` needs to be _ran_ before `PrintUnits` (`Move` writes `Moved` which is read by `PrintUnits`) but no _merge_ is needed (`Moved` is not matched, and an `ecs_get` obtains data from the stage).

These additional annotations will allow Flecs to construct a DAG of systems that not only enable it to decide when to merge, but also allows systems to be ran in parallel, or combine multiple systems in a single iteration if they overlap.

**Comment by teksoc-1** [comment]
@SanderMertens After taking a look this issue, I think the solution approach is applicable to issue [164](https://github.com/SanderMertens/flecs/issues/164)
