### ISSUE TITLE
Task, System Column examples

### ISSUE THREAD

**Issue by nssgarcia** [SanderMertens/flecs#170]
**Describe the problem you are trying to solve.**
I can't see any example of a task and system columns in all the samples provided. I'm trying to call the "step" function of an external physics system (box2d, chipmunk2d, bulletPhysics) in a task and there is no example on how to register the physics api as a System.column and there is no example on how to call tasks with system columns, neither tasks.
Additional information: Chipmunk2d is writenn in C, so it hides all functionalities in pointers, so it will be grate if the "System.column" could be a pointer in c++ api.

**Describe the solution you'd like**
Please, could you create an example with system columns and an example on task with only system columns? (I'm working with c++ API) Thanks in advance

**Comment by nssgarcia** [comment]
I was able to make it work, I'm adding an example with chipmunk2d physics system that works on c++11. In this example calling cpSystemInit, passing the chipmunk space pointer (physics system) registers it to update event and creates a task with a SYSTEM column and executes the step event on each flecs progress call with the delta time. Maybe is not so well implemented, but it works as expected.

`void CpSpaceTask(flecs::rows& rows, flecs::column<cpSpace*> space) {
    cpSpaceStep(space[0], rows.delta_time());
}

void cpSystemInit(flecs::world& world, cpSpace* space) {
    flecs::component<cpSpace*>(world, "CpSpacePtr");
    
    auto& cpSpaceTask = flecs::system<cpSpace*>(world)
                    .signature("SYSTEM.CpSpacePtr")
                    .action(CpSpaceTask);
    *cpSpaceTask.get_ptr<cpSpace*>() = space;
}`

**Comment by SanderMertens** [comment]
Added the examples!
