### ISSUE TITLE
OnAdd with System column signature with initial values not triggering.

### ISSUE THREAD

**Issue by nssgarcia** [SanderMertens/flecs#172]
**Describe the bug**
When creating bulk entities and adding an OnAdd system to initialize this components as recommended in the manual there is no way to pass an array with the initial values to the system.

> What can provide an even bigger performance boost is that when entities are created in bulk with an initial set of components, the EcsOnAdd handler for initializing those components is called with an array that contains the new entities vs. for each entity individually

**To Reproduce**

I'm registering the system with this signature, I'm adding the array with the initial data to the custom context variable but it never gets triggered.
```
auto& bodyCompOnAdd = flecs::system<CustomContext*, BodyComp>(world)
        .signature("SYSTEM.CustomContextPtr, BodyComp")
        .kind(flecs::OnAdd)
        .action(BodyCompOnAddWithContext);
*bodyCompOnAdd.get_ptr<CustomContext*>() = context;
```
But if I register the OnAdd system with this signature it gets triggered but there is no way to pass the array with the initial values to it.
```
flecs::system<BodyComp>(world)
        .signature("BodyComp")
        .kind(flecs::OnAdd)
        .action(BodyCompOnAdd);
```

**Expected behavior**
In order to pass an array to the OnAdd event, there should be a way to pas the initial values to it.

**Additional context**

**Comment by nssgarcia** [comment]
I was able to overcome this by adding a component to the system, please don't remove this functionality.

```
// Declare components
flecs::component<BodyComp>(world, "BodyComp");
flecs::component<CustomContext*>(world, "CustomContextPtr");

// Add system on add BodyComp
auto& bodyCompOnAdd = flecs::system<BodyComp>(world)
        .signature("BodyComp")
        .kind(flecs::OnAdd)
        .action(BodyOnAdd);
ferretBodyOnAdd.set<CustomContext*>(context);

// BodyOnAdd system definition
void BodyOnAdd(flecs::rows& rows, flecs::column<BodyComp> bodyComp) {
    PlasticContext* context = rows.system().get<PlasticContext*>();
    for (auto& row : rows) {
        auto e = rows.entity(row).id();
        auto& comp = bodyComp[row];
        comp.body = context->getBody(e);
    }
}

// Before calling bulk creation on body add, all bodies should be defined in the context
auto range = flecs::entity_range(world, count);
context.lowerId = *range.begin(); // Get lower id
// Add all bodies to the context
range.add<BodyComp>(); // This will trigger the onAdd system
```

**Comment by SanderMertens** [comment]
The issue in the code you posted is the way you define the system in the C++ API:

```c++
auto& bodyCompOnAdd = flecs::system<CustomContext*, BodyComp>(world)
        .signature("SYSTEM.CustomContextPtr, BodyComp")
```

The components from the template parameters and signature get appended, so that the full signature looks like this:

```
CustomContextPtr, BodyComp, SYSTEM.CustomContextPtr, BodyComp
```

This will cause Flecs to trigger only when you add `BodyComp` and `CustomContextPtr`, which is not what you want. Try defining the system like this:

```c++
auto& bodyCompOnAdd = flecs::system<BodyComp>(world)
        .signature("SYSTEM.CustomContextPtr")
```

And let me know if that works!
