### ISSUE TITLE
Cpp API OnAdd event with bulk triggers multiple events with one row

### ISSUE THREAD

**Issue by Josid88** [SanderMertens/flecs#173]
**Describe the bug**
Cpp API OnAdd event with bulk triggers multiple events with one row, instead a single event with multiple rows should be triggered.

**To Reproduce**
```
struct Position {
    float x;
    float y;
};

void PositionOnAdd(flecs::rows& rows, flecs::column<Position> bodyComp) {
    std::cout << "On add call" << std::endl;
    for (auto& row : rows) {
        auto e = rows.entity(row).id();
        std::cout << e << ".- Row call" << std::endl;
    }
}
int main(int argc, char *argv[]) {
    flecs::world world;
    
    flecs::component<Position>(world, "Position");
    
    flecs::system<Position>(world)
        .signature("Position")
        .kind(flecs::OnAdd)
        .action(PositionOnAdd);
    
    // Create 3 entities with Position
    flecs::entity_range(world, 3)
        .add<Position>();
}
```
The console prints:
**On add call**
19.- Row call
**On add call**
20.- Row call
**On add call**
21.- Row call

**Expected behavior**
The console shall print :
**On add call**
19.- Row call
20.- Row call
21.- Row call

**Additional context**
Ubuntu on x64

**Comment by SanderMertens** [comment]
Hi @Josid88, thanks for reporting!

There is no obvious solution to do this in combination with the fluent API, but I agree that this would be great to have. Let me think a bit on this and I'll get back to you.

**Comment by SanderMertens** [comment]
Changed this to enhancement, since it is not a bug (nothing breaks).

**Comment by SanderMertens** [comment]
The entity range API was deprecated and has been removed in v3!
