### ISSUE TITLE
Trigger Newly Created Reactive System inside Single Staged System

### ISSUE THREAD

**Issue by teksoc-1** [SanderMertens/flecs#176]
**Describe the bug**
Triggering a newly created reactive system (i.e. EcsOnAdd) inside a  single stage system (i.e. EcsOnLoad) generates an assertion failure.

**To Reproduce**
```c
#include "flecs.h"

#define TRIGGER_ASSERTION_FAILURE 1

typedef int A;
typedef int B;

int SystemBRan = 0;

void
SystemB( ecs_rows_t * rows )
{
    SystemBRan = 1;
}

void
SystemA( ecs_rows_t * rows )
{
    ECS_COLUMN_COMPONENT( rows, B, 2 );
    
    ECS_SYSTEM( rows->world, SystemB, EcsOnAdd, B );
    
#if TRIGGER_ASSERTION_FAILURE
    _ecs_add( rows->world, rows->entities[ 0 ], TB );
#endif
    
}

int
main( int argc, const char * argv[] )
{
    ecs_world_t * world = ecs_init();
    ecs_entity_t e = ECS_INVALID_ENTITY;
    
    ECS_COMPONENT( world, A );
    ECS_COMPONENT( world, B );
    
    ECS_SYSTEM( world, SystemA, EcsOnLoad, A, !B );

    e = ecs_new( world, A );
    
    ecs_progress( world, 0 );
    
    _ecs_add( world, e, TB );
        
    ecs_assert( 0 != SystemBRan, ECS_INTERNAL_ERROR, NULL );
    
    return ecs_fini( world );
}   
```

**Expected behavior**
Reactive system is executed and program successfully terminates. Setting TRIGGER_ASSERTION_FAILURE to 0 demonstrates the reactive system is in fact successfully registered and triggered via `_ecs_add()` when called external to the single stage system.

**Additional context**
Unsure if this functionality was ever a supported design construct, however it did provide utility. Unsure where/when exactly it broke. Also find the same behavior if in the example above if SystemA is registered as a manual system and invoked via `ecs_run()`.

**Comment by SanderMertens** [comment]
Sorry for the late reply, I'm currently working on fixing v2 issues. I'll get on this right after that!

**Comment by SanderMertens** [comment]
@teksoc-1 closing this issue as it's illegal to create systems (and now in v2, triggers for OnAdd / OnRemove) while in a system (as discussed). I'll make sure to add some asserts to the code so it's clear why this doesn't work.
