### ISSUE TITLE
Component registered twice when creating and destroying multiple worlds

### ISSUE THREAD

**Issue by Josid88** [SanderMertens/flecs#179]
**Describe the bug**
Creating a world and destroying it, then creating another world throws component registered twice error

**To Reproduce**

#include <cassert>
#include <flecs.h>
#include <flecs/flecs.hpp>

int main(int argc, char** argv) {
    flecs::world* w = new flecs::world;
    delete w;
    flecs::world* w2 = new flecs::world;
    delete w2;
}

component registered twice with a different name (EcsComponent)

**Expected behavior**
Be able to create and destroy worlds

**Additional context**
Ubuntu 64bit with cmake

**Comment by SanderMertens** [comment]
I fixed this issue, and also ensured that when components are registered across multiple worlds in C++ they keep the same identifiers.

**Comment by duddel** [comment]
Not sure if this is related, but I see a similar issue when the component is in a namespace:

```c++
namespace A
{
    struct Distance
    {
        float x;
    };
}

int main()
{
    flecs::world *fw = new flecs::world();
    fw->component<A::Distance>();
    delete fw;
    fw = new flecs::world();
    fw->component<A::Distance>();

    // component registered twice with a different name (A::Distance)
}
```

latest master: https://github.com/SanderMertens/flecs/commit/1458bd83d747373e18c30c5c58c2b99d298e9583
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 7.3.0 on Windows 10

**Comment by SanderMertens** [comment]
@duddel looking into this

**Comment by SanderMertens** [comment]
Checked in a fix! Let me know if you're still having issues with this.

**Comment by duddel** [comment]
> Checked in a fix! Let me know if you're still having issues with this.

That solved it for me, thanks alot!
