### ISSUE TITLE
V2 wishlist (post your requests / ideas!)

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#181]
Flecs v2 will be released in the near future, and I wanted to do a give everyone an opportunity to share ideas / improvements that they would like to see. V2 is a breaking change, which lets me fix some things I can't do in a minor release.

The v2 branch: https://github.com/SanderMertens/flecs/tree/v2_in_progress

Also consider joining Discord where a lot of the discussion is taking place: https://discord.gg/MRSAZqb

**Comment by SanderMertens** [comment]
From Discord:
There should be a way for Flecs to make a copy of the string in EcsId to avoid resource management on application side.

**Comment by SanderMertens** [comment]
From Discord:
Undefine macro's in C++ API, and get rid of T0 (and T/E prefixes).

**Comment by SanderMertens** [comment]
From Discord:
Allow for a deferred event handling.

**Comment by SanderMertens** [comment]
From Discord: add configurable tracing.

**Comment by SanderMertens** [comment]
From Discord:
API to obtain information from system (such as matched components, signature).

**Comment by SanderMertens** [comment]
From Discord:
Allow for creation of systems / components / ... with an explicit entity id.

**Comment by SanderMertens** [comment]
From Discord:
Allow specifying a thread id to ecs_staging_begin

**Comment by ArnCarveris** [comment]
Allow to create system via `ecs_new_system_w_sig`

**Comment by ArnCarveris** [comment]
Allow to pass `ecs_filter_t` to pipeline

**Comment by ArnCarveris** [comment]
Allow to create query via `ecs_query_new_w_sig`

**Comment by ArnCarveris** [comment]
Allow to specify pagination for `ecs_filter_t` via `ecs_filter_iter_page(filter, offset, limit)`

**Comment by ArnCarveris** [comment]
Allow to specify pagination for `ecs_query_t` via `ecs_query_iter_page(filter, offset, limit)`
