### ISSUE TITLE
Inconsistent tags

### ISSUE THREAD

**Issue by egorpugin** [SanderMertens/flecs#188]
`v1.2` but `1.3`
This breaks scripts.

Could you use tags with or without `v` consistently?
Maybe you could use always three-number semver for releases?
https://semver.org/

![image](https://user-images.githubusercontent.com/4325333/85373560-1dbfdd80-b53c-11ea-9997-c3d836495243.png)

**Comment by SanderMertens** [comment]
My bad! Using a three number tag sounds like a good idea.

**Comment by egorpugin** [comment]
Bump. Missing the third number.

![image](https://user-images.githubusercontent.com/4325333/95346803-e267d580-08c4-11eb-92ce-fc901a8fa3bb.png)

**Comment by SanderMertens** [comment]
@egorpugin Sorry! Fixed it afterwards. I wish I could tell Github somehow to prevent me from creating ill-formed tags
