### ISSUE TITLE
ability to remove constexpr

### ISSUE THREAD

**Issue by dgoad95** [SanderMertens/flecs#210]
**Describe the problem you are trying to solve.**
I'm still using Visual Studio 2013, which has partial c++11 support. It does, however, lack constexpr support, therefore flecs will not compile under it (even Visual Studio 2013 Update 5, despite what the Internet tries to tell me).

I got the following errors as well:
I got a compiler error saying "'int32_t' is not a member of 'std'" unless #include <cstdint.h> comes before #include "flecs.h"
I got a compiler error with alignof, but changing to __alignof made it go away...not sure what the difference is.
I got a compiler error with std::enable_if as well: error C2039: 'type' : is not a member of 'std::enable_if<false,void>'.

**Describe the solution you'd like**
A macro that would disable constexpr, or a compiler version detection macro that would disable it.

I'm using the flecs 2.0 release from today. it's probably honestly time for me to bite the bullet and upgrade my Visual Studios, but I like 2013 oh so much, and I really don't want to.

**Comment by SanderMertens** [comment]
Hi @dgoad95, I tried to make the C++11 API work for older compilers, but ran into a lot of issues, some of which you outlined above. Older versions of GCC with partial C++11 support also have trouble with the API, and it is unfortunately not straightforward to modify the API, as the C++11 features are important for some of the wrappers.

For now I suggest that you either upgrade to a later version of MSVC (if possible), or use the C API, which should also work properly in C++.

On the Discord there is someone that is working on a legacy C++ API though I'm not sure if it is in a shareable state. If you're interested, here is an invite: https://discord.gg/MRSAZqb

**Comment by SanderMertens** [comment]
I'm closing this issue, as there are no immediate actions to take.
