### ISSUE TITLE
Flecs.c and Flecs.h links in README.md are broken

### ISSUE THREAD

**Issue by Keating950** [SanderMertens/flecs#213]
> The easiest way to add Flecs to a project is to add [flecs.c](https://github.com/flecs/master/flecs.c) and [flecs.h](https://github.com/flecs/master/flecs.h) to your source code. These files can be added to both C and C++ projects (the C++ API is embedded in flecs.h). Alternatively you can also build Flecs as a library by using the cmake, meson, bazel or bake buildfiles.

The links in the README.md to these files lead to a page simply saying `Not Found`.

For reference:
https://github.com/flecs/master/flecs.c
https://github.com/flecs/master/flecs.h

Proper links:
https://raw.githubusercontent.com/SanderMertens/flecs/master/flecs.c
https://raw.githubusercontent.com/SanderMertens/flecs/master/flecs.h

**Comment by SanderMertens** [comment]
Merged the PR, thanks again!
