### ISSUE TITLE
Implement system scheduling parameters

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#22]
Currently when using threads, Flecs splits up the workload of a system into multiple jobs by assigning each job `total_matched_entities / thread_count` entities. It does this for every system not in `EcsOnLoad` and `EcsOnStore`.

This design is an all-or-nothing approach, and typically an application has systems that can either be ran on N threads or one thread. To let the scheduler know how it should schedule systems, an application should be able to provide scheduling parameters.

This could be done through an `EcsSchedulingParams` component, which could look something like this (design not yet finalized):

```c
ECS_SYSTEM(world, Sys, EcsOnUpdate, Position, 
   SYSTEM.EcsSchedulingParams = {.bind_to_threads = [0, -1]);
```

In the above example, `0` could refer to the main thread, a non-zero value to a worker thread, and `-1` could refer to all worker threads. Additionally, applications could specify whether a system shared threads with other systems, and whether a system wants to run without any other systems running.

**Comment by ArnCarveris** [comment]
What about this:
`ECS_SYSTEM(world, Sys, EcsOnUpdate, Position, 
   SYSTEM.EcsSchedulingParams = {.bind_to_threads = [EcsThreadMain, EcsTheadAnyWorker]);`

**Comment by SanderMertens** [comment]
Looks good to me 👍

**Comment by ArnCarveris** [comment]
`EcsTheadAny = -2` - main or worker thread, so there you get:
```c
ECS_SYSTEM(world, Sys, EcsOnUpdate, Position, 
 SYSTEM.EcsSchedulingParams = {.bind_to_threads = [EcsThreadAny]);
```

**Comment by SanderMertens** [comment]
Another option could be to start counting threads from `1`, reserve negative numbers for exclusivity, and `0` for automatic scheduling, so you could do:

```
n_threads = 4
SystemA: [-1, 2] // Claim main thread exclusively, and share thread 2
SystemB: [2, -3] // Share thread 2 and claim thread 3 exclusively
SystemC: [0] // Run on thread 2 and 4
SystemD: [0] // Run on thread 2 and 4
```

If the capability to run on only worker threads is needed, `MAX_INT` could be reserved for that:

```
SystemA: [MAX_INT] // Only run on worker threads
```

**Comment by ArnCarveris** [comment]
@SanderMertens what you mean by `claim` ?

**Comment by SanderMertens** [comment]
It means that no other systems can run on that thread (within that phase). For example, if I have a render system, I could make it run on the main thread, and make sure that no other systems are running on it.

**Comment by ArnCarveris** [comment]
We need macros for these:
`ECS_THREAD_AUTO()  0`
`ECS_THREAD_WORKER_ONLY() MAX_INT`
`ECS_THREAD_SHARED(i) i`
`ECS_THREAD_RESERVED(i) -i`

**Comment by ArnCarveris** [comment]
This will force systems to run on thread 2 one-by-one in order:
```
SystemA: [ECS_THREAD_RESERVED(2)] 
SystemB: [ECS_THREAD_RESERVED(2)] 
SystemC: [ECS_THREAD_RESERVED(2)] 
SystemD: [ECS_THREAD_RESERVED(2)]
```

**Comment by SanderMertens** [comment]
I'm closing this issue for now because there are big upcoming changes that affect this (staging redesign, custom phases). We can reevaluate once those changes have been made.
