### ISSUE TITLE
Missing intructions on how to use flecs-systems-admin and other components from Meson.

### ISSUE THREAD

**Issue by gegoxaren** [SanderMertens/flecs#256]
**Use Meson to build project without the need for Bake.**
The current Flecs documentation relies on a non-standard build system for all modules, and does not provide any instruction on how to use these modules from Meson.

**Add Meson.build files to the modules.**
To solve this in the most effective way would be to use Mesons builtin [subproject system](https://mesonbuild.com/Subprojects.html) to so solve this. That means that no external tools need to be invoked from Meson. The ability to use [Mesons Wrap system](https://mesonbuild.com/Wrap-dependency-system-manual.html) would also be a plus, for those that use it.

I have made a [simple template](https://github.com/gegoxaren/flecs-template-meson) that I hoped to be able to use for some experiments.

Thank you for listing
// Gustav.

**Comment by randy408** [comment]
Ideally the CMake and Meson files would be auto-generated like the amalgamations.

**Comment by randy408** [comment]
With recent versions of Meson you can add your own `meson.build` for projects that don't have one, that is how it was done for flecs-lua when flecs-meta didn't have a `meson.build` https://github.com/flecs-hub/flecs-lua/tree/aaa2869b8d913a6b0b2ee3944fb532959c17bbae/subprojects

Also, your top-level project can have its own .wrap's for specific versions of each dependency, if you initialize them with `subproject()` the dependencies will be overridden for all the subprojects with that version (assuming `meson.override_dependency()` is used).

Adding .wrap's for all modules would be nice, but then again it's unlikely a module is built on its own, and they're not needed if the superproject already has the right .wrap's.

**Comment by SanderMertens** [comment]
I added build instructions to the flecs-dash repository: https://github.com/flecs-hub/flecs-dash

Closing this issue for now, as the dashboard can be used with any build system (you just add the source files to your project). I agree with @randy408 that eventually meson/cmake files should be automatically generated. In the meantime, I'll accept PRs that add meson/cmake files to module projects!
