### ISSUE TITLE
Function for checking if subquery is orphaned

### ISSUE THREAD

**Issue by randy408** [SanderMertens/flecs#258]
**Describe the problem you are trying to solve.**
Binding the subquery API for a garbage collected language is more difficult than it should be, if the parent query is GC'd the subquery will not work as intended, but there is no easy way to detect that.

**Describe the solution you'd like**
Mark the subqueries as orphaned when the parent query is freed and add a new function e.g. `ecs_query_orphaned()`

**Comment by SanderMertens** [comment]
Done!
