### ISSUE TITLE
C++ example 34 (persistent_query) asserts

### ISSUE THREAD

**Issue by duddel** [SanderMertens/flecs#261]
**Describe the bug**
The example 34 (persistent_query) asserts with _"invalid access to readonly column (use const)"_.
This happens while creating the column from iterator:
`flecs::column<Position> p(it, 1); `

**To Reproduce**
Compile 34_persistent_query  and run. Seen with v2.2.0 and latest master f84db86

**Expected behavior**
Should give similar output as _"Iterate over entities matching the query using each"_.

**Additional context**
Seen with gcc 7.5.0 on Ubuntu and MinGW-w64 GNU 7.3.0 on Windows 10

**Comment by SanderMertens** [comment]
Thanks for reporting! Fixed the example.

**Comment by duddel** [comment]
> Thanks for reporting! Fixed the example.

Thanks for the fix! So I understand that iter() is preferred over constructing the columns from iterator manually (C++ API).

Is it safe to use a query with iter()/each() inside a "regular" system and even capture system-local variables/components in the query.iter([](){}) lambda function?

Thanks again!
