### ISSUE TITLE
entity with number name will cause writer crash

### ISSUE THREAD

**Issue by wicast** [SanderMertens/flecs#298]
**Describe the bug**
Name a entity with a number in range 1-15 will cause crash when load from file.

**To Reproduce**
```c++
#include <fstream>
#include <iostream>

#include "flecs.h"

#define BUFFER_SIZE (36)
#define FILENAME "savegame2.flecs"

struct Position {
  float x;
  float y;
};

struct Velocity {
  float x;
  float y;
};

struct CharComp {
  char a;
};

void save_to_file(flecs::world& ecs,
                  const char* filename) {
  flecs::reader reader(ecs);
  std::fstream file(filename, std::fstream::out | std::fstream::binary);

  char buffer[BUFFER_SIZE];
  std::int64_t read;

  // Read from world until there is no more data, write buffer(s) to file
  while ((read = reader.read(buffer, BUFFER_SIZE))) {
    file.write(buffer, read);
  }

  file.close();
}

void load_from_file(flecs::world& ecs, const char* filename) {
  flecs::writer writer(ecs);
  std::fstream file(filename, std::fstream::in | std::fstream::binary);

  char buffer[BUFFER_SIZE];
  std::int64_t read;

  // Read from file until there is no more data, write buffer(s) to world
  while ((read = file.read(buffer, BUFFER_SIZE).gcount())) {
    writer.write(buffer, read);
  }

  file.close();
}

int main(int argc, char* argv[]) {
  flecs::world ecs(argc, argv);

  auto posC = ecs.component<Position>();
  auto velC = ecs.component<Velocity>();
  auto ncC = ecs.component<CharComp>();


  ecs.entity("15").set<Velocity>({1,3});


  save_to_file(ecs,  FILENAME);

  auto another_ecs = flecs::world();

  load_from_file(another_ecs, FILENAME);

}

```
Run this code will get segment fault, is any restrict for naming?

**Additional context**
win10
flecs git commit:78558a33c270c527ddcf69e8af25288918fa5f74
msvc 14.28.29333 cxx17

**Comment by wicast** [comment]
![VirtualBox_Arch_12_01_2021_19_39_15](https://user-images.githubusercontent.com/2603937/104310061-124ef680-550e-11eb-98e7-85bd6df37125.png)
same error with linux

**Comment by SanderMertens** [comment]
Interesting. Names that are 100% a number are a special case, since this:

```c
world.lookup("100");
```

will return entity 100. I suspect that this has something to do with it, but will have to investigate. Entities 1-15 are builtin entities that are pretty important for the framework to function correctly, so if something gets overwritten there I could see how that could result in this error. In any case it shouldn't cause a crash.

Is it possible for you to prefix the name of the entity with a letter? I suspect that this work around the issue.

**Comment by wicast** [comment]
Yes, This issue is not blocking my project. I don't use pure number name normally, I just occasionally typed in a number name when playing with save/load feature.

**Comment by SanderMertens** [comment]
The reader/writer API has been removed from v3 which "solves" this problem!
