### ISSUE TITLE
ecs_iter_t::table_offset is never set

### ISSUE THREAD

**Issue by jfaust-fy** [SanderMertens/flecs#299]
**Describe the bug**
In the "systems and tables" section, the manual says:
```
Additionally, the `table_offset` member contains the current table being iterated over, so that a system can keep track of where it is in the iteration
```

However, `table_offset` is never set anywhere in the Flecs codebase. This means that it is impossible for a system to accumulate data across all elements of a query and then act on that data. A workaround is to split the system into two parts.

**To Reproduce**
Run a system that works across multiple tables. `table_offset` is always zero.

**Expected behavior**
`table_offset` should reflect the table being iterated.

**Additional context**
v2.2.0

**Comment by SanderMertens** [comment]
Nice catch! The member is no longer set because it was recently moved to an iterator-specific `index` member (`ecs_query_iter_t::index`). I removed it as it's redundant.
