### ISSUE TITLE
Serialization Issues

### ISSUE THREAD

**Issue by JonSnowbd** [SanderMertens/flecs#302]
[example.zip](https://github.com/SanderMertens/flecs/files/5844655/example.zip)

**Describe the bug**
Basic serialization isn't working, unclear cause. Deserialization results in `serialized data has invalid format`

**To Reproduce**
1. Download example.zip
2. `make` to produce the binary in ./bin
3. `./Dungeons.exe` to see the error output.

**Expected behavior**
Running on windows 10, built using Clang/LLVM, expected serialization to output file(works unsure if data is the issue though), issue lies in deserialization complaining about the data format despite it being exactly what output gives.

Also unsure if this is my own doing or a bug in flecs, but the only differences between this and the serialization demo is the use of global components, custom pipeline, and singleton components.

**Additional context**
Provided is an extremely stripped down version of my project that had the issue, almost all functions are gutted, but their definitions remain. Saving is done in `./src/editor.c : editor_Save` and loading is done in `./src/core.c : new_World`

new_World takes in a `char* path` which is expected to be optional, `NULL` as path will circumvent loading, providing one will force loading.

**Comment by hbiblia** [comment]
I updated a "flecs 2.3", I already tried it and it seems to work.

**Comment by JonSnowbd** [comment]
> I updated to version "flecs 2.3", I already tried it and it seems to work.

I updated to 2.3 and I still encounter the error. What operating system and C compiler are you using?

**Comment by hbiblia** [comment]
**Windows 10
Msys2 -> gcc-10.2.0**

**Comment by JonSnowbd** [comment]
Recompiled with GCC and I'm still getting invalid serialized data.

**Comment by hbiblia** [comment]
This is the example they have in flecs and it seems to work fine [example.zip](https://github.com/SanderMertens/flecs/files/5859228/example.zip)
![image](https://user-images.githubusercontent.com/1939353/105561268-a67a4400-5cec-11eb-965e-38fab3d6431e.png)

**Comment by JonSnowbd** [comment]
[example_singletons.zip](https://github.com/SanderMertens/flecs/files/5860034/example_singletons.zip)

Heres that example but with the features I mention as likely candidates. Converting components to global presented an issue in that they had to be defined twice, that took a bit to debug.

But the invalid data came when I introduced Singletons to the world with `ecs_singleton_set`.

The demo works great, but my issue occurs in a more complete project.

![image](https://user-images.githubusercontent.com/4250341/105575745-2aabe600-5d44-11eb-968f-e4479096f999.png)

**Comment by hbiblia** [comment]
![image](https://user-images.githubusercontent.com/1939353/105577007-3059f980-5d4d-11eb-941e-c83d733bd774.png)

Checking how to solve the problem, if you declare the components and call the singleton after creating the new world it seems to work. But I guess this doesn't help much.

![image](https://user-images.githubusercontent.com/1939353/105577010-3ea81580-5d4d-11eb-89e0-23b8c1ad8048.png)

**Comment by JonSnowbd** [comment]
> ![image](https://user-images.githubusercontent.com/1939353/105577007-3059f980-5d4d-11eb-941e-c83d733bd774.png)
> 
> It seems to work if ...
> 1 - Create the new world.
> 2 - Load the components and the singleton.
> 3 - Load the data from the file.
> 
> ![image](https://user-images.githubusercontent.com/1939353/105577010-3ea81580-5d4d-11eb-89e0-23b8c1ad8048.png)

Thank you very much! Instanciating my singletons on the world before loading makes it all work.
