### ISSUE TITLE
.hpp headers are not being installed with CMake

### ISSUE THREAD

**Issue by qimmer** [SanderMertens/flecs#305]
**Describe the bug**
Headers like flecs.hpp is not being installed on CMake install step. Only .h files are copied. Consider adding *.hpp to the globbing filter as well.

**To Reproduce**
Build and install using CMake. Notice the missing flecs.hpp header.

**Expected behavior**
C++ headers should be installed as well.

**Comment by rawbby** [comment]
This one should be closed as there was a fix ;-)

**Comment by SanderMertens** [comment]
Will close the issue, as the latest cmake changes should have solved this. Feel free to reopen the issue if you are still having issues!
