### ISSUE TITLE
Add threading API that works with application managed threads

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#334]
**Describe the problem you are trying to solve.**
Currently Flecs has a thread-safe staging design that allows multiple threads to asynchronously do mutations on the world. These mutations are stored in a thread specific "stage" (a command queue) which are flushed when threads synchronize.

This defer queue is available to the public API with the `defer_begin` and `defer_end` calls, though this only offers control over the defer queue in the "main" stage, and does not allow an application to control a stage per thread, such as what the internal threading feature provides.

To allow applications to manage their own threads while using the builtin defer queue features, this functionality must be made available through a public API.

NOTE: this feature will _not_ attempt to schedule systems, or prevent an application from running two systems that read/write the same components. When an application is managing its own threads, it should also take care of its own scheduling.

**Describe the solution you'd like**
The following example shows what the new API will look like:

```c
ecs_world_t *world = ecs_init();

// Create two stages. This allows two threads to concurrently mutate the world.
ecs_set_stages(world, 2);

// Get the stage objects. These are passed to the threads and should be provided to API calls instead of the world.
// The stage objects provide a transparent mechanism for passing a thread context to regular flecs API functions 
// without requiring a dedicated API for enqueuing commands.
ecs_world_t *stage_1 = ecs_get_stage(world, 0);
ecs_world_t *stage_2 = ecs_get_stage(world, 1);

// Start some threads (not a Flecs API function)
thread_new(thread_func, stage_1);
thread_new(thread_func, stage_2);

// Main loop. Instead of ecs_progress, use these functions to control when a frame starts/stops, and when merging 
// should occur.

while (true) {

// Start frame. This does time measurements, and if an application has set a target FPS, this function will sleep for
// as long as necessary to ensure the application does not exceed the set FPS
ecs_frame_begin(world);

// Start staging. After this call it is safe for threads to start adding commands to the queue. This also flags the moment 
// at which it is no longer valid to do mutations on the regular world object. When an application would attempt to, for
// example, do "ecs_add(world, e, Position)" after staging_begin, an assert would be thrown. It is still safe to call
// functions that do not mutate the world, such as "ecs_has".
ecs_staging_begin(world);

// Signal threads that it's okay to start enqueueing commands (not a Flecs API function)
signal_threads();

// Wait for threads to finish (not a Flecs API function)
wait_for_threads();

// End staging. This will automatically merge data from all threads. Applications will be able to disable automatic
// merging, and even take control over which stages are merged and which stages aren't. It is valid to begin/end
// staging multiple times per frame. This is commonly required when an application has multiple sync points.
ecs_staging_end(world);

// Finish frame. This executes post-frame actions and a few other administrative things. 
ecs_frame_end(world);
}
```

This is what a thread implementation could look like:
```c
void* thread_func(void *arg) {

  // This is actually the stage that has been passed to the thread. Use it as the world when invoking the API
  ecs_world_t *world = arg;

  // Main loop
  while (true) {

  // Wait until main thread signals threads that it's ok to start processing (not a Flecs function)
  wait_for_frame();

  // Do some stuff. These operations are not directly executed on the world, but are enqueued
  ecs_entity_t e = ecs_new(world, Position);
  ecs_add(world, e, Velocity);

  // Signal to main thread that we're done for this frame (not a Flecs function)
  signal_main();
}
```

**Comment by ikrima** [comment]
Looks pretty good; based on flecs.h/flecs.hpp + example, my "95% LOD" feedback is mostly nitpicks/documentation tidbits that may already be planned to be covered
- Liked/Helpful
    - high-level pseudo code of problem solution
    - delineating between flecs vs. non-flecs api calls. Ex: 
    ```cpp
    // Start some threads (not a Flecs API function)
    thread_new(thread_func, stage_1);
    ```
    - comments on what happen during flecs calls. Ex: 
    ```cpp
    // End staging. This will automatically merge data from all threads.
    ```
    - Calling out what data-hazards are ie  what can/can't be done that may be non
    ```cpp
    // End staging. This will automatically merge data from all threads. Applications will be able to disable automatic
    // merging, and even take control over which stages are merged and which stages aren't. It is valid to begin/end
    // staging multiple times per frame. This is commonly required when an application has multiple sync points.
    ecs_staging_end(world);
    ```
- Nice to have/nitpicks
    - Code sample showing pipeline implementation with new api
    - Ordering of stage merging at `ecs_staging_end`?
    - (might be covered elsewhere) call out how do onAdd/onSet/etc systems & component ctor/dtor/etc fit into this
    - Expand on what will happen in common error conditions (ie "undefined/silent error", flecs assert, etc)
        - E.g. from comments on mutation on world object post-`ecs_staging_begin(world)` 
        ```cpp
        // When an application would attempt to, for
        // example, do "ecs_add(world, e, Position)" after staging_begin, an assert would be thrown
        ```
    - Possibly use deprecated macro? (ie  ``[[deprecated]]/declspec(deprecated)/#pragma deprecated(func1, func2)``)

**Comment by SanderMertens** [comment]
@ikrima 
> Code sample showing pipeline implementation with new api
I've made a few improvements that now allow you to use `ecs_pipeline_run`, but only in single threaded applications. The reason for this is that mid-execution a pipeline may need to sync & merge, and this would require exposing more of the internal worker thread implementation. I don't think that part of the code is stable enough yet to make public, as there are a few big shortcomings in the current builtin flecs-managed threading implementation.

In a single threaded application you can use the functions like this:
```c
// optional, this function just measures time and, when enabled, limits FPS
float delta_time = ecs_frame_begin(world, 0);

ecs_pipeline_run(world, pipeline_id, delta_time);

ecs_frame_end(world);
```

> Ordering of stage merging at ecs_staging_end?
I added this example: https://github.com/SanderMertens/flecs/blob/staging_api/examples/cpp/56_custom_merge/src/main.cpp

> Expand on what will happen in common error conditions (ie "undefined/silent error", flecs assert, etc)
Added more comments to the examples, and added diagram to documentation

> Possibly use deprecated macro? (ie [[deprecated]]/declspec(deprecated)/#pragma deprecated(func1, func2))
Created issue #339 for this & implemented it

**Comment by ikrima** [comment]
awesome; the referenced commits/diagrams + stage merging example are spot on

**Comment by SanderMertens** [comment]
This feature deprecated the `ecs_get_thread_index` function (use `ecs_get_stage_id`).
