### ISSUE TITLE
Allow for component disabling for prefabs

### ISSUE THREAD

**Issue by jtferson** [SanderMertens/flecs#346]
**Describe the problem you are trying to solve.**
Currently it's possible to disable components for regular entities. It might be useful to expand that functionality to define which components of the prefab instances will be disabled by default. 

**Describe the solution you'd like**
Instances inherit the disabling status of components from the prefab:
```cpp
// Velocity will be disabled for every instance by default
auto prefab = ecs.prefab()
	.add<Movable>()
	.add_owned<Velocity>()
	.disable<Velocity>();

// Here an instance is getting the Velocity component as disabled
auto instance = ecs.entity().add_instanceof(prefab);

// Example: a system matches only entities with enabled Velocity
ecs.system<>().signature("Velocity, Movable").iter([](flecs::iter& it)
{
       test_int(it.count(), 0);
});
```

**Comment by SanderMertens** [comment]
Fixed in v4
