### ISSUE TITLE
Deleting an entity involved in a pair causes flecs to leave the related entity broken

### ISSUE THREAD

**Issue by shanehyde** [SanderMertens/flecs#362]
**Describe the bug**
Deleting an entity involved in a pair causes flecs to leave the related entity broken

**To Reproduce**
This is adapted from the manual - 
```c++    
    auto world = flecs::world();
    auto HasSibling = flecs::entity(world);

    auto Jane = flecs::entity(world, "Jane");
    auto Jeff = flecs::entity(world, "Jeff");

    Jane.add(HasSibling, Jeff);
    Jeff.add(HasSibling, Jane);

    Jane.each(HasSibling.id(), [](flecs::entity e)
    {
        printf("Jane has a sibling named %s\n", e.name().c_str());
    });

    Jeff.destruct();

    Jane.each(HasSibling.id(), [](flecs::entity e)
    {
        printf("Jane has a sibling named %s\n", e.name().c_str());
    });
```
**Expected behavior**
This should print `Jane has a sibling named Jeff` once.  Instead it prints it once and asserts on the second print
`err : assert(ecs_is_valid(world, entity)) ..\..\..\extern\flecs\src\entity.c:2074: invalid parameters`

Also once Jeff has been deleted, it is also impossible to remove the HasSibling from Jane as the pair id is invalid and asserts if you try to.

**Comment by SanderMertens** [comment]
Ah yes, this is a known issue. It is not valid to store relationships that are no longer alive, but there are currently no builtin mechanisms to prevent this.

A feature will be developed to address this, which will let you specify for a relationship (`HasSibling`) what the behavior should be when its object (`Jeff`) is deleted. Currently I am planning to allow for two behaviors, which is to either delete the relationship (`HasSibling, Jeff`) or the entity (`Jane`).

The first one would make most sense in this case, the second one would make sense for a relationship like `ChildOf`, where you want to delete child entities if the parent is deleted.
