### ISSUE TITLE
Iterating over entities with disabled components

### ISSUE THREAD

**Issue by jtferson** [SanderMertens/flecs#364]
**Describe the problem you are trying to solve.**
Currently entities with disabled components are prevented from being matched. It might be useful in some scenarios to iterate over entities with such components. 

**Describe the solution you'd like**
The query signature can accept DISABLED modifier (or something like this) and allow to match with entities that have disabled components:
```cpp
auto entity = ecs.entity()
    .add<Movable>()
    .add<Velocity>();
entity.disable<Velocity>();

ecs.system<>().signature("DISABLED | Velocity, Movable").iter([](flecs::iter& it)
{
    for(auto i : it)
    {
        //here could be some conditional logic, for example
        if(canEnable)
        {
            it.entity(i).enable<Velocity>();
        }
    } 
});
```

**Comment by SanderMertens** [comment]
This is possible in v4:

```cpp
    ecs.query_builder()
        .expr("toggle | Velocity")
        .each([](flecs::entity e) {
          // ..
        });
```
