### ISSUE TITLE
Remove `bake.utils` dependency

### ISSUE THREAD

**Issue by ArnCarveris** [SanderMertens/flecs#37]
* Substitute all `ut_*` function with `ecs_os_api_*` callbacks.
* Move [bake.utils](https://github.com/SanderMertens/flecs/blob/master/src/os_api.c#L21) to separate `flecs.bake` module. It will setup os api within module import function. 
* Remove `bake.utils` dependency from all modules use os api instead.

**Comment by SanderMertens** [comment]
I did not solve the issue as suggested, as this would require additional steps in the application code that would make it bake specific. Instead, I added additional os_api functions that provide library loading, so that now all bake-specific code is localized to os_api.c
