### ISSUE TITLE
Allowing for using named entity modifiers together with switchable tags 

### ISSUE THREAD

**Issue by jtferson** [SanderMertens/flecs#376]
**Describe the problem you are trying to solve.**
Currently we can match against regular entities with switchable tags but narrowing that down to just singleton or specific entities is not possible. It might be useful to have such matching logic in order to have global state machines.

**Describe the solution you'd like**
The query signature that contains switchable tags with named modifiers properly matches: 
```cpp
auto Slow = ecs.entity("Slow");
auto Normal = ecs.entity("Normal");
auto Fast = ecs.entity("Fast");
auto GlobalSpeed = ecs.type("GlobalSpeed", "Slow, Normal, Fast");
	
ecs.entity("GameArena")
    .add_switch(GlobalSpeed)
    .add_case(Slow);

ecs.query<>("Position, Velocity, GameArena:CASE | Slow").iter([&](flecs::iter& It)
{
});

```

**Comment by SanderMertens** [comment]
This is now possible in v4:

```cpp
ecs.component<GlobalSpeed>().add(flecs::Union);

ecs.query_builder()
    .expr("Position, Velocity, GlobalSpeed(GameArena, Slow)")
    .each([](flecs::entity e) {
        // ...
    });
```
