### ISSUE TITLE
Executing Reactive systems in order

### ISSUE THREAD

**Issue by RomanZhu** [SanderMertens/flecs#38]
Hi

From what I read, reactive behaviors (OnAdded, On*...) are executed during ecs_* methods.
But can there be behavior for executing those events at a specified order?

Here is how my systems structured while I work with Entitas:
- Input feature
- - CollectMouseKeyboardStateSystem (adds/removes empty component `LeftMouseDown` etc)
- - CollectTouchStateSystem
- - ...
- ...
- Shooting feature
- - SpawnBulletOnLeftMouseDownAddedSystem( reacts on `LeftMouseDown` added, creates new entity-bullet)
- - ...
- ...
- ...
- Collision feature
 - - DetectBulletCollisionSystem (fires raycast to see if we will hit something, if we will, then add `Collided` on bullet)
 - - ...
 - - DestroyBulletOnCollidedAddedSystem (reacts on `Collided` being added, **adds `Destroyed` component**)
- ...
- ...
- ...
- Visual feature
- - SpawnAssetSystem (reacts on added `Asset` component, spawns visual representation, links them somehow)
- - DestroyVisualAssetSystem (**reacts on added `Destroyed`** component OR removed `Asset` component, removes visual representation)

- RemoveDestroyedEntitiesSystem (**reacts on added `Destroyed`**, **removes entity**)

There can be a lot of different logic between marking an entity as `Destroyed` and actually removing such entity. For example, some system could remove `Destroyed` component before the entity would be removed.
Those systems are executed at that specified order.

Can there be a feature to delay the execution of reactive systems?

**Comment by SanderMertens** [comment]
@RomanZhu flecs does not (yet) have reactive systems that work the same as Entitas. To implement something like what you describe with Flecs, you would use system _phases_. Flecs has a number of predefined phases which are executed in sequence each frame, to which systems/features can be assigned.

Your example in Flecs would look something like this:

`EcsPreUpdate` => Feature Input [CollectMouseKeyboardState, CollectTouchState, ...]
`EcsOnUpdate` => Feature Shooting [SpawnBulletOnLeftMouseDown, ...]
`EcsOnValidate` => Feature Collision [DetectBulletCollision, DestroyBulletOnCollided]
`EcsPostUpdate` => Feature Visual [SpawAsset, DestroyAsset]
`EcsPreStore` => Feature [RemoveDestroyedEntities]

Components added in one phase are available to systems in the next phase, so you can delay destruction simply by adding a `Destroyed` component in `DestroyBulletOnCollided`, and then actually deleting the entity in the `RemoveDestroyedEntities`, which requires `Destroyed`.

More info on phases: https://github.com/SandeårMertens/flecs/blob/master/Manual.md#system-phases

**Comment by RomanZhu** [comment]
It would work if I won't have hundreds of those features
I will think about how to restructure the code to work with instant events
Thanks

**Comment by SanderMertens** [comment]
@RomanZhu sounds good! If you want to discuss further, join the gitter: https://gitter.im/flecsdev/community
