### ISSUE TITLE
Component registration not working correctly with more than one world

### ISSUE THREAD

**Issue by Jarodwr** [SanderMertens/flecs#381]
**Describe the bug**
When you create a second world and import the same module as another world, systems won't be able to find the correct associated entity for the required components and will fail.

**To Reproduce**
Example project that reproduces the issue: https://github.com/Jarodwr/flecs-multiworlds-issue-example

**Comment by SanderMertens** [comment]
Fixed a bug & added a test for it. Closing the issue, feel free to reopen if you're still having issues!
