### ISSUE TITLE
README, Quickstart, and Manual still use old ecs_column API

### ISSUE THREAD

**Issue by cshenton** [SanderMertens/flecs#385]
As the title says, there's a bit of conflict between the documentation and the code in the `examples` folder which is currently making it a bit confusing to pick up the library.

**Comment by SanderMertens** [comment]
Yup good point! As you've noticed the API is a bit in flux at the moment, and the documentation & examples are lagging behind. There are still a few APIs to update, once that's done I'll update the docs.

**Comment by SanderMertens** [comment]
Fixed!
