### ISSUE TITLE
Allow flecs::system to be default constructible

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#386]
**Describe the problem you are trying to solve.**
To use `flecs::system` as a field of a component we have to fallback to C api or upcast system to the `flecs::entity`. Calling such a system is always through a C api. 

**Describe the solution you'd like**
`flecs::system` being default constructible (doing nothing / asserting when called if not having the world pointer).

**Comment by SanderMertens** [comment]
Yup good point. Note that it is currently possible to create a system from a flecs entity, so you don't have to necessarily go all the way down to the C API:

```c
// Create system
auto sys = world.system<Pos,Vel>();
// Upcast to entity
flecs::entity sys_e = sys;
// Create system from entity
auto sys_var = world.system(sys_e);
// Run system
sys_var.run();
```
