### ISSUE TITLE
Add an option for non-deferred mutating task system

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#388]
**Describe the problem you are trying to solve.**
I have a task system (that is actually the very first system being declared) that polls application input and writes some input data into arbitrary component in the scene (player controller or some UI container). The data it writes must be accessible in the same frame (so that no input latency is added due to deferment).

To achieve this, with the current tools of flecs, I have to write `[out] :CInput` annotation for the input writing system, and `[in] :CInput` annotation for the reading system. The problem is, those two systems are spread apart, between them are some logical systems. And for those logical systems I am perfectly fine with the deferment, and it is expensive to merge their deferred actions together with the input. _**I only want to merge the input component writes (coming from the task system), and defer the rest (coming from other systems).**_

To achieve that, I have to create a secondary artificial system right after the input writing one, that contains just the `[in] :CInput` annotation. This feels hacky and is not generically applicable (what if I had logical systems before my input writing systems, but would not want to merge them?).

**Describe the solution you'd like**
I propose some special annotation or system configuration parameter that specifically states: all operations of this task system are NOT to be deferred. 

So there are two ways that I see how this could be implemented:
1. Just automatically insert sync point after such a system. Easy, guaranteed not to break anything, but does not solve some of the issues (some stuff could already be deferred before this system that we do not want to merge).
2. Do not make the world read-only for the scope of this task system, provide the real world in the flecs::iter for this task system. We also have to insert non-merging sync-point (preventing other threads from running while task system executes) in the pipeline, so that no data race occurs due to the actions of non-deferred task system (like other thread immediately trying to read the input that is being written by that task system). This is related to the ability to make systems bound to a single thread fyi @SanderMertens .

Current workaround: manual sync-point insertion through dummy system, as to minimize the amount of data being merged.

**Comment by Hexlord** [comment]
Another workaround (feels better than sync-point enforcement): make system manual, and call it from the main thread (as it is the first one to be executed anyway), thus have no deferment.

**Comment by SanderMertens** [comment]
Implemented! (the `no_staging` option).
