### ISSUE TITLE
Allow for destruction of child entities together with the parent

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#390]
**Describe the problem you are trying to solve.**
When `destruct()`-ing scene root, OnRemove is not called for child entity components of that scene root, resulting in unfreed resources (even though those components are no longer matched). This implicit behaviour is never the one I intend, and we have no alternative explicit behaviours built-in.

**Describe the solution you'd like**
I use this custom function to achieve child-tree destruction, and I propose something similar to be added to flecs, preferably as a default replacement for `.destruct()`:
```c
inline void Destruct(entity Entity) {
    for(auto Child : Entity.children()) {
        for(auto Index : Child) {
            Destruct(Child.entity(Index));
        }
    }
    Entity.destruct();
}
```

**Comment by SanderMertens** [comment]
I'll look into this. If OnRemove/dtors aren't called for child entities when the parent is removed, that is a bug.

**Comment by Hexlord** [comment]
> I'll look into this. If OnRemove/dtors aren't called for child entities when the parent is removed, that is a bug.

Okay, please let me know if you are unable to reproduce, I would then try to extract the minimum reproducible example from my code base. 

Basically I spawn both the root and child entities in a task system (**so they are deferred**), and their components are not getting `OnRemove`-d when I `.destruct()` (also deferred) the root entity in multi-threaded setup. It might work in single-threaded or without the deferment, sorry have not tested that!

**Comment by SanderMertens** [comment]
Rerprodu
