### ISSUE TITLE
Module namespace doesn't receive Module tag upon registration

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#397]
**Describe the bug**
When a module is registered, a `Module` tag is added so that applications can easily find (or filter out) the imported modules. However, when a module is inside a namespace, registration will create an entity for both the namespace and the module. This namespace does not receive the module tag.

**To Reproduce**
```cpp
namespace ns {
class my_module {
  my_module(world& w) {
    // creates `ns::my_module` with tag `Module`
    // creates `ns` without tag `MyModule`, not good!
    w.module<my_module>();
  }
};
}

**Expected behavior**
Each entity created by registering a module should get the module tag.

**Comment by Hexlord** [comment]
Still crashing 
```c
err : abort /home/sasha/SpaceEngine/ThirdParty/flecs/src/entity.c:2127: invalid delete of entity/pair (SE.MGeometryFluctuationSystems)
```
