### ISSUE TITLE
C++ component move lifecycle action doesn't destruct source component

### ISSUE THREAD

**Issue by HenryFalconerIO** [SanderMertens/flecs#399]
As far as I can tell from the code that uses it, the `move` action is expected to move the source component into the destination, where the destination has already had the constructor run on it, and then destruct the source component.

In other words, after running `move`, the source component should be in a destructed state such that it would have to have the constructor run on it before it could have a different component `move`d into it.

Flecs's C++ implementation of the `move` action, `component_move`, simply uses `std::move` on the source to move it to the destination. However, this doesn't leave the source in a destructed state. This should be fine for most types, e.g. `std::vector`, where a vector that has been moved from will have no dynamic allocations and can safely be discarded without leaking memory, but this behaviour could cause problems for types that need to be destructed properly even after being "moved" out of.

Unless I've missed something, you should be able to fix this by changing `component_move` to invoke the destructor on the source component after moving it.

**Comment by SanderMertens** [comment]
Actually this is not entirely correct. The move semantics of the flecs core are the same as those of C++, which means that while the move ensures that the source no longer holds any resources, the source is still left in a constructed/valid state, which means that in theory it could be used again.

This is the same as in C++, where this is valid:
```c
std::string a = "foo";
std::string b = std::move(a);
a = "bar";
```

**Comment by HenryFalconerIO** [comment]
Yeah, sorry I should have posted the snippet from Flecs that made me think a destruct would be needed.

For what it's worth, I've changed my design now to no longer use `move`, as I'm assuming all component types I'm using will be relocatable in memory using memcpy, so this isn't immediately impacting me (I'm using the C API from C++ for more control). The codepaths in Flecs when `move` is not implemented do appear to destruct the component correctly.

**Comment by Hexlord** [comment]
> Calling an additional dtor would come at a cost though, will have to think a bit about this.

You could wrap both the move and the destructor into a single static function pointer (this is the stuff that std::function does for its implementation), move func would inline into it and there would be no extra perf for supporting the destructor.

**Comment by SanderMertens** [comment]
@Hexlord that is possible, and is something that is also needed for copy ctors and move ctors (right now the core only supports the equivalent of a copy/move assignment).

Where a tradeoff comes in is in what to do with these callbacks. Say you'd have:
- ctor
- dtor
- copy
- move
- copy_ctor
- move_ctor
- move_dtor

Either you require the application to set all of them (in C++ this is implicit but in C it's not) or you add additional branching at the storage level. I'm leaning towards the latter.

**Comment by Hexlord** [comment]
> Either you require the application to set all of them (in C++ this is implicit but in C it's not) or you add additional branching at the storage level. I'm leaning towards the latter.

Agreed, branching is probably the way.
