### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by jesta88** [SanderMertens/flecs#4]
I know CMake has problems, but it is kind of a standard now. Bake is the only thing that keeps me from using reflecs right now, because I don't want to install/learn yet another build tool, even if it is theoretically superior.

Providing CMakeLists.txt would help adoption IMO.

**Comment by SanderMertens** [comment]
You're not the first person to point this out, and you're likely correct that not supporting CMake hurts adoption of reflecs. I would like to add support for it at some point, but there are a few things to consider:

1. Currently bake uses pthreads for threading, which is not portable to Windows. Bake has an OS abstraction library (`bake.util`) which provides threading, and a host of other useful APIs that reflecs (modules) may use in the future.

2. Bake is a _build system_, not a build tool. [Reflecs modules](https://github.com/SanderMertens/reflecs#modules) rely heavily on its features, like management of dependencies/header files/miscellaneous files (HTML, JS etc).

If you want to use reflecs as a standalone library, a simple CMakeList.txt could do the trick- though threading has to be addressed if reflecs is used on Windows. To actually leverage reflecs modules, more work is required.

**Comment by SanderMertens** [comment]
One more thing which may help: you can just use bake to build the reflecs binary(s). Bake produces a directory (`~/bake`) which contains all the binaries and include files you'd need. Once you have those, you could use whichever build tool you prefer.

**Comment by SanderMertens** [comment]
I added a simple CMakeList.txt to the repository. I just validated that it builds and that the binary contains the symbols, but haven't done much testing beyond that. If you want to give it a go, make sure to check out the `aos_to_soa` branch, as that is the latest state (about to be merged back into the main branch).
