### ISSUE TITLE
Implement `ecs_type_parse` as public API

### ISSUE THREAD

**Issue by ArnCarveris** [SanderMertens/flecs#40]
Default type construction by signature:
```c
int ecs_type_parse(ecs_world_t *world,  ecs_type_t* type, const char *sig);
```

User defined type construction by something:
```c
int ecs_type_parse_{smth}(ecs_world_t *world,  ecs_type_t* type, {smth});
```

Function modifies given `type` pointer and returns non-zero error code.

**Comment by SanderMertens** [comment]
Suggested to use the following signatures:

```c
ecs_type_t ecs_type_parse(ecs_world_t *world, const char *expression);
ecs_signature_t ecs_signature_parse(ecs_world_t *world, const char *signature);
```

The `ecs_signature_t` type would be a new data structure that contains a parsed representation of a system signature. The `ecs_new_system` function could be changed to:

```c
ecs_entity_t ecs_new_system(
    ecs_world_t *world, 
    const char *id, ecs_system_kind_t kind, 
    ecs_signature_t *sig, 
    ecs_system_action_t action);
```
