### ISSUE TITLE
FTBFS using meson

### ISSUE THREAD

**Issue by jon-turney** [SanderMertens/flecs#401]
**Describe the bug**

Fails to build from source using meson:

```
    meson.build:13:0: ERROR: File src/signature.c does not exist.
```

This file seems be moved in commit 54ec23e8b124b60c78008f1ee2ee2f941c5ca7ff, but meson.build isn't changed appropriately.

**Comment by SanderMertens** [comment]
Thanks for reporting! Fixed the meson buildfile & added a meson build to CI
