### ISSUE TITLE
Allow for non-prefixed use of module components

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#404]
**Describe the problem you are trying to solve.**
When writing flecs modules, it would be handy to be able to use all their components without the namespace (I know I have no collisions, as all my modules are internal).

**Describe the solution you'd like**
This to work (idea of @SanderMertens):
```c
world.import<SE.MGeometryFluctuationSystems>().use(world.filter<Component>());
```

**Comment by Hexlord** [comment]
Current workaround is to use this function to register components inside internal modules:
```c++
template<typename T>
void Use(ecs &ECS) {
    ecs_entity_t prev = ecs_set_scope(ECS.c_ptr(), 0);
    ECS.use<T>();
    ecs_set_scope(ECS.c_ptr(), prev);
}
```

**Comment by SanderMertens** [comment]
This can now be addressed with the `ecs_set_lookup_path` function.
