### ISSUE TITLE
Make all world retrieval function return non-const ref

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#406]
**Describe the problem you are trying to solve.**
When passing world around (through functions), we often need to use non-const ref because some function (`get_mut`) require mutability, and passing by value is hard because copy constructor is deleted. But some ways of world retrieval (`iter::world(), entity::world()`) return by value, which does not allow for easy ways to pass world around as non-const ref (have to capture into local variable).

**Describe the solution you'd like**
Make `iter::world()` and `entity::world()` return `world &`

**Comment by SanderMertens** [comment]
I looked into doing this a couple times, but the change spreads like an inkblot across the API. The biggest challenge is that `flecs::entity` stores a `flecs::world_t*`, not a `flecs::world`, and so when an iterator is created by an entity it can't give you a ref to the world (like when using `children`) as it would go out of scope after the statement.

In a few months I expect to fix a few inconsistencies between how lifecycles of different objects are managed, I'll take a look at the world then and see how it fits in the larger picture.

Closing this for now as there's no clear path forward for implementing this.
