### ISSUE TITLE
Problems with flecs hierarchy in OnRemove monitors

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#408]
**Describe the bug**
E4 does not get deleted, hierarchy in OnRemove monitor is messed up.
And it is NOT just the names being messed up, the acutal data from E4 in my code is not getting destroyed breaking some guarantees.
```c
ecs ECS;
    ECS.set_threads(1);

    if (true) {
        struct CComp {
            float Value;
        };
    
        ECS.use<CComp>();
    
        ECS.system<>("CComp OnRemove", "[in] CComp").kind(flecs::OnRemove).iter([](iter &Iter) {
          for (auto Index : Iter) {
              entity Entity = Iter.entity(Index);
              entity_view Parent = Entity.get_parent(0);
              Debugf("%s (%s)", Entity.name().c_str(), Parent.name().c_str());
          }
        });
        auto Root = ECS.entity("Root");
        auto E1 = ECS.entity("E1").add(flecs::ChildOf, Root).set<CComp>({1.0f});
        auto E2 = ECS.entity("E2").add(flecs::ChildOf, E1).set<CComp>({1.0f});
        ECS.entity("E3").add(flecs::ChildOf, E2).set<CComp>({1.0f});
    
        auto E4 = ECS.entity("E4").add(flecs::ChildOf, Root).set<CComp>({1.0f});
        auto E5 = ECS.entity("E5").add(flecs::ChildOf, E4).set<CComp>({1.0f});
        ECS.entity("E6").add(flecs::ChildOf, E5).set<CComp>({1.0f});
    
       Root.destruct(); // This results in same printed output as query below.
        
    }
```

**Expected behavior**
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E3 (E2)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E2 (E1)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E6 (E5)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E5 (E4)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E1 (Root)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E4 (Root)

**Actual behavior**
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E3 (E2)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E2 (E1)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E6 (E5)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E5 (E1)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E1 (Root)
/home/sasha/SpaceEngine/Source/Core/Engine/Engine.cpp:249 E1 (Root)

**Workaround**
For me, luckily, there is one: do not destroy world on application exit (I do not have dynamic scenes with layout hierarchy just yet)

**Comment by SanderMertens** [comment]
@Hexlord Got it reproduced. The issue seems to be isolated to using `get<>` inside the `OnRemove` callback. Reading from the component array directly doesn't have the issue. If you only need to access the component value of the removed component this might be an easier workaround:

```c
ECS.system<Comp>("CComp OnRemove")
    .kind(flecs::OnRemove)
    .iter([](iter &Iter, Comp *comp) {
        for (auto Index : Iter) {
            Debugf("%s (%s)", comp[i].Value);
        }
    });
```

I suspect the issue is caused by the entity index getting out of sync just before the entity is deleted. Looking into a fix.

**Comment by SanderMertens** [comment]
Turned out to be an off-by-one error :)

**Comment by Hexlord** [comment]
Fix confirmed, thank you!
