### ISSUE TITLE
Module destructor being called strange amount of times or not being called at all

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#409]
**Describe the bug**
Module destructor is called using strange logic, when we expect it to be always called just once on world destruction.

This code never prints the string
```c
    ecs *ECSPtr = new ecs;
    ecs &ECS = *ECSPtr;

    if (true) {
        class MModule {
        public:
            MModule(ecs &ECS) {
                (void)ECS;
            }
            ~MModule() {
                Debugf("Destructing...");
            }
        };
    
        ECS.module<MModule>();
        
        delete ECSPtr;
    }
```

This code prints the string 3 times (3x destructor calls)
```c
    ecs *ECSPtr = new ecs;
    ecs &ECS = *ECSPtr;

    if (true) {
        class MModule {
        public:
            MModule(ecs &ECS) {
                (void)ECS;
            }
            ~MModule() {
                Debugf("Destructing...");
            }
        };
    
        ECS.module<MModule>();
        
        ECS.entity();
        ECS.entity();
        ECS.entity();
        
        delete ECSPtr;
    }
```

**Expected behavior**
"Destructing..." should be printed once in both cases

**Comment by SanderMertens** [comment]
The code is not expected to work, as it does not register the module in the constructor, and do not import the module with the world. After correcting the examples, they work as expected (one dtor @ work exit). Make sure to use modules like this:

```cpp
class MModule {
public:
    MModule(flecs::world &ECS) {
        ECS.module<MModule>();
    }
    ~MModule() {
        printf("Destructing...\n");
    }
};

ECS.import<MModule>();
```

One additional note:
> we expect it to be always called just once on world destruction.

Modules are stored just as regular (singleton) components, which means that they follow the same rules when it comes to when to invoke a dtor. That means that it is possible to get multiple dtors (after fixing issue #399) if you happen to add/remove components to a module entity.

**Comment by Hexlord** [comment]
Sorry, actual reproduce is following:
```c
namespace Test {

static std::vecotr<system> Systems;

class MModule {
public:
    MModule(ecs &ECS) {
        ECS.module<MModule>();
        Systems.Add(ECS.system<>("Just a system", "").kind(0).iter([](iter &){}));
    }
    ~MModule() {
        Debugf("Destructing...");
    }
    
    
};
}

int main(){
    stdcpp_set_os_api();
    ecs *ECSPtr = new ecs;
    ecs &ECS = *ECSPtr;
    ECS.set_threads(8);
    
    if (true) {
        ECS.import<Test::MModule>();
        delete ECSPtr;
    }
}
```
