### ISSUE TITLE
Make query iteration automatically introduce deferment

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#410]
**Describe the problem you are trying to solve.**
When iterating a query and simultaneously mutating some of the components, a silent state corruption happens(see https://github.com/SanderMertens/flecs/issues/400).

**Describe the solution you'd like**
To prevent this from happening (as it is easy to forget to defer manually in such cases), @SanderMertens thought of a way to fix this:
Make query iteration automatically introduce deferment context (if there ain't one already).

**Comment by SanderMertens** [comment]
Agreed. While there are scenarios where you can safely do operations without deferring, those specific scenarios are difficult to spot in complex applications and is even harder to correctly enforce. Auto-deferring is the safest option that has almost no overhead when nothing got deferred.

The core (C99) API does not automatically defer (it cannot), so there will still be the option to iterate queries without deferring.

**Comment by Hexlord** [comment]
Confirmed working! Thanks!
