### ISSUE TITLE
Allow to check whether optional tag component term is set for an iter invocation

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#413]
**Describe the problem you are trying to solve.**
Under https://github.com/SanderMertens/flecs/issues/402 a new way to check for tag components matching the query was introduced, but it does not handle `Optional` oper correctly (or rather currently it does not allow for the desired check to be performed when having such and oper).

Following code prints "Match" even for entities without the tag.
```c
struct Tag { };

flecs::world World;

auto q = World.query_builder<>()
  .term<const Tag>().oper(flecs::Optional)
  .build();

q.iter([](flecs::iter& it) {
  bool HasTag = Iter.term_id(1) == Iter.world().id<Tag >();

  for (auto Index : Iter) {
    if (HasTag) {
     printf("Match");
    }

  }
}
```

**Describe the solution you'd like**
Some way to also support optional tags without resorting to `Iter.entity(Index).has<Tag>()`

**Comment by SanderMertens** [comment]
Fixed!
