### ISSUE TITLE
Implement read-only component data access in systems

### ISSUE THREAD

**Issue by ArnCarveris** [SanderMertens/flecs#42]
Currently we have read-write(mutable) access to component data via `ECS_COLUMN`, to make all systems work together we split it into phases but if systems count increases we run out of phases, and get loose control of running order within phase, by knowing systems RO/RW component access we can build better scheduling(producer-consumer data-flow graph?). 
As bonus we disallow users to change immutable data.

In system definition.
at: https://github.com/SanderMertens/ecs_graphics/blob/master/src/main.c#L31
we defined read-only `EcsInput` component data access:

```c
ECS_SYSTEM(world, MoveSquare, EcsOnUpdate, Immutable.EcsInput, Square.EcsPosition2D);
```

In system function.
at: https://github.com/SanderMertens/ecs_graphics/blob/master/src/main.c#L5
we implement read-only `EcsInput` component data access:

```c
void MoveSquare(ecs_rows_t *rows) {
    const EcsInput *input = ecs_column_ro(rows, EcsInput, 1); 
    //or, ECS_COLUMN_IMMUTABLE(rows, EcsInput, input, 1);
    
    EcsPosition2D *position = ecs_shared_rw(rows, EcsPosition2D, 2); 
    //or, ECS_SHARED(rows, EcsPosition2D, position, 2);


    int x_v = input->keys[ECS_KEY_D].state || input->keys[ECS_KEY_RIGHT].state;
        x_v -= input->keys[ECS_KEY_A].state || input->keys[ECS_KEY_LEFT].state;
    int y_v = input->keys[ECS_KEY_S].state || input->keys[ECS_KEY_DOWN].state;
        y_v -= input->keys[ECS_KEY_W].state || input->keys[ECS_KEY_UP].state;

    position->x += x_v * MOVE_SPEED;
    position->y += y_v * MOVE_SPEED;
}
```

**Comment by SanderMertens** [comment]
This sounds good. There are a few things I can think of that flecs could do with this information:
- Detect access to uninitialized components
- Use it for pub/sub systems, where a pub system only publishes when there is a sub system

**Comment by SanderMertens** [comment]
This issue can be closed. The `[in]` component modifier is used by the API to enforce read only access.
