### ISSUE TITLE
Make ecs_enable deferrable so it can be called from stages

### ISSUE THREAD

**Issue by tedajax** [SanderMertens/flecs#427]
**Describe the problem you are trying to solve.**
Currently attempting to call ecs_enable from a stage will result in an assert on world->magic == ECS_WORLD_MAGIC

**Describe the solution you'd like**
It would be nice if ecs_enable could be deferred like ecs_enable_component

**Comment by SanderMertens** [comment]
Fixed it, that was an easy one :) Just had to remove the check
