### ISSUE TITLE
Make entity and entity_view bool conversion more useful

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#428]
**Describe the problem you are trying to solve.**
Currently expressions like `if (entity_view()) {}` lead to the use of `flecs::id`'s operator `operator flecs::id_t() const`, and the conversion of that integer into a bool for the condition of the branch, which basically means `if( entity_view().m_id != 0 ) {}`. This is often not what we want (what if entity with that id is no longer alive, or the world was destroyed) but is what we might occasionally write (happened to me) and only notice the unexpected behavior a long time afterward (requiring time to be spent on debugging).

So either we forbid the operator usage, or we make that operator be useful for the most general case (which is currently not the case), as of current it is an error-prone operator on the `flecs`-user level.

A more useful scenario for user programming purposes is `if (entity_view()) {}` leading to the use of `is_valid()` method of the entity which returns bool to be used as the condition of the branch.

**Describe the solution you'd like**
To achieve this and not break the code of `flecs` we have to do following things:
1. Introduce `operator bool() const` into `flecs::entity` which returns the value of `::is_valid()`.
2. Add operators `bool operator==` and `bool operator!=` into `flecs::id` to prevent `flecs` codebase from breaking due to the first change.
3. Make `flecs::entity::is_valid()` **const**, so that we could call it from `operator bool() const`.
4. Also make `flecs::entity::is_alive()` **const** for the consistency of the codebase.

**Comment by SanderMertens** [comment]
CI shows the problem with this: https://github.com/SanderMertens/flecs/pull/429/checks?check_run_id=2754906932

Having both bool & int implicit conversions causes ambiguity in situations like `e != 0`

**Comment by Hexlord** [comment]
> CI shows the problem with this: https://github.com/SanderMertens/flecs/pull/429/checks?check_run_id=2754906932
> 
> Having both bool & int implicit conversions causes ambiguity in situations like `e != 0`

The idea is not to write `e != 0`, fixed the tests to follow that idea.

**Comment by SanderMertens** [comment]
If the only thing that breaks is comparisons with 0 or decays to `int` (but not decays to `uint`) it's worth considering. I'm adding a bunch of tests to make sure that all the scenarios that should still work don't break.

**Comment by SanderMertens** [comment]
Merged!

**Comment by Hexlord** [comment]
Neat! Thank you!
