### ISSUE TITLE
add_owned does not work for prefab children

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#450]
**Describe the bug**
`add_owned` is not "inherited" during prefab child instantiation, tags are missing in the resulting prefab instance' children

**To Reproduce**
```c
struct Comp{int Int;};
struct Tag {};

flecs::world World;
auto Prefab1 = World.prefab();
auto PrefabChild1 = World.prefab().child_of(Prefab1).set_owned<Comp>({123});

auto Prefab2 = World.prefab();
auto PrefabChild2 = World.prefab().child_of(Prefab2).add_owned<Tag>();

auto Instance1 = World.entity().is_a(Prefab1);
for(auto Children : Instance1.children()) {
    for(auto Index : Children) {
        auto Child = Children.entity(Index);
        assert(Child.has<Comp>()); // This passes fine
    }
}

auto Instance2 = World.entity().is_a(Prefab2);
for(auto Children : Instance2.children()) {
    for(auto Index : Children) {
        auto Child = Children.entity(Index);
        assert(Child.has<Tag>()); // This asserts (bug?)
    }
}
```

**Expected behavior**
The code does not assert

**Actual behavior**
The code asserts for the Instance2 which uses tag `add_owned` instead of `set_owned`

**Additional context**
This blocks prefab implementation in my codebase (lots of code crashes assuming component/tag existence)

**Comment by SanderMertens** [comment]
This is expected behavior, for two reasons:
- `add_owned()` doesn't actually add the component to the prefab, it only enforces that a prefab instance gets a private copy of the component.
- Prefab components of children are copied by default, not shared

If you change the above prefab code to this it'll work:
```c
auto Prefab1 = World.prefab();
auto PrefabChild1 = World.prefab().child_of(Prefab1).set<Comp>({123});

auto Prefab2 = World.prefab();
auto PrefabChild2 = World.prefab().child_of(Prefab2).add<Tag>();
```

More details here:
https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#inheritance-hierarchies

Bit of background- the reason why components of prefab children are copied and not shared is because it would cause each instantiated prefab child to end up in its own table. Consider this example, which is what would happen with sharing:

```c
auto Prefab1 = World.prefab();
// Two prefab children that are in the same table
auto PrefabChild1 = World.prefab().child_of(Prefab1).set<Comp>({123});
auto PrefabChild2 = World.prefab().child_of(Prefab1).set<Comp>({456});

auto inst = world.entity().is_a(Prefab1);
// The instantiated children now end up in two tables, whereas the original prefab
// children were in the same table:
[(ChildOf, inst), (IsA, PrefabChild1)]
[(ChildOf, inst), (IsA, PrefabChild2)]
```

Instead the behavior is like this:

```c
auto Prefab1 = World.prefab();
// Two prefab children that are in the same table
auto PrefabChild1 = World.prefab().child_of(Prefab1).set<Comp>({123});
auto PrefabChild2 = World.prefab().child_of(Prefab1).set<Comp>({456});

auto inst = world.entity().is_a(Prefab1);
// The instantiated children also end up in the same table
[(ChildOf, inst), Comp]
[(ChildOf, inst), Comp]
```

**Comment by Hexlord** [comment]
@SanderMertens I see, that explains it, thanks.
So prefab children are a special case, and you only want to write `add_owned` and `set_owned` in the root prefab to prevent sharing.
And to share the children prefab components we need those children to be just an `IsA` of an actual component. This complicates things quite a lot (a special way to describe hierarchical prefabs) :thinking: 
This does make a lot of sense for the low levelness it has.
