### ISSUE TITLE
Add a way to check for uninitialized iterators

### ISSUE THREAD

**Issue by randy408** [SanderMertens/flecs#453]
**Describe the problem you are trying to solve.**
There is no definitive way to tell apart an initialized `ecs_iter_t` from an uninitialized one, this makes it more difficult for bindings where user errors are preferably caught in the binding layer instead of flecs for better integration with the error handling mechanism of the higher level language.

Checking for `it->count` is a quick-and-dirty way to do it, but this assumption isn't valid when all the columns are shared, `count` would always be `0`.

**Describe the solution you'd like**
A boolean field named `is_valid` would work, `ecs_*_next()` can set it to `true`.

**Comment by SanderMertens** [comment]
@randy408 Could you share more details about the problem this would address? My first reaction is that an uninitialized iterator means that memory is uninitialized, and that uninitialized memory should never be exposed by the binding. A check on whether the iterator is initialized would by definition read uninitialized memory, which causes undefined behavior.

**Comment by randy408** [comment]
I'm using the term uninitialized loosely here, my binding indirectly exposes `ecs_iter_t`'s returned from `ecs_query_iter()`, it is technically not uninitialized but unpopulated(?), calling `ecs_is_owned()` for example without a preceding, successful `ecs_*_next()` call will cause an assert in flecs.

Because of the aforementioned corner case with shared columns, looking at `count` is not a reliable way to check for this populated, (more or less) assert-free state. If I wanted to expose data from iterators with only shared columns where `count` is always zero the binding would have to do its own tracking to not cause asserts in flecs.

An `is_valid` field could replace the inadequate `it->count` check by distinguishing iterators that haven't been touched since its creation by `ecs_query_iter()` from iterators on which `ecs_*_next()` was used successfully used but `count` remains zero.
