### ISSUE TITLE
Flecs-meta fails to init

### ISSUE THREAD

**Issue by randy408** [SanderMertens/flecs#455]
**Describe the bug**

Flecs-meta (`update` branch for v2.3+)  fails to load with latest master, flecs asserts in the import callback.

**To Reproduce**
```c
#include <flecs_meta.h>

int main(int argc, char **argv)
{
    ecs_world_t *w = ecs_init();

    ECS_IMPORT(w, FlecsMeta);

    ecs_fini(w);

    return 0;
}
```
Fails on `ECS_SYSTEM(world, EcsSetType, EcsOnSet, EcsMetaType);` - https://github.com/flecs-hub/flecs-meta/pull/35/files#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176R424
```
EcsSetType:1: error: unresolved identifier 'EcsMetaType'
    EcsMetaType
    ^
```

Seems to be related to `ecs_set_name_prefix(world, "Ecs")`, system registration succeeds if it's commented out but it's not a workaround as it breaks other things in the import callback.

**Expected behavior**
Flecs-meta should init and work properly, there doesn't seem to be any other API changes that have to be accounted for on the `update` branch.

**Additional context**
n/a

**Comment by SanderMertens** [comment]
It's working again with the latest flecs: https://github.com/flecs-hub/flecs-meta/actions/runs/1077662223
