### ISSUE TITLE
Improve & organize examples

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#460]
**Describe the problem you are trying to solve.**
One of the most used sources of documentation is the code examples. The list has grown to be quite large though, making it more difficult to find what you need. Additionally, some examples are outdated and don't necessarily show the latest APIs and best practices.

**Describe the solution you'd like**
Redo the examples, use the latest APIs & best practices, and organize them in category-based folders.

**This issue is sponsored!**
Completing it will earn you $250! 💰

**Comment by smilberger** [comment]
I'm about to do an evaluation of flecs for a simulation project I'm working on.  I'll give you any feedback I have on the examples through this issue.

First, though, where is the appropriate place to find "best practices"?  Is the other documentation referenced in the README fairly up to date, reflecting best practices?

Thanks.

**Comment by SanderMertens** [comment]
@smilberger good questions! The low-hanging fruit examples of best practices would be that:
- examples don't use deprecated APIs (anything in the deprecated addon)
- don't use old-style query syntax (for new style query syntax see the Query manual)

There are also plenty of new things that the examples don't show.

The documentation is mostly up to date, but can be improved.

**Comment by smilberger** [comment]
Idea: Add a new example, which is a game built by progressively adding features according to a recipe/tutorial.  

See The [Mal (Make a Lisp)](https://github.com/kanaka/mal) project for such an approach. The game could be simple overall, but utimately playable and complex enough to show basics like movement, scoring, physics, etc.  Write it (with minimal dependencies) in stages as an ASCII console, 2D sprite, or OpenGL game.                                                                                 
                                                                                                                              
Start off with one game entity, then incrementally add features until a representative subset of flecs was covered.  Encourage others to port it to their platform/language.  Having an explicit list of exemplary libraries that work well with flecs would be useful. Emphasize what flecs is doing, and what is external.  It might be better as an external project (flecs-demo-game?).                                                                                                                          
                                                                                                                              
As a learning exercise, I'm working on recreating an old game of mine with flecs, which is simple but hopefully will help me learn what I need.  I was planning on doing it incrementally (informally) as above.                                           
                                                                                                                              
It's nice to have extensive stand-alone examples, but an integrated example would be good too.
