### ISSUE TITLE
entity and entity_view should be implicitly default constructible

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#461]
**Describe the problem you are trying to solve.**
Given 
```c
struct Comp {
    flecs::entity_view Entity;
}
```
We are able to write
```c
world.entity().add<Comp>();
```
but not
```c
world.entity().set<Comp>({});
```
because `Comp` construction from initializer list `{}` is considered implicit, and the default constructors of `entity` and `entity_view` are currently marked explicit.

**Describe the solution you'd like**
Make both default constructors implicit.

**Comment by SanderMertens** [comment]
Merged it!
