### ISSUE TITLE
Assertion hit reaching max entity ID

### ISSUE THREAD

**Issue by zaklaus** [SanderMertens/flecs#464]
**Describe the bug**
Upon setting an entity range to 0-UINT16_MAX, if we create 1 entity, proceed to delete it and create another one again, we hit an assertion at line 5521 in function `ecs_new_id` that states:
```
ecs_assert(!world->stats.max_id || entity <= world->stats.max_id, 
        ECS_OUT_OF_RANGE, NULL);
```
This is most likely caused by the fact that new entity IDs now include generation index after an entity deletion, which is not accounted for in the assertion, as it doesn't extract the ID itself from the handle. Thus, with the range specified above, entity handles consist of numbers above the limit, triggering a false assertion in the process.

**To Reproduce**
1. call `ecs_set_entity_range(world, 0, UINT16_MAX)`
2. create 1 entity
3. delete that entity
4. attempt to create another entity
5. observe the assertion

**Expected behavior**
Entities with recycled IDs should be created without issues, even with the previously mentioned entity range.

**Additional context**
I am using the latest stable release of flecs.

**Comment by SanderMertens** [comment]
Fixed!
