### ISSUE TITLE
Any by default for components in queries

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#469]
**Describe the problem you are trying to solve.**
When transitioning code to support prefabs, we have to insert "ANY:[component_name]" for all query's components of each system so that they match instances of prefabs with some of the components being shared with the prefab, which is a lot of boilerplate, and the code increases in size considerably.

**Describe the solution you'd like**
It seems like the "ANY" matching is actually the default (my codebase never cares about component being actually OWNED) use case as opposed to "OWNED" matching, as it would reduce code size considerably. So making it the default one, which is a breaking change, might make coding with flecs easier when using prefabs.

**Comment by SanderMertens** [comment]
Fixed!

**Comment by Hexlord** [comment]
Wow, that took quite a lot of commits :D Cheers!
