### ISSUE TITLE
OnSet/OnRemove should be triggered for prefab-shared components

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#470]
**Describe the problem you are trying to solve.**
When using prefabs in conjunction with OnSet and OnRemove monitors, a problem occurs due to monitors not being triggered for the instances of the prefab that is being modified.

**Describe the solution you'd like**
Pseudocode, as suggested by Sander (https://discord.com/channels/633826290415435777/689159031239082065/867890640732815371)
```c
emit_on_set(ent, component, check_is_a) {
  if (!ent.has(Prefab)) {
    invoke_trigger(OnSet, ent, component);
  }
  
  if (check_is_a) {
    for (table : tables(pair(IsA, ent))) {
      if (!table.has(component)) {
        for (entity : table.entities) {
          emit_on_set(entity, component, entity.marked == true);
        }
      }
    }
  }
}
```

**Comment by SanderMertens** [comment]
Fixed!
