### ISSUE TITLE
An error is reported when compiling CPP example using vs2015

### ISSUE THREAD

**Issue by Zachary9079** [SanderMertens/flecs#474]
An error is reported when compiling CPP example using vs2015, such as: flecs-2.4.4\include\flecs/cpp/iter.hpp(61): error C2512: “std::is_empty<_Ty>”: No suitable default constructor is available

**Comment by Zachary9079** [comment]
> > such as:1>flecs-master\include\flecs/cpp/invoker.hpp(218): error C2672: “flecs::_::each_invoker<main::<lambda_2894f3ad125b7bc42de28eec69575cb2>,Message>::invoke_callback”: No matching overloaded function found
> 
> That sounds like you're not providing the correct signature for the `each` function. The function should look either look like this, with the components as arguments:
> 
> ```c
> world.query<Position, Velocity>()
>   .each([](Position& p, Velocity& v) {
>   });
> ```
> 
> Or like this, with an additional entity argument:
> 
> ```c
> world.query<Position, Velocity>()
>   .each([](flecs::entity e, Position& p, Velocity& v) {
>   });
> ```

But I reported this error by compiling the CPP example in your repository. I use the Visual Studio 2015  compiler

**Comment by SanderMertens** [comment]
> But I reported this error by compiling the CPP example in your repository. I use the Visual Studio 2015 compiler

Oh that's not good. Which example was this?

**Comment by codylico** [comment]
_outsider comment; feel free to ignore:_

Could it be somewhere near here? I'm not sure which source line @Zachary9079 is referring to, but I remember that relations were recently changed so maybe something broke near here?
https://github.com/SanderMertens/flecs/blob/9efd8eb47ee977356bfa47bd6776313ccd5c6d68/examples/cpp/entities/relations/src/main.cpp#L37

**Comment by SanderMertens** [comment]
@Zachary9079 I just noticed that one of the OS API examples is failing to build on Windows, and somehow CI wasn't reporting back the issue. Will investigate further.

@codylico Thx for looking into this! I think that example is OK, it's building on all platforms/compilers in CI

**Comment by SanderMertens** [comment]
This should have been fixed as part of https://github.com/SanderMertens/flecs/issues/541. Let me know if you're still having issues!
