### ISSUE TITLE
Report error instead of assert where it's safe to do so

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#476]
**Describe the problem you are trying to solve.**
When supplying invalid inputs into the flecs api, it will trigger an assert which brings the entire application down with it. In cases where flecs is integrated with Unreal, this includes bringing the editor down as well, which results in lost work. 

**Describe the solution you'd like**
In several places, these asserts could safely report a warning, and return a default value (nullptr, false, etc), thus leaving the flecs internal state in a known good state. It was discussed on the discord about having a soft assert, which would notify the os_api that an invalid input was received and discarded. This would allow the host to handle this input error in it's own manner, eg., in UE4, the os_api hook report an error, and then queue an exit of the play session, thus leaving the editor intact and a message to the developer about what went wrong.

**Comment by SanderMertens** [comment]
Done!
