### ISSUE TITLE
Annotations for arbitrary components not working

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#482]
**Describe the bug**
Since v3 annotations ( https://flecs.docsforge.com/master/designing-with-flecs/#annotations ) for arbitrary components are no longer parsed correctly

**To Reproduce**
Try adding a system like this
```c
ECS.system("Force sync point post-render", "[inout] :*").iter([](iter &) {});
```

**Expected behavior**
A sync point gets inserted if necessary

**Actual behavior**
Program outputs this and does not insert any sync points
```c
Force sync point post-render:9: error: unexpected character ':'
    [inout] :*
            ^
```

**Comment by SanderMertens** [comment]
This (deprecated) syntax is no longer supported, try this
```
[inout] *()
```

For more information on new/old syntax, see this discussion https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-1242759:
