### ISSUE TITLE
Add userdata to system callback action

### ISSUE THREAD

**Issue by GamerJie** [SanderMertens/flecs#49]
Could add a custom userdata to system callback action?

**Comment by ArnCarveris** [comment]
See `param`:
https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L1499-L1507
https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L1527-L1538

See `ctx`:
https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L494-L519

**Comment by SanderMertens** [comment]
@GamerJie as Arn mentioned, you can pass in a user-defined parameter if you invoke a system with `ecs_run`. This parameter is accessible through `rows->param`. Currently `param` is not used for systems that are invoked automatically.

The `ctx` refers to the world context, which is user data you can get/set on the world with `ecs_get_context` and `ecs_set_context`.

Another way to add user data to a system, is to add a component to it. For example:

```
typedefe struct MyUserData {
    ....
} MyUserData;

void MySystem(ecs_rows_t *rows) {
    ECS_COLUMN(rows, MyUserData, ctx, 1);

    printf("%d\n", ctx->...);
}

int main(int argc, char *argv[]) {
    ecs_world_t *world = ecs_init();

    ECS_COMPONENT(world, MyUserData);

    ECS_SYSTEM(world, MySystem, EcsOnUpdate, SYSTEM.MyUserData, ...);

    ecs_set(word, MySystem, MyUserData, { ... });
}
```

Additionally I could support a `ecs_system_set_context` function that sets the `param` field in `ecs_rows_t`.

**Comment by GamerJie** [comment]
@ArnCarveris @SanderMertens  Thanks for your answer. The world context is not my need, i need every system has a single userdata.I am not good at c, so i think that ecs_system_set_context is very good, and it is easy to use. So is that possible to add it ?

**Comment by SanderMertens** [comment]
@GamerJie I just added support for it with these new functions:

```c
void ecs_set_system_context(
    ecs_world_t *world,
    ecs_entity_t system,
    const void *ctx);

void* ecs_get_system_context(
    ecs_world_t *world,
    ecs_entity_t system);
```

Simply call like this:

```c
ECS_SYSTEM(world, MySystem, EcsOnUpdate, Position);

int my_var = 0;
ecs_set_system_context(world, MySystem, &my_var);
```

You can also access the user data from the system callback, through `rows->param`.

**Comment by GamerJie** [comment]
@GamerJie Thanks. It is very useful for me.
