### ISSUE TITLE
"system" in "module" failed to run successfully

### ISSUE THREAD

**Issue by Zachary9079** [SanderMertens/flecs#491]
Please ask a question. I made the simple_module class in cpp example 04_simple_module into a dynamic library. After loading the dynamic library successfully, I found that the "system" in this "module" failed to run successfully. If it is made into a static library, then "system" in "module" can run successfully.

**Comment by SanderMertens** [comment]
This sounds more like a compiler/linker issue. Flecs is not aware of whether code is running in a DLL, a static library or whether everything is running in the same executable, so that shouldn't make a difference. What could make a difference is whether symbols are not correctly exported, or if the module is imported or not.

Could you share the code after you changed it to a DLL? Maybe I can spot an issue with it/

**Comment by Zachary9079** [comment]
I use flecs version 2.3.2, and the compiler is VS2015. in order to generate dynamic library, "simple_module.h" is modified, and the modified contents are as follows:

#ifndef SIMPLE_MODULE_H
#define SIMPLE_MODULE_H

#ifdef DLL_EXPORTS
#define DLLAPI		__declspec(dllexport)
#else
#define DLLAPI		_declspec(dllimport)
#endif

/* This generated file contains includes for project dependencies */
#include "simple_module/bake_config.h"

struct Position {
    float x;
    float y;
};

struct Velocity {
    float x;
    float y;
};

struct DLLAPI SimpleModule {
    SimpleModule(flecs::world& world);
    flecs::entity position;
    flecs::entity velocity;
    flecs::entity move;
};

#endif

**Comment by Zachary9079** [comment]
> This sounds more like a compiler/linker issue. Flecs is not aware of whether code is running in a DLL, a static library or whether everything is running in the same executable, so that shouldn't make a difference. What could make a difference is whether symbols are not correctly exported, and if the module is imported with `world.import<Module>()`.
> 
> Could you share the code after you changed it to a DLL? Maybe I can spot an issue with it/

I use flecs version 2.3.2, and the compiler is VS2015. in order to generate dynamic library, "simple_module.h" is modified, and the modified contents are as follows:

#ifndef SIMPLE_MODULE_H
#define SIMPLE_MODULE_H

#ifdef DLL_EXPORTS
#define DLLAPI	__declspec(dllexport)
#else
#define DLLAPI	_declspec(dllimport)
#endif

/* This generated file contains includes for project dependencies */
#include "simple_module/bake_config.h"

struct Position {
float x;
float y;
};

struct Velocity {
float x;
float y;
};

struct DLLAPI SimpleModule {
SimpleModule(flecs::world& world);
flecs::entity position;
flecs::entity velocity;
flecs::entity move;
};

#endif

**Comment by SanderMertens** [comment]
Thanks for sharing! Could you also show me the code of `SimpleModule`, and the code that imports it?

**Comment by Zachary9079** [comment]
> Thanks for sharing! Could you also show me the implementation of `SimpleModule`, and the code that imports it?

this is the implementation of `SimpleModule` :

SimpleModule::SimpleModule(flecs::world& ecs)
{
    /* Register module with world */
    ecs.module<SimpleModule>();

    /* Register components */
    this->position = ecs.component<Position>();
    this->velocity = ecs.component<Velocity>();

    /* Register system */
    this->move = ecs.system<Position, const Velocity>("Move")
        .each([](flecs::entity e, Position& p, const Velocity& v) {    
            p.x += v.x;
            p.y += v.y;

            std::cout << "Moved " << e.name() << " to {" <<
                p.x << ", " << p.y << "}" << std::endl;
        });
}

 and this is the code that imports  `SimpleModule`:

#include <simple_module.h>

int main(int argc, char *argv[]) {
    /* Create the world, pass arguments for overriding the number of threads,fps
     * or for starting the admin dashboard (see flecs.h for details). */
    flecs::world ecs(argc, argv);

    /* Import module containing Position, Velocity and Move */
    ecs.import<SimpleModule>();

    /* Create entity with imported components */
    ecs.entity("MyEntity")
        .set<Position>({10, 20})
        .set<Velocity>({1, 1});

    ecs.set_target_fps(1);

    /* Run imported move system */
    while (ecs.progress()) { }
}

**Comment by SanderMertens** [comment]
@Zachary9079 it looks like there might be an issue with how you register the module, this:
```c
ecs.module();
```
should be
```c
ecs.module<SimpleModule>();
```

**Comment by Zachary9079** [comment]
> @Zachary9079 it looks like there might be an issue with how you register the module, this:
> 
> ```c
> ecs.module();
> ```
> 
> should be
> 
> ```c
> ecs.module<SimpleModule>();
> ```
I modified it as follows. After the test, the "system" still did not run

SimpleModule::SimpleModule(flecs::world& ecs)
{
/* Register module with world */
ecs.module<SimpleModule>();

/* Register components */
this->position = ecs.component<Position>();
this->velocity = ecs.component<Velocity>();

/* Register system */
this->move = ecs.system<Position, const Velocity>("Move")
    .each([](flecs::entity e, Position& p, const Velocity& v) {    
        p.x += v.x;
        p.y += v.y;

        std::cout << "Moved " << e.name() << " to {" <<
            p.x << ", " << p.y << "}" << std::endl;
    });
}

**Comment by Zachary9079** [comment]
> @Zachary9079 it looks like there might be an issue with how you register the module, this:
> 
> ```c
> ecs.module();
> ```
> 
> should be
> 
> ```c
> ecs.module<SimpleModule>();
> ```

I modified it as follows. After the test, the "system" still did not run

`SimpleModule::SimpleModule(flecs::world& ecs)
{
/* Register module with world */
ecs.module<SimpleModule>();

/* Register components */
this->position = ecs.component<Position>();
this->velocity = ecs.component<Velocity>();

/* Register system */
this->move = ecs.system<Position, const Velocity>("Move")
    .each([](flecs::entity e, Position& p, const Velocity& v) {    
        p.x += v.x;
        p.y += v.y;

        std::cout << "Moved " << e.name() << " to {" <<
            p.x << ", " << p.y << "}" << std::endl;
    });
}`

**Comment by Zachary9079** [comment]
> @Zachary9079 it looks like there might be an issue with how you register the module, this:
> 
> ```c
> ecs.module();
> ```
> 
> should be
> 
> ```c
> ecs.module<SimpleModule>();
> ```

According to your suggestion, I modified it as follows. After the test, I don't know why this "system" still doesn't run
SimpleModule::SimpleModule(flecs::world& ecs)
{
    /* Register module with world */
  `  ecs.module<SimpleModule>();`

    /* Register components */
    this->position = ecs.component<Position>();
    this->velocity = ecs.component<Velocity>();

    /* Register system */
    this->move = ecs.system<Position, const Velocity>("Move")
        .each([](flecs::entity e, Position& p, const Velocity& v) {    
            p.x += v.x;
            p.y += v.y;

            std::cout << "Moved " << e.name() << " to {" <<
                p.x << ", " << p.y << "}" << std::endl;
        });
}

**Comment by Zachary9079** [comment]
> This sounds more like a compiler/linker issue. Flecs is not aware of whether code is running in a DLL, a static library or whether everything is running in the same executable, so that shouldn't make a difference. What could make a difference is whether symbols are not correctly exported, and if the module is imported with `world.import<Module>()`.
> 
> Could you share the code after you changed it to a DLL? Maybe I can spot an issue with it/



> @Zachary9079 it looks like there might be an issue with how you register the module, this:
> 
> ```c
> ecs.module();
> ```
> 
> should be
> 
> ```c
> ecs.module<SimpleModule>();
> ```

I have solved this problem. By putting "Create entity" before "Import module", the modified code is as follows:
#include <simple_module.h>

int main(int argc, char argv[]) {
/ Create the world, pass arguments for overriding the number of threads,fps
* or for starting the admin dashboard (see flecs.h for details). */
flecs::world ecs(argc, argv);

/* Create entity with imported components */
ecs.entity("MyEntity")
    .set<Position>({10, 20})
    .set<Velocity>({1, 1});

/* Import module containing Position, Velocity and Move */
ecs.import<SimpleModule>();

ecs.set_target_fps(1);

/* Run imported move system */
while (ecs.progress()) { }
}
