### ISSUE TITLE
Crash when calling `ecs_delete_children` with a staged world

### ISSUE THREAD

**Issue by jemc** [SanderMertens/flecs#496]
**Describe the bug**
The `ecs_delete_children` function assumes it always is given a real `ecs_world_t*` as its `world` parameter, rather than an `ecs_stage_t*` masquerading as the world, as is the case within a system / query iterator, where the delete operation is expected to be deferred rather than immediately executed.

**To Reproduce**
- From within a system / query iteration, call `ecs_delete_children` using `it->world` as the `world` parameter.
- Observe the crash, as shown in these captured stack frames from `lldb`:

```c
(lldb) 
frame #4: 0x00000000004229ad example-game`ecs_delete_children(world=0x0000000000d6ea30, parent=430) at flecs.c:7037:5
   7034	    ecs_world_t *world,
   7035	    ecs_entity_t parent)
   7036	{
-> 7037	    on_delete_action(world, parent);
   7038	}
   7039	
   7040	void ecs_delete(
(lldb) 
frame #3: 0x00000000004229dd example-game`on_delete_action(world=0x0000000000d6ea30, entity=430) at flecs.c:7028:5
   7025	    ecs_world_t *world,
   7026	    ecs_entity_t entity)
   7027	{
-> 7028	    on_delete_relation_action(world, entity);
   7029	    on_delete_relation_action(world, ecs_pair(entity, EcsWildcard));
   7030	    on_delete_object_action(world, ecs_pair(EcsWildcard, entity));
   7031	}
(lldb) 
frame #2: 0x000000000046476d example-game`on_delete_relation_action(world=0x0000000000d6ea30, id=430) at flecs.c:6997:28
   6994	    ecs_world_t *world,
   6995	    ecs_id_t id)
   6996	{
-> 6997	    ecs_id_record_t *idr = flecs_get_id_record(world, id);
   6998	    if (idr) {
   6999	        ecs_entity_t on_delete = idr->on_delete;
   7000	        if (on_delete == EcsThrow) {
(lldb) 
frame #1: 0x0000000000423c79 example-game`flecs_get_id_record(world=0x0000000000d6ea30, id=430) at flecs.c:22167:12
   22164	    const ecs_world_t *world,
   22165	    ecs_id_t id)
   22166	{
-> 22167	    return ecs_map_get(world->id_index, ecs_id_record_t,
   22168	        ecs_strip_generation(id));
   22169	}
   22170	
(lldb)
frame #0: 0x0000000000431c75 example-game`_ecs_map_get(map=0x0000000200000001, elem_size=80, key=430) at flecs.c:11834:5
   11831	        return NULL;
   11832	    }
   11833	
-> 11834	    ecs_assert(elem_size == map->elem_size, ECS_INVALID_PARAMETER, NULL);
   11835	
   11836	    ecs_bucket_t * bucket = get_bucket(map, key);
   11837	    if (!bucket) {
```

**Expected behavior**
I expected the children of the given entity to be deleted at the end of the frame (deferred deletion). 

**Additional context**
I was also planning to add other new children entities immediately after deleting all existing children, so hopefully the deferred deletion of children can have a deferred creation of children following that operation, and have those two operations be executed in order.

The context of my desire to delete all existing children and create new children is a system that executes when the player moves from one room to another room, which tears down all assets of the current room and spins up all assets of the newly current room.

**Comment by SanderMertens** [comment]
Fixed!
