### ISSUE TITLE
flecs-systems-civetweb failed building on win10 with vs2017 installed

### ISSUE THREAD

**Issue by raptoravis** [SanderMertens/flecs#50]
when `bake clone SanderMertens/flecs-systems-civetweb`:

flecs-systems-civetweb\src\civetweb.c(641): error C2027: use of undefined type 'timespec'

**Comment by ArnCarveris** [comment]
Try this: https://github.com/flecs-hub/flecs-systems-civetweb/pull/3

**Comment by SanderMertens** [comment]
@raptoravis the PR that @ArnCarveris posted should work for you. I still need to take a look at this PR and ensure it works on Linux / MacOS.

**Comment by SanderMertens** [comment]
I pushed a fix for MacOS to https://github.com/flecs-hub/flecs-systems-civetweb/pull/3, asked @ArnCarveris to validate whether it still works on Windows

**Comment by SanderMertens** [comment]
@raptoravis This issue should have been fixed. Let me know if you are still seeing problems.
