### ISSUE TITLE
Entities do not get deleted when registering OnRemove system

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#52]
By @teksoc-1:

When doing some test cases of deleting entities and having OnRemove systems registered with components of the deleted entities, the entities seem to not get deleted, and will see them again next iteration. If I do not register OnRemove systems, the entities get deleted as expected, however, when the OnRemove Systems are applied ( and respectively called as expected ), the entities do not get deleted.

**Comment by SanderMertens** [comment]
@teksoc-1 This sounds like something that could potentially be easy to reproduce in a small code example, could you try to post one here?

I have some tests for this and haven't observed this behavior yet, so there must be something special about your code that makes this happen.

**Comment by teksoc-1** [comment]
#include "flecs.h"

#define MAX_ENTITIES    10
#define MAX_ITERATIONS  20

typedef int DummyComponent;

void
CreateEntitiesOnUpdate( ecs_rows_t * rows )
{
    ECS_COLUMN_COMPONENT( rows, DummyComponent, 1 );
    
    ecs_os_log( "Creating %i entites ...", MAX_ENTITIES );
    ecs_new_w_count( rows->world, DummyComponent, MAX_ENTITIES );
}

void
OnRemoveDummyCommponent( ecs_rows_t * rows )
{
    ecs_os_log( "%s rows->count: %i", __FUNCTION__, rows->count );
}

void
DeleteEntitiesOnStore( ecs_rows_t * rows )
{
    ecs_os_log( "%s rows->count: %i", __FUNCTION__, rows->count );
    
    static unsigned int iterations = 0;
    iterations++;
    
    for ( unsigned int i = 0; i < rows->count; i++ )
    {
        ecs_delete( rows->world, rows->entities[ i ] );
    }
    
    if ( MAX_ITERATIONS == iterations )
    {
        ecs_quit( rows->world );
    }
}


int main( int argc, char ** argv )
{
    int rc = -1;
    
    ecs_world_t * world = ecs_init();
    
    ECS_COMPONENT( world, DummyComponent );
    ECS_SYSTEM( world, CreateEntitiesOnUpdate, EcsOnUpdate, .DummyComponent );
    ECS_SYSTEM( world, DeleteEntitiesOnStore, EcsOnStore, DummyComponent );
    ECS_SYSTEM( world, OnRemoveDummyCommponent, EcsOnRemove, DummyComponent );

    ecs_set_target_fps( world, 1 );
    
    while ( ecs_progress( world, 0 ) );
    
    rc = ecs_fini( world );
    
    return rc;
}

**Comment by teksoc-1** [comment]
On my end (macOS), I can also use this test case to demonstrate the memory continues to grow ( set MAX_ENTIES to relatively high number - again, unsure if this whole set up is erroneous on my part.

**Comment by teksoc-1** [comment]
output on my end:
```
[log] Creating 10 entites ...
[log] DeleteEntitiesOnStore rows->count: 10
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] Creating 10 entites ...
[log] DeleteEntitiesOnStore rows->count: 20
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] OnRemoveDummyCommponent rows->count: 1
[log] Creating 10 entites ...

**Comment by teksoc-1** [comment]
however, commenting out the OnRemove system, I get the expected results: DeleteEntitiesOnStore() rows->count == MAX_ENTITIES every iteration

**Comment by SanderMertens** [comment]
@teksoc-1 I've reproduced the issue, curious! I'll be looking into it and will let you know when I have a fix. I'll also look into the memory leak.

**Comment by teksoc-1** [comment]
ok, I'm really glad was able to support, and wasn't something erroneous on my part.

**Comment by SanderMertens** [comment]
Sure thing, your code looks solid!

**Comment by teksoc-1** [comment]
if you are able to reproduce the leak ... here is the crude patch I applied after the first entity_index iteration in merge_commits():
```
it = ecs_map_iter( stage->entity_index );
    while ( ecs_map_hasnext( &it ) )
    {
        ecs_entity_t entity = ECS_INVALID_ENTITY;
        ecs_row_t * row = ecs_map_next_w_key( &it, &entity );
        ecs_table_column_t * staged_columns = NULL;
        
        if ( ecs_map_has( stage->data_stage, ( uintptr_t ) row->type, &staged_columns ) )
        {
            unsigned int column_count = ecs_vector_count( row->type );
            
            for ( unsigned int i = 0; i < column_count + 1; i++ )
            {
                ecs_vector_free( staged_columns[ i ].data );
                staged_columns[ i ].data = NULL;
            }
        }
    }
```

**Comment by SanderMertens** [comment]
@teksoc-1 I just pushed a fix, looked like some old code was preventing this from working correctly. Can you retry?

I haven't looked at the mem leak yet.

**Comment by teksoc-1** [comment]
Ok, awesome that fix seems to work at least from the output of the logging!

**Comment by SanderMertens** [comment]
Great! I'll close this issue and #53

**Comment by teksoc-1** [comment]
@SanderMertens - revisiting the creation of entities using the same test code as above, however creating entities EcsOnLoad vice EcsOnUpdate .... I'm not getting entry when using EcsOnLoad, that is a valid use case right?

**Comment by teksoc-1** [comment]
worth mentioning on this .... looks like on entry (when using EcsOnUpdate), rows->count == 1 && rows->entities == NULL ... I guess was expecting to get all entities in the main store, but I guess the more important take away is perhaps the perceived inconsistency of matched entities?

**Comment by SanderMertens** [comment]
@teksoc-1 I reproduced the problem and created an issue for it: https://github.com/SanderMertens/flecs/issues/56

You're correct, tasks are currently run in the run_tasks function, and tasks are not executed per phase. This is not correct, as running tasks in different phases should be possible. I'll work on fixing that.
