### ISSUE TITLE
Add examples to flecs repository

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#55]
Add example projects that just demonstrate Flecs features to the repository. These examples should not rely on external modules, but should be used to concisely demonstrate a single feature (all other examples / demo's should be stored in flecs-hub).

**Comment by ArnCarveris** [comment]
Make it under `CMake` instead of `bake`.

**Comment by SanderMertens** [comment]
@ArnCarveris It will be using bake.
