### ISSUE TITLE
Mutable flecs::ref

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#551]
**Describe the problem you are trying to solve.**
When integrating procedural code into ECS, being executed from main thread and containing nested calls with `.get_mut`-s and `.get`-s, it often leads to problems:
1. Any archetype mutation invalidates all the pointers, and top-level functions are not aware of that.
2. `.modified` after `.get_mut` is easy to forget
see [discord message](https://discord.com/channels/633826290415435777/841178490979876914/911419180354502666) for contextn.

refs & mutable refs would protect from
- archetype mutations in the main thread flow
- would help with not forgetting .modified by providing a lambda modification interface only
- are totally fine with function-nesting

**Describe the solution you'd like**
A mutable `flecs::ref` for use in those scenarios.
Ideally it would also allow to access it without `.set` for reading.

**Comment by SanderMertens** [comment]
Fixed!
