### ISSUE TITLE
Task is not executed when assigned to EcsOnLoad phase

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#56]
When a task (a system which does not subscribe for any entities) is registered with the EcsOnLoad phase, it is not executed. The following code reproduces the issue:

```c
typedef int DummyComponent;

void
Task( ecs_rows_t * rows )
{    
    printf("Task executed\n");
}

int main( int argc, char ** argv )
{    
    ecs_world_t * world = ecs_init();
    
    ECS_COMPONENT( world, DummyComponent );
    ECS_SYSTEM( world, Task, EcsOnLoad, .DummyComponent );

    printf("Run systems\n");

    ecs_progress( world, 0 );

    printf("Done\n");
    
    return ecs_fini(world);
}
```

**Comment by teksoc-1** [comment]
Worth capturing here, if the the system is registered with the EcsOnUpdate phase, it will be executed, however rows->count == 1 and rows->entities == NULL; should rows->count be equal to zero for Tasks?

**Comment by SanderMertens** [comment]
@teksoc-1 I checked in a fix that allows task systems to be ran in any phase. They basically behave now like any other system, and will be executed in the order of the phase first, then the order of declaration.

You're right that `rows->count` should be 0, I added this to the testcase to ensure this is the case. Thanks for reporting the issue! Let me know if the fix works for you.

**Comment by teksoc-1** [comment]
@SanderMertens Solid fix - works here on my end, thank you.

**Comment by SanderMertens** [comment]
Awesome! Closing the issue.
