### ISSUE TITLE
Methods .get and .set should lock the table

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#562]
**Describe the problem you are trying to solve.**
When doing `entity::get([&](const Comp &comp) {..}`, it is scary that we could invalidate the comp reference by creating entities / mutating archetype of the entity, and we could never notice that, it could be hard to debug. 

Example:
```c
e.get([&](const Comp &comp) {
    e.add<OtherComp>(); // this should assert-fail, but it does not.
    printf("Number: %i", comp.number); // this is invalid because previous line could have mutated the table, but it is hard find it out.
});
```

**Describe the solution you'd like**
Locking the table would allows us to observe problematic mutations at the moment of their happening.

**Comment by SanderMertens** [comment]
Fixed!
