### ISSUE TITLE
Idea of singletons usage in systems

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#563]
**Describe the problem you are trying to solve.**
Writing less code.

**Describe the solution you'd like**
This is just an idea:
Maybe we could type-tag our components when describing a system to specify that they are singletons, like this:
```c
template<typename T>
struct Singleton{
    using Type = T;
}
world.system<Comp1, Comp2, flecs::Singleton<Comp3>>("System Name").iter(iter Iter) {
    auto &Comp3 = *Iter.term<Comp3>(3);
}
```
Template machinery could test Args against being a Singleton (which is obvious with SFINAE, but maybe there could be other ways), and take his ::Type, but also mark him as `.singleton()` automatically.

**Comment by SanderMertens** [comment]
This will be addressed by a new `Singleton` property, see bottom of https://github.com/SanderMertens/flecs/discussions/532

It'll be used like
```c
world.component<Comp>().add(flecs::Singleton);
```

**Comment by Hexlord** [comment]
> This will be addressed by a new `Singleton` property, see bottom of #532
> 
> It'll be used like
> 
> ```c
> world.component<Comp>().add(flecs::Singleton);
> ```

Perfect, feel free to close this if it makes sense

**Comment by Hexlord** [comment]
Solved this on user level with a wrapper and `&` appendix signalling singleton role of term
