### ISSUE TITLE
Explorer triggered internal error

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#567]
**Describe the bug**
While running the explored attached to a game instance, the following assert was triggered from entering this rule:
`FECSScriptStructComponent(_CMP), !FTransientComponent(_CMP), _CMP(This), !Prefab(This), !Component(*, This), !Identifier(This, Name)`
```C
    /* Same as above, if the object is a variable, store it and flag it */
    if (term->obj.var == EcsVarIsVariable) {
        const ecs_rule_var_t *var = find_variable(
            rule, EcsRuleVarKindEntity, term_id_var_name(&term->obj));

        /* Variables should have been declared */
        ecs_assert(var != NULL, ECS_INTERNAL_ERROR, NULL);
```

Trimmed stack trace using commit https://github.com/SanderMertens/flecs/commit/dd1ebb64f5731fda95aeb8670ad7754be020e17c:
```
OsHalt() FlecsNativeBindings.cpp:154
term_to_pair(ecs_rule_t *,ecs_term_t *) flecs.c:30311
insert_term(ecs_rule_t *,ecs_term_t *,int,bool *) flecs.c:31685
compile_program(ecs_rule_t *) flecs.c:31814
ecs_rule_init(ecs_world_t *,const ecs_filter_desc_t *) flecs.c:31973
rest_reply(const ecs_http_request_t *,ecs_http_reply_t *,void *) flecs.c:23693
handle_request(ecs_http_server_t *,ecs_http_request_impl_t *) flecs.c:34269
dequeue_requests(ecs_http_server_t *,float) flecs.c:34293
ecs_http_server_dequeue(ecs_http_server_t *,float) flecs.c:34448
DequeueRest(ecs_iter_t *) flecs.c:23781
ecs_run_intern(ecs_world_t *,ecs_stage_t *,unsigned long long,EcsSystem *,int,int,float,int,int,void *) flecs.c:38880
ecs_run_pipeline(ecs_world_t *,unsigned long long,float) flecs.c:36858
ecs_workers_progress(ecs_world_t *,unsigned long long,float) flecs.c:36244
ecs_run_pipeline(ecs_world_t *,unsigned long long,float) flecs.c:36814
ecs_progress(ecs_world_t *,float) flecs.c:37042
```

**Comment by SanderMertens** [comment]
Repro: https://www.flecs.dev/explorer/?q=hQAAAD9GRUNTU2NyaXB0U3RydWN0Q29tcG9uZW50KF9DTVApLAggIUZUcmFuc2kgEuAIG0AiBChUaGlzQCcFUHJlZmFi4AAO4AEsAiosIMAjAUlkIEYRaWZpZXIoVGhpcywgTmFtZSkA&p=nAAAAD9GRUNTU2NyaXB0U3RydWN0Q29tcG9uZW50CkZUcmFucwBpIArgARMECkEgPSDgETIAQuATHQEsIOAMUQBYIDMCQQpZIAUQQgpaID0gQSwgUHJlZmFiCgA-

Looks like the behavior on the latest master has changed. The error that is reported is now:
```
Query error: unconstrained variable '_2'
```

**Comment by SanderMertens** [comment]
Smaller repro: https://www.flecs.dev/explorer/?q=KQAAADFUcmFpdChfQyksIF9DKFRoaXMgCRMhQ29tcG9uZW50KCosIFRoaXMpAA--&p=GAAAADdBID0gVHJhaXQKClggPSBBClkgPSBCCgA-

**Comment by SanderMertens** [comment]
Fixed!
