### ISSUE TITLE
Question: Best way to update some systems at different intervals?

### ISSUE THREAD

**Issue by xgalaxy** [SanderMertens/flecs#57]
What would be the best way to have some systems update with deltaTime, eg `ecs_progress` and other systems update at stable tick intervals eg. for physics the deltaTime would be fixed to some predetermined value and likely called more than once in a frame depending on certain factors.

I'm not sure if what I'm asking is possible but thinking about this from what I know about the library so far maybe `ecs_progress` could be updated to allow me to specify which systems / features to progress. I'm not even sure `ecs_progress` would be the best place to specify something like this, as I'm sure there is a certain amount of overhead with that call and calling multiple times in a frame is maybe too costly. But it certainly seems like the most convenient place.

The work around right now is that each system that cares about having a fixed timestep needs to track this themselves.

**Comment by xgalaxy** [comment]
Sorry rolling this over in my mind so I'm just spitballing ideas here.

Maybe the way to do this is have a separate api for more complicated tilmestep scenarios and keep `ecs_progress` the way it is for people who need or want simplified behavior.

The more complicated api could be something like:
`ecs_begin_timestep()`
`ecs_timestep(<filter>, <timestep_value>)`
`ecs_end_timestep()`

Where `<filter>` is systems or features to match on that will have their systems update called. 
Where `<timestep_value>` is the amount of time to pass to the systems update method.

This could be used like:

```
void doUpdate()
{
   float deltaTime = ... // calculate deltaTime
   float physicsStep = ...// hardcoded fixed physics time step
   int numPhysicsSteps = ...// calculate how many physics steps to do
   
   ecs_begin_timestep();
   
   ecs_timestep(MyNonPhysicsFeature, deltaTime)
   for(int i = 0; i < numPhysicsSteps; ++i) {
      ecs_timestep(MyPhysicsFeature, physicsStep)
   }
   
   ecs_end_timestep();
}
```

**Comment by SanderMertens** [comment]
@xgalaxy you're looking to update two systems in the same frame with different deltaTime's? That's interesting.. won't that mess up with the simulation, e.g. your physics moves slower/faster than the rest of the game logic?

In any case, you could do something like this I think:

```c
#define PHYSICS_TIME_INCREMENT (0.16)
typedef float PhysicsTime;

void PTimeProvider(ecs_rows_t *rows) {
    ECS_COLUMN(rows, PhysicsTime, pt, 1);
    *pt += PHYSICS_TIME_INCREMENT;
}

void SomePhysicsSystem(ecs_rows_t *rows) {
    ECS_COLUMN(rows, PhysicsTime, pt, 1);
    ...
}

int main(int argc, char *argv[]) {
    ecs_world_t *world = ecs_init();

    ECS_COMPONENT(world, PhysicsTime);
    ECS_SYSTEM(world, PTimeProvider, EcsOnLoad, SYSTEM.PhysicsTime);
    ECS_SYSTEM(world, SomePhysicsSystem, PTimeProvider.PhysicsTime, << components >>);
   
    while (ecs_progress(world, 0)) { } // normal systems still use flecs time

    return ecs_fini();
}
```
I haven't tested this code, but I think it should work. Is this what you mean?

**Comment by SanderMertens** [comment]
@xgalaxy I'm closing this issue, feel free to reopen if you want to discuss further!
