### ISSUE TITLE
Rare crash when explorer is attached while stopping world

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#570]
Occasionally when stopping the world an access violation happens when tearing down the http server. I had a query of `FAttributeValue(_X, ChildOf)` entered into the explorer.

More frame info from `request_free`
![image](https://user-images.githubusercontent.com/74724040/145244355-cf0c5179-4b94-4c49-b676-a1884d1a774f.png)

Log
```
Flushing World Nuke <-- me deleting all non important looking entities 
Flecs.Debug_0[34406] http: shutting down server thread 
```

```
static
void request_free(ecs_http_request_impl_t *req) {
    ecs_os_free(req->res);
    flecs_sparse_remove(req->pub.conn->server->requests, req->pub.id);
}
```

where `req->pub.conn->server == NULL`

stack
```
request_free() flecs.c:33730
ecs_http_server_stop() flecs.c:34424
ecs_http_server_fini() flecs.c:34371
EcsRest_dtor() flecs.c:23604
flecs_table_delete() flecs.c:19226
delete_entity() flecs.c:4738
ecs_delete() flecs.c:6498
flecs_defer_flush() flecs.c:7770
ecs_defer_end() flecs.c:7495 <-- flushing the enqueued deletion of all non important looking entities
```

**Comment by SanderMertens** [comment]
This issue should've been fixed as part of https://github.com/SanderMertens/flecs/commit/69f3eb72413f541f1853cf7a1a86be6b8b33c70d, there was an issue in the Windows implementation of thread_join.
