### ISSUE TITLE
Allow .each to process iter param

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#575]
**Describe the problem you are trying to solve.**
We need a version of `.each` with first argument `entity` replaced by an `iter` that has a `count` of 1.

**Describe the solution you'd like**
See [discord](https://discord.com/channels/633826290415435777/731400638637932604/920130598541082634), basically add `.each` overload that receives `iter` which always has `count` equal to 1.

**Comment by SanderMertens** [comment]
I didn't end up exactly implementing this as I could not think of a way to do so without making the function quite a bit less efficient. The challenge is that to make an iterator return only a single entity, I have to update its value & I have to do this for every entity, vs once per table.

What I will add (as per discord discussion) is a way to access `flecs::iter` from `each`:
```c
q.each([](flecs::iter it, size_t i, Position& p) {
  std::cout << it.entity(i).name() << std::endl;
});
```

**Comment by SanderMertens** [comment]
Fixed!
