### ISSUE TITLE
Using the C interface from C++

### ISSUE THREAD

**Issue by meshula** [SanderMertens/flecs#583]
**Describe the bug**

For the most part, the C interface as published works from C++. My project has a mix of C and C++, and I'd like to be able to use the flecs API consistently in both kinds of source files. The only particular issue I ran into was the use of C named-initializers in flecs' macros. For the most part, it's easy enough to bypass the macros, but I found `ECS_COMPONENT_DEFINE` a bit fussy to bypass, and ended up rewriting the macro without the C style named-initializers. I was thinking it would be nice to make the macro less idiomatically C in favor of C++ portability in this case; e.g.

```c
#define LS_ECS_COMPONENT_DEFINE(world, id)\
{\
    ecs_component_desc_t desc = {};\
    desc.entity.entity = ecs_id(id);\
    desc.entity.name = #id;\
    desc.entity.symbol = #id;\
    desc.size = sizeof(id);\
    ecs_id(id) = ecs_component_init(world, &desc);\
    ecs_assert(ecs_id(id) != 0, ECS_INVALID_PARAMETER, NULL);\
}
```

**Comment by SanderMertens** [comment]
Yup makes sense, I'll have a look at it.

**Comment by meshula** [comment]
Thanks :)

**Comment by aganm** [comment]
The only thing I have against this is people like me who want to use the C API without macros will often look at the code behind the macros as a reference. Said reference will be used as a demonstration of how to use the API cleanly and correctly.
This change would give a bad example of how to use the API in C.

**Comment by codylico** [comment]
Only thing I would recommend, since [struct initializers cannot be empty in C](https://en.cppreference.com/w/c/language/struct_initialization), is to change the third line:
```c
ecs_component_desc_t desc = {};\
```
to the following
```c
ecs_component_desc_t desc = {{0}};\
```

**Comment by meshula** [comment]
Thanks! I missed that in the sketch.

**Comment by SanderMertens** [comment]
@meshula @codylico I just committed a change that should make it possible to use most macro's in C++. Let me know if this works for you!

@aganm I'll make sure to add an example to the repository that shows how to use the API without macro's.

**Comment by meshula** [comment]
That dropped right into my code, I can remove my hacked macros :) Thanks!!
