### ISSUE TITLE
Allow manually managing entity generation

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#587]
**Describe the problem you are trying to solve.**
When doing temporary pools for entity management where we never delete the entities, we need a way to set entity's generation to the desired value to invalidate hanging references to the entity.

**Describe the solution you'd like**
Provide such a function:
```c
void ecs_set_entity_generation(
    ecs_world_t *world,
    ecs_entity_t entity_with_generation) {
    flecs_sparse_set_generation(world->store.entity_index, entity_with_generation);
}
```

**Comment by SanderMertens** [comment]
Merged! Thanks for the PR :)
