### ISSUE TITLE
Improve performance of world retrieval in debug builds

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#589]
**Describe the problem you are trying to solve.**
There is a noticeable **debug build** performance impact of `flecs::entity::world()` and `flecs::iter::world()` calls that would be cool to have less of

_Why this matters_: My debug builds are 8 times slower than release builds, and it becomes hard to target 60 fps with somewhat complex scenes this way. Primary performance impact of debug builds in the profiler is world construction.

Consider this code:
```c
struct FNonVirtual {
    void *World;
    bool Owned;
    FNonVirtual(void *World) : World(World), Owned(false){}
};
uint32 Times = 10000;
flecs::world World;

auto Entity = World.entity();
auto Start = Time::GetClock();
for(uint32 Index = 0; Index < Times; ++Index) {
    (void)Entity.world();
}
auto End = Time::GetClock();
printf("Time to retrieve world (virtual) %u times: %sms", Times, *String::ToString(Time::ClockToTime(End - Start) * 1000, 3));
Start = Time::GetClock();
for(uint32 Index = 0; Index < Times; ++Index) {
    FNonVirtual NonVirtual(World.c_ptr());
}
End = Time::GetClock();
printf("Time to retrieve world %u times: %sms", Times, *String::ToString(Time::ClockToTime(End - Start) * 1000, 3));
```
It outputs this:
```c
Time to retrieve world (virtual) 10000 times: 3.144ms
Time to retrieve world 10000 times: 0.052ms
```
As you can see `.world()` call is 60 times slower than what it would ideally be (just assigning two fields), most probably due to virtual inheritance's vfptr initialization for all the inherited mixins (that's what profiler shows having most of the samples).

**Describe the solution you'd like**
flecs::world wrapper without mixin usage, or mixins without virtual inheritance.

**Comment by SanderMertens** [comment]
Fixed it! https://github.com/SanderMertens/flecs/actions/runs/1665748443

Replaced the mixin implementation with a less template-heavy solution & removed virtual calls from world & entity. Both types are now back to being 16 bytes 🎉
