### ISSUE TITLE
Add Notice to FAQs About Required Static Library Macro

### ISSUE THREAD

**Issue by cjens00** [SanderMertens/flecs#597]
Currently, there is no official documentation explaining the complete process of how to use Flecs as a static library, which requires the use of a macro before including flecs.h, as demonstrated below.

**Before:**
`// #define flecs_STATIC`
`#include <flecs.h>`

The compiler/linker (specifically MSVC in this case) produces errors such as
`1>main.obj : error LNK2019: unresolved external symbol __imp_ecs_os_api referenced in function "public: __cdecl flecs::string::~string(void)" (??1string@flecs@@QEAA@XZ)`

**After:**
`#define flecs_STATIC`
`#include <flecs.h>`

Builds correctly. This was quite the headache and I believe it would be a good thing to add _somewhere_ in the documentation, I was thinking the FAQs section seems most appropriate. e.g., **"I'm trying to use Flecs as a static library in my project and keep getting LNK2019 errors! Why?"**

**Comment by SanderMertens** [comment]
Fixed!
