### ISSUE TITLE
Module links are dead

### ISSUE THREAD

**Issue by RomanZhu** [SanderMertens/flecs#6]
I wanted to look at physics module, but there is 404
Same for others D:

**Comment by SanderMertens** [comment]
Sorry about that! Let me update the links.

Note that I'll need a few more days to update the modules to the latest API, so you won't be able to use most of them yet.

**Comment by SanderMertens** [comment]
Links should work now! (the links were correct, but I still needed to rename the repositories).

**Comment by RomanZhu** [comment]
Yep, they do work
Thanks

**Comment by SanderMertens** [comment]
Modules work again. For example projects that use the modules, see: https://github.com/SanderMertens/flecs/blob/master/README.md#built-with-flecs
