### ISSUE TITLE
Allow for creating/populating table with application buffers

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#60]
Currently it is not possible in Flecs to provide values for entities in bulk. Usecases where data is restored from an external data source therefore require relatively expensive `ecs_set` calls to populate the component data.

To facilitate faster insertion of data a new API call is needed that can create/populate a table with data from buffers provided by the application, so that data can be copied with a memcpy per component.

A code example:

```c
ecs_entity_t entity_buffer = {2000, 3000, 4000, 5000};
Position pos_buf = {{10, 20}, {30, 40}, {50, 60}, {70, 80}};
Velocity vel_buf = {{1, 2}, {3, 4}, {5, 6}, {7, 8}};

ecs_new_w_data(world, &(ecs_table_data_t){
    .row_count = 4, 
    .column_count = 2, 
    .entities = entity_buffer, 
    .components = {ecs_entity(Position), ecs_entity(Velocity)}, 
    .columns = {pos_buf, vel_buf}
});
```

**Comment by ArnCarveris** [comment]
Simplified version of this: https://github.com/SanderMertens/flecs/issues/26 ?

For consistency: 
 - `ecs_set_w_data` - is missing.
 - `ecs_get_data`  - how will look?
