### ISSUE TITLE
Small typo in Manual.md

### ISSUE THREAD

**Issue by jmz-b** [SanderMertens/flecs#604]
I may be misunderstanding, but i think there is a typo on this line of `Manual.md`:

https://github.com/SanderMertens/flecs/blob/ae64dda9155fd2e29fe06f2eb45e59803ffbb1f0/docs/Manual.md?plain=1#L358

I think 

```
Here, `ecs_entity` is a macro that translates the typename of the component to a variable name.
```

should actually read

```
Here, `ecs_id` is a macro that translates the typename of the component to a variable name.
```

Sorry for the issue spam if I have got it wrong

**Comment by SanderMertens** [comment]
Fixed!
