### ISSUE TITLE
ecs_strbuf_ftoa does not handle float state NaN or Inf

### ISSUE THREAD

**Issue by KenthJohan** [SanderMertens/flecs#608]
**Describe the bug**
If a meta component that has float is `NaN` or `Inf` then the REST module will respond with garbage values then JSON will be invalid.
I believe the garbage output come from `ecs_strbuf_ftoa` because it seems it does not handle  `NaN` or `Inf` cases.
https://github.com/SanderMertens/flecs/blob/94fa2086c41787cebaf554616b0dfcab5fc5e23a/src/datastructures/strbuf.c#L28

**Expected behavior**
`ecs_strbuf_ftoa` should be able to set `NaN` or `Inf` in string buffer.
Look at this example which handles such cases:  https://github.com/nothings/stb/blob/af1a5bc352164740c1cc1354942b1c6b72eacb8a/stb_sprintf.h#L1720

**Comment by SanderMertens** [comment]
Fixed!
