### ISSUE TITLE
Multi Thread Crash

### ISSUE THREAD

**Issue by teksoc-1** [SanderMertens/flecs#61]
@SanderMertens Can you please confirm this - when applying multi thread execution via ecs_set_threads(), seeing a crash in ecs_schedule_jobs() from a null dereference of 'table' in line 182. 

Note - not using bake, but rather using ecs_os_set_api() per documentation if not using bake; previously this was working with my set up - thinking this may have been recently introduced in one of the recent fixes? Using the same test code as was previously used for creation/deletion of multiple entities.

**Comment by teksoc-1** [comment]
@SanderMertens actually not sure if the problem was on my end earlier, or you have since made updates again, didn't pay attention to commit history, but after pulling changes on another machine, I can no longer reproduce the issue - just testing '0' signature and .Component signature is working. Again, not sure if you pushed some more updates, or the problem was on my end earlier - my apologies if the later.

**Comment by SanderMertens** [comment]
@teksoc-1 The 2nd issue can be reproduced. Seems to be related to using new_w_count from a worker thread. I think I know how to fix it, but will take a closer look tonight.

**Comment by teksoc-1** [comment]
@SanderMertens Disregard my last, ok, here's the System registration to trigger the crash:

ECS_SYSTEM( world, SomeSystem, EcsOnUpdate, .SomeComponent ) // EcsOnLoad does not trigger it, but that's also not multi threaded right

And then inside SomeSystem() it looks like the following call is  triggering it ( can crash in a couple different places actually, not just the assertion failure )

 ecs_new_w_count( rows->world, SomeComponent, N );

I updated the code posting above to demonstrate this. Hope this helps.

**Comment by teksoc-1** [comment]
@SanderMertens your recent push appears to have resolved this issue, had another fellow teammate confirm as well.

**Comment by SanderMertens** [comment]
Great! Thanks again for reporting the issue(s) :)
