### ISSUE TITLE
Unable to replace memory allocators while keeping the defaults of os_api

### ISSUE THREAD

**Issue by tcdude** [SanderMertens/flecs#611]
**Describe the bug**
I was trying to replace the memory allocators of flecs, but this resulted in a fatal error.

**To Reproduce**
```C
ecs_os_set_api_defaults();
ecs_os_api_t os_api = ecs_os_api;
os_api.malloc_ = my_malloc;
os_api.free_ = my_free;
os_api.calloc_ = my_calloc;
os_api.realloc_ = my_realloc;
ecs_os_set_api(&os_api);

ecs_world_t *w = ecs_init();
```
results in flecs crashing with a fatal error:
```shell
fatal: flecs.c: 27892: assert: ecs_os_has_threading() missing OS API implementation (UNSUPPORTED)
```

**Expected behavior**
I would like to be able to only replace single parts of the `ecs_os_api`, in this case particularly all uses of memory allocation to go through custom allocators.

**Additional context**
flecs version: `commit 665e0d41`
os: `Linux (Manjaro ARM)`
arch: `aarch64`
compiler `gcc (GCC) 10.2.0`

**Comment by SanderMertens** [comment]
I don't think the code in the description will result in the described assert- this only happens when the application calls a function that requires threading (such as `ecs_set_threads`).

Regardless, what happens is that the OS API defaults don't include threading functions, so when you override it with your own callbacks you need to also provide threading functions or they won't be set later on.

This is not really a bug, more an inconvenience that the OS API defaults don't include threading (which didn't use to be part of the core codebase APIs at all).

I'll see if I can improve it so that `ecs_os_set_api_defaults` sets the OS API functions from the `FLECS_OS_API_IMPL` addon (which has threading support) if it is included.

**Comment by tcdude** [comment]
It felt wrong leaving the automatically added bug label on this tbh, because I agree, it really isn't a bug.. I realize that it's an inconvenience, but to be clear, I currently have no code that should enable threading in flecs (no calls to `ecs_set_threads` or similar), at least not intentionally so far, but that assert fires regardless.

I'm currently working on setting the entire `ecs_os_api` with functions from my own API as a workaround for my purposes, but enabling users to replace parts of the os api could be a nice enhancement I guess

**Comment by SanderMertens** [comment]
> I currently have no code that should enable threading in flecs (no calls to ecs_set_threads or similar)
Hm that's not good, can you share the code that reproduced the assert? I tried this which doesn't reproduce:

```c
static
void* my_malloc(ecs_size_t size) {
    return malloc((size_t)size);
}
static
void* my_calloc(ecs_size_t size) {
    return calloc(1, (size_t)size);
}
static
void* my_realloc(void *ptr, ecs_size_t size) {    
    return realloc(ptr, (size_t)size);
}
static
void my_free(void *ptr) {
    free(ptr);
}

int main(void) {
    ecs_os_set_api_defaults();
    ecs_os_api_t os_api = ecs_os_api;
    os_api.malloc_ = my_malloc;
    os_api.free_ = my_free;
    os_api.calloc_ = my_calloc;
    os_api.realloc_ = my_realloc;
    ecs_os_set_api(&os_api);

    ecs_world_t *world = ecs_init();
	return ecs_fini(world);
}
```

**Comment by tcdude** [comment]
Figured out the assert, it's because I had the REST API active, which obviously uses the threading API. when I remove that, the next problem that appears is me not passing in `user_delta_time` when calling the `ecs_progress` function, thus this check fails:

```c
ecs_check(user_delta_time != 0 || ecs_os_has_time(), 
        ECS_MISSING_OS_API, "get_time");```

Which may or may not be intended behavior I guess.

**Comment by SanderMertens** [comment]
Try passing a non-zero value to `ecs_progress`. From the docs:
> When an application passes 0 to delta_time, ecs_progress will automatically
> measure the time passed since the last frame.

> it's because I had the REST API active

Ahh, that makes sense. I'll see what I can do to make this easier to use.

**Comment by tcdude** [comment]
So it's intended behavior, which is enough information. 

For now I simply wrote wrappers for the entire `ecs_os_api` to make it work. I'll stay subscribed to this issue in case you find a way to enable partial replacement of the `ecs_os_api`.

**Comment by SanderMertens** [comment]
Fixed! When `ecs_os_set_api_defaults` is called it will now also initialize from the OS API addon, which means that threading, time management etc should still be available after overriding :)
