### ISSUE TITLE
Make ecs_vector_t private

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#616]
**Describe the problem you are trying to solve.**
I implemented reflection codegen timestamps and now switching to Release does not re-trigger the codegen, but in reality it becomes outdated because flecs layout changes due to `ecs_vector_t`'s layout being dependent on Debug/Release build type

**Describe the solution you'd like**
Making `ecs_vector_t` private would prevent it from being reflected in my codegen, preventing my issue from occurring.

**Comment by SanderMertens** [comment]
Done!
