### ISSUE TITLE
Add flecs::reset that resets per-component static id cache

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#617]
**Describe the problem you are trying to solve.**
When writing and executing tests for flecs worlds with different sets of components within single executable, component id-s get cached and overlap with already existing id-s (different components), resulting in assert triggering:
```c
struct Module1{
    Module1(ecs &ECS) {
        ECS.module<Module1>();
    }
};
struct Module2{
    Module2(ecs &ECS) {
        ECS.module<Module2>();
    }
};
struct Module3{
    Module3(ecs &ECS) {
        ECS.module<Module3>();
    }
};

{
    flecs::world World;
    World.import<Module1>();
    World.import<Module3>();
}
{
    flecs::world World;
    World.import<Module1>();
    World.import<Module2>();
    World.import<Module3>(); // this asserts
}
```

**Describe the solution you'd like**
[As mentioned by @SanderMertens](https://discord.com/channels/633826290415435777/928335218899816458/928502178337927178), add a new function `flecs::reset()` that would reset static id cache of components, so it could be called after `flecs::world` initialization, before importing modules or registering any components.

**Comment by SanderMertens** [comment]
Done!

**Comment by Hexlord** [comment]
Thank you!
