### ISSUE TITLE
Using .expr() on more than one term in the builder replaces previous term

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#622]
**Describe the bug**
When building a rule using `.term().expr()` only the final term is used.

**To Reproduce**
```c++
flecs::world ecs;
ecs.entity("A");
ecs.entity("B");
printf("%s\n",
    ecs.rule_builder()
        .term().expr("A")
        .term().expr("B")
        .build().str().c_str());
```
prints `B`

**Expected behavior**
prints `A, B`

**Comment by SanderMertens** [comment]
This issue is not unique to the rule builder (which shares its implementation with filters & queries) but looks like it's being caused by `.expr()`.

**Comment by SanderMertens** [comment]
The issue turned out to be that the code called `filter_builder::expr` twice. I removed `term_builder::expr` and replaced it with an overload for `term()`:

```c
ecs.rule_builder()
  .term("A")
  .term("B")
  .build()
```

I've also added a check that if`expr()` is called more than once for the same builder, an error is thrown.
