### ISSUE TITLE
Internal Error when building rules by expr

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#623]
**Describe the bug**
The following snippet triggers `fatal: flecs.c: 32447: assert: !term->move INTERNAL_ERROR` from `int finalize_term_var` on `ecs_assert(!term->move, ECS_INTERNAL_ERROR, NULL);`

**To Reproduce**
```
    ecs.entity("A");
    ecs.rule_builder().term("A(_Var)").build();
```

**Comment by SanderMertens** [comment]
Fixed!
