### ISSUE TITLE
`ECS_TARGET_ANDROID` is not defined in Android builds

### ISSUE THREAD

**Issue by tcdude** [SanderMertens/flecs#624]
**Describe the bug**
The `ECS_TARGET_ANDROID` macro doesn't get defined when compiling for Android using the NDK on Linux.

**To Reproduce**
Compile flecs for android using the NDK on a Linux machine (or inside a linux container)

**Expected behavior**
setting the preprocessor macro `ECS_TARGET_ANDROID` properly

**Additional context**
I assume this happens because of the evaluation order of where [the macro is defined](https://github.com/SanderMertens/flecs/blob/25719a4db8bce2c449f95d08e3993c4ed03b80be/include/flecs/private/api_defines.h#L13-L30) , probably hitting the first `#elif` on a Linux machine, even though the target is Android.

**Comment by SanderMertens** [comment]
Fixed! I don't have an Android build running on CI yet so I haven't been able to test it, but if you find that it still doesn't work feel free to reopen the issue.

**Comment by tcdude** [comment]
That has done the trick. Thank you :+1:
