### ISSUE TITLE
world::ensure collides with UE defines

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#628]
The new method `flecs::entity ensure(flecs::entity_t e) const;` clashses with a define in UE4 `#define ensure( ...`

Can a different name be chosen? I doubt I can convince UE to change their define :(

**Comment by SanderMertens** [comment]
> I doubt I can convince UE to change their define :(
It would be a reasonable thing to raise it with them, this is bad practice.

**Comment by SanderMertens** [comment]
Fixed!
