### ISSUE TITLE
Add support in reflection framework for registering types with user-defined offsets

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#629]
When running our application, and connecting the explorer to it, we no longer see the entity details in the inspector. You can see in the attached screenshot that 10906 has a transform, but the inspector shows 10906 as being a component.
![image](https://user-images.githubusercontent.com/74724040/151572092-3708701c-a8ee-4ee9-a674-d649e785a506.png)

**Comment by SanderMertens** [comment]
Fixed!
