### ISSUE TITLE
Assertion when checking for case on instance of prefab with switch

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#639]
**Describe the bug**
The following triggers `ecs_assert(count != 0, ECS_INTERNAL_ERROR, NULL);` from `flecs_table_switch_from_case`

**To Reproduce**
```c++
struct SwitchT { struct Cases1{};};
struct Prefab {};
flecs::world ecs;
ecs.type<SwitchT>()
    .add<SwitchT::Cases1>();

ecs.prefab<Prefab>()
    .add_switch<SwitchT>()
    .add_case<SwitchT::Cases1>();

ecs.entity().is_a<Prefab>().has_case<SwitchT::Cases1>();
```

**Expected behavior**
For `ecs.entity().is_a<Prefab>().has_case<SwitchT::Cases1>();` to return false

**Comment by SanderMertens** [comment]
Fixed!
