### ISSUE TITLE
has(Wildcard) should only match non-pairs

### ISSUE THREAD

**Issue by safasofuoglu** [SanderMertens/flecs#643]
From discord:

safa — Yesterday at 9:17 PM
remove(Wildcard) removes only non-pairs while has(Wildcard) returns true if an entity has only a pair. could we make this consistent?
has(pair(Wildcard, Wildcard)) and remove(pair(Wildcard, Wildcard)) only deal with pairs, intuitively.

Sander — Today at 3:08 PM
You’re right, that is a bit inconsistent
I guess * should only match non pairs 🤔

safa — Today at 3:34 PM
I agree. neither approach is absolutely intuitive, but this way we retain the ability to address non-pairs.

**Comment by SanderMertens** [comment]
Fixed!
