### ISSUE TITLE
observers do not handle OnSet of components on an instance of a prefab that are added with .mut(world)

### ISSUE THREAD

**Issue by Lost-Boy-Jason** [SanderMertens/flecs#645]
**Describe the bug**
Observers will not handle observing OnSet on instances of components that are set on the prefab of an instance by calling .mut(world) on the prefab and setting the instance.

**To Reproduce**
1. make a prefab that has one component set when initialized
2. modify the prefab by setting another component by calling .mut(world).set
3. make two observers for instances of the prefab, one for each component
4. instance the prefab
5. the OnSet observer for the first component will trigger, the OnSet observer for the second component will not.

**Expected behavior**
the OnSet observer for each component will trigger, as both components are set on instancing

**Additional context**
repro in text file
[OnSetBug.txt](https://github.com/SanderMertens/flecs/files/8018404/OnSetBug.txt)

**Comment by SanderMertens** [comment]
Fixed!
