### ISSUE TITLE
Allow for custom system phases and system pipelines

### ISSUE THREAD

**Issue by ArnCarveris** [SanderMertens/flecs#65]
Currently the Flecs API defines a fixed set of phases (`EcsPreUpdate`, `EcsOnUpdate`, etc), to which systems can be assigned. These phases are designed to be generic enough to support most scenarios, however if an application needs more (or fewer) phases, the only thing applications can do to day is revert to manual systems. When and how manual systems are ran is fully up to the application, which means that there isn't much Flecs can do to ensure interoperability between such systems.

Additionally, the semantics associated with a phase might influence which features of Flecs are used (threading, staging etc). The current phases may be doing too little or too much for an application.

To address this problem, a user should be able to define custom phases, arrange them in a custom order, and assign custom semantics to each custom phase. The terminology used is:

- Phase: an ordered set of systems
- Pipeline: an ordered set of phases, annotated with additional semantics

Custom phases/pipelines should be functionally equivalent to the builtin phases in Flecs, so that there are no adverse effects to using custom phases vs. the builtin Flecs phases. An application should be able to define/run multiple pipelines in a single application.

**Comment by SanderMertens** [comment]
API proposal by @ArnCarveris 

---
Current API draft for `ecs_pipeline_t`
---
```c
// Creates pipeline object
//
ecs_entity_t ecs_new_pipeline(world, ecs_pipeline_t* pipeline, const char* id);

// Deletes given pipeline
//
ecs_delete_pipeline(ecs_world_t* world, ecs_entity_t pipeline);

// Runs given pipeline with given delta time and optional param
//
ecs_run_pipeline(ecs_world_t* world, ecs_entity_t pipeline, float delta_time,
    void *param);
```
---
Example
---
```c
ecs_entity_t pipeline = ecs_new_pipeline(world, &(ecs_pipeline_t){
    .phases = {Tag_1, Tag_2, Tag_3},
    .bind_thread = {{-1}, {-1}, {0}},
    .stage = {true, true, false}
}, "Pipeline");

ECS_SYSTEM(world, Move, Tag_2, Position, Velocity);

ecs_run_pipeline(world, pipeline, delta_time, user_data);

ecs_delete_pipeline(world, pipeline);
```
---
Notes:
 - Need to reimplement phases by using the pipeline to avoid code duplication.
 - This will allow users to simplify the implementation of custom/complex simulation with explicit multithreading(task graph).
 - There must be able to run pipeline within any system.
