### ISSUE TITLE
`ecs_filter_str` omits the `[filter]` modifier for all filtered terms after it

### ISSUE THREAD

**Issue by prime31** [SanderMertens/flecs#650]
The same query with the terms in a different order result in different strings returned by `ecs_filter_str`. The first example output is when the `or` term comes _before_ the `filtered` `PopTart` term.
`[in] Velocity, ?Acceleration, ?Player, ?Enemy, [filter] Player || Enemy, PopTart`

The output when the `or` term comes _after_ the `filtered` `PopTart` term is correct.
`[in] Velocity, ?Acceleration, ?Player, ?Enemy, [filter] PopTart, [filter] Player || Enemy`

**Expected behavior**
`ecs_filter_str` should report all inouts correctly regardless of the term order in the query.

**Comment by prime31** [comment]
Tiny bit more info: this only affects the next term after the `filtered or`. Two terms later it again reports correctly the `[filter]` tag.

**Comment by SanderMertens** [comment]
Fixed!
