### ISSUE TITLE
v3 set name in multi-threaded mode asserts

### ISSUE THREAD

**Issue by wobes1** [SanderMertens/flecs#659]
flecs.c: 31495: assert: ecs_get_stage_count(world) <= 1 INVALID_WHILE_ITERATING in the latest flecs master? Here is the callstack. It crashes on creating entity with name.

![image](https://user-images.githubusercontent.com/24993673/155902927-0be30204-6563-4a61-91e7-b47e14acc089.png)

Possible solution:
![image](https://user-images.githubusercontent.com/24993673/155902940-6f1c11a5-03bf-4c27-a0c7-8ea811a6615f.png)

Related to: "a fix that prevents the creation of multiple entities with the same name while staged."

Thank you.

**Comment by SanderMertens** [comment]
Fixed!
