### ISSUE TITLE
query_builder leak memory

### ISSUE THREAD

**Issue by nneesshh** [SanderMertens/flecs#670]
**Describe the bug**
My Code is just like
"
for (int i=0; i<100000000;++i)
{
    auto q= gWorld.query_builder<CompTest>().build;
    q.each([](flecs::entity e, CompTest& test) {
    });
    q.destruct();
}
"

The memory is always increasing even I haven't any entity in the world yet.

**Expected behavior**
the builder release it is memory when destruct is called,
 or reused the memory to limit the memory increase upper bound

somebody may say construct builder and keep it until the program end, but it is not a elegant design.

**Comment by SanderMertens** [comment]
I tried to reproduce with your code but it doesn't leak!

It looks like some bits are missing in your code (for example, `each` has `CompTest` but it doesn't show up in the builder). Can you ensure that your reproducer compiles and reproduces the issue?

**Comment by nneesshh** [comment]
thank you for your reply, but nothing is special in the CompTest, just some int32_t, float, bool,etc...

the leak memory is allocated by "ecs_query_init" --> process_signature --> register_monitors -> flecs_monitor_register --> _ecs_vector_add --> resize

the leak memory would double time by time

**Comment by SanderMertens** [comment]
I got it reproduced! Didn't see the leaks before because the world cleans them up. Working on a fix.

**Comment by nneesshh** [comment]
thanks, I just think how to explain it. I work in a lan, it is hard to copy code out to the wan. Thank you for you great works.

**Comment by SanderMertens** [comment]
Fixed!
