### ISSUE TITLE
Modified asserts after clearing arbitrary entity 

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#671]
**Describe the bug**
There is a valid scenario where we may call `modified` after `clear`, but it asserts.
The scenario is manually managed pool of recycled entities, where recycling happens in multi_threaded systems without sync-points, through atomic integer.

**To Reproduce**
```c
flecs::world ECS;
ECS.set_threads(8);

struct TemporaryText{
    int Value;
};
struct Lifespan{
    int Value;
};
struct DebugTextBeacon{
    int Value;
};

std::vector<entity> TemporaryTextEntities;
for(uint32 Index = 0; Index < 160; ++Index) {
    TemporaryTextEntities.push_back(ECS.entity(1500 + Index * 100).add<TemporaryText>().add<Lifespan>());
}
for(uint32 Index = 0; Index < 20; ++Index) {
    ECS.entity().add<DebugTextBeacon>();
}

ECS.system<Lifespan>().multi_threaded().each([&](entity E, Lifespan &lifespan){
    std::this_thread::sleep_for(std::chrono::milliseconds(1 + E.id() / 100));
    lifespan.Value -= 1;
    E.modified<Lifespan>();
    // ...
});

std::atomic<uint32> Counter = 0;

ECS.system<DebugTextBeacon>().multi_threaded().each([&](entity E, DebugTextBeacon &) {
    //            std::this_thread::sleep_for(std::chrono::milliseconds(10));
    auto Index = Counter.fetch_add(1, std::memory_order::relaxed);
    auto NewE = TemporaryTextEntities[Index % 160].mut(E);
    NewE.clear();
    NewE.add<TemporaryText>();
});

ECS.progress();
ECS.progress();
```

**Expected behavior**
`modified` should early-out instead of asserting if the target component is missing.

**Comment by Hexlord** [comment]
Actually I thought about this a little bit more and don't like what I am doing at all, I should not recycle arbitrary entities - only the ones iterated by current stage, because it could have too many unpredictable consequences (like events being lost), so feel free to close this one, I think current behavior is the most sane approach long-term. 

As for my code base - I will have to avoid temporary entity overflow some other way - not by recycling them arbitrarily.

**Comment by SanderMertens** [comment]
Fixed!
