### ISSUE TITLE
Rare deadlock on the last worker thread

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#673]
**Describe the bug**
Sometimes during world destruction one of the worker threads never joins - it just hangs on worker_cond.

**To Reproduce**
```c
for(uint32 Index = 0; Index < 10000; ++Index) {
    flecs::world ECS;
    ECS.set_threads(8);
    ECS.system("No Staging System").no_staging().iter([](iter &Iter) {
        auto ECS = Iter.world();
        ECS.defer_end();
        assert(!ECS.is_deferred());
        ECS.defer_begin();
    });
    ECS.progress();
    ECS.progress();
    printf("%u\n", Index);
}
```
This never reaches 10000, it deadlocks beforehand for me.

I am on Linux Mint 20.2 Cinnamon Intel© Xeon© CPU E3-1231 v3 @ 3.40GHz × 4

**Comment by Hexlord** [comment]
Submitted repro

**Comment by SanderMertens** [comment]
I tried running the code and it doesn't repro for me, are you able to share more information, for example stack traces of the deadlock?

**Comment by Hexlord** [comment]
Can't repro on latest master as well, feel free to close

**Comment by SanderMertens** [comment]
Sounds good, I'll keep an eye out for any hanging tests
