### ISSUE TITLE
ecs_set_api_defaults() crash

### ISSUE THREAD

**Issue by teksoc-1** [SanderMertens/flecs#68]
@SanderMertens Have been meaning to mention this for awhile now, and just chalked it up to something in our environment set up, but when writing to the `_ecs_os_api` pointer to the  `ecs_os_api` global data structure declared with the `const` qualifier, it crashes inside `ecs_set_api_defaults()` on macOS (clang compiler). The pointer assignment naturally bypasses the compiler checks, but at run time crashes on the fact that we are modifying a data structure with the `const` qualifier. Not sure if you are able to reproduce, if there is some compiler/platform specific implementation with your set up that is not triggering this condition?

**Comment by SanderMertens** [comment]
@teksoc-1 I am compiling and running on macOS with clang as well. Can you post a code snippet that reproduces the issue? I don't think it is related to the variable being `const`.

**Comment by teksoc-1** [comment]
@SanderMertens hmm, interesting ... so we have an Xcode build configuration for flecs as a static lib, and link against it. We crash up front on `ecs_init()` ( with the underlying stack trace to `ecs_os_setapi_defaults()` ), line 243 `_ecs_os_api->malloc = malloc;`. Our work around to date has just been to remove the `const` qualifier in the respective .h and .c files.

**Comment by SanderMertens** [comment]
Hmm, sounds like the variable gets put in the data segment which is readonly. I've seen issues with this before, let me ponder on a clean solution. I'd like to keep the publicly exposed declaration const but readable so that the only way to modify it is through the functions.

**Comment by teksoc-1** [comment]
@SanderMertens Concur, that's exactly what I'm seeing in accordance with the specification as I understand it - lands inside (__TEXT,__const) section as RO ...

**Comment by SanderMertens** [comment]
I found no way to reliably address this problem with a const still in place in the header file, so I decided to just remove the const. It's the most portable solution- I think I could find a hacky way around it, but I'm sure that would break on some other platform.

Pushed the code, let me know if you're still seeing the issue!

**Comment by teksoc-1** [comment]
@SanderMertens Sorry was out of pocket there for awhile - just tested - works here.

**Comment by SanderMertens** [comment]
Great! I'll close the issue.
