### ISSUE TITLE
Conflict with "json_?" and other libraries

### ISSUE THREAD

**Issue by hbiblia** [SanderMertens/flecs#683]
Bug or Problem:

I was trying to add a JSON library and it name conflicts with flecs functions to work with JSON.

```
multiple definition of `json_number';  ..ThirdParty/flecs/flecs.c.obj:flecs.c:(.text+0x52eb1): first defined here
multiple definition of `json_string';  ..ThirdParty/flecs/flecs.c.obj:flecs.c:(.text+0x52eb1): first defined here
```

I propose changing these functions to "ecs_json_" as suggested by user @randy on discord or "json_flecs_" "jsonf_".

**Comment by SanderMertens** [comment]
Fixed!
