### ISSUE TITLE
Add support for enums with custom integer types

### ISSUE THREAD

**Issue by BHolman-LBI** [SanderMertens/flecs#696]
**Describe the bug**
Unsure if this is a bug or a feature request:

The following snippet compiles and triggers a heap corruption runtime check on MSVC
```c++
enum class ETest : uint8_t
{
    A, B
};
int main()
{
    
    flecs::world ecs;

    ecs.component<ETest>();
    ecs.entity().set<ETest>(1);
    return 0;
}
```

**Expected behavior**
I don't think the above should be allowed to compile?

**Comment by SanderMertens** [comment]
Updated the description, this is not currently supported. Will look into why it crashes though, that's not nice.

**Comment by SanderMertens** [comment]
Added an assert that checks if the enum is of the correct size.
