### ISSUE TITLE
compiler warnings with Visual Studio 2017

### ISSUE THREAD

**Issue by mattiasljungstrom** [SanderMertens/flecs#70]
I've been evaluating this library as one possible solution for a project, but I noticed there are quite a lot of warnings when compiling with visual studio 2017. 

Examples:
flecs\src\column_system.c(281): warning C4146: unary minus operator applied to unsigned type, result still unsigned
flecs\src\column_system.c(934): warning C4244: '=': conversion from 'uint64_t' to 'uint32_t', possible loss of data
flecs\src\column_system.c(1001): warning C4244: '+=': conversion from 'double' to 'float', possible loss of data
flecs\src\entity.c(1050): warning C4018: '<': signed/unsigned mismatch
flecs\src\entity.c(300): warning C4090: 'function': different 'const' qualifiers
flecs\src\type.c(1068): warning C4244: 'initializing': conversion from 'ecs_entity_t' to 'int', possible loss of data
etc...

Would you be interested in a push request if I keep using this library?

**Comment by SanderMertens** [comment]
@mattiasljungstrom Sure thing! I just built Flecs with pedantic warnings on MacOS and fixed a few warnings that showed up there, but it seems like msvc is catching more. If you can do a PR I'll definitely merge it.

**Comment by SanderMertens** [comment]
I've recently fixed a lot of warnings in MSVC related to type conversions and "unsafe" functions, so closing this issue. If you are still seeing issues with MSVC, feel free to reopen.
