### ISSUE TITLE
bad return value in C++ pair

### ISSUE THREAD

**Issue by elaucoin** [SanderMertens/flecs#703]
I'm afraid that `pair::operator*`  (line 14218 of flecs.h) does not return the right value.

I think that :

```
type& operator*() {
    return &ref_;
}
```

should be replaced by :

```
type& operator*() {
    return ref_;
}
```

since `ref_` is already a `type&`.

Best regards,
Eli

**Comment by SanderMertens** [comment]
Yep I think you're correct. The `&` would turn the value into a pointer, which should throw a compiler error. Looks like it isn't covered by the tests yet, I'll make sure to add one.

**Comment by SanderMertens** [comment]
Fixed!
