### ISSUE TITLE
can not declare flecs::observer

### ISSUE THREAD

**Issue by eziasolsky** [SanderMertens/flecs#707]
**Describe the problem you are trying to solve.**
I am migrating from v2 to v3 and trying to declare a member variable "flecs::observer xxx; ", but there is no default constructor of observer, and failed to compile.

**Describe the solution you'd like**
add the constructor back.
`
    explicit observer() 
        : entity() { }
`

**Comment by SanderMertens** [comment]
Can you share the code that causes the compiler error and the specific error you're getting? I just tried this, which works for me:
```c
    flecs::observer o;

    o = world.observer<TagA>()
        .event(flecs::OnAdd)
        .each([&](flecs::entity e, TagA) {
        });
```

The observer class has this statement (https://github.com/SanderMertens/flecs/blob/master/include/flecs/addons/cpp/mixins/observer/impl.hpp#L10):
```c
using entity::entity;
```
which inherits the default constructor from `flecs::entity`.

**Comment by SanderMertens** [comment]
Ah, looks like this is an msvc only problem: https://github.com/SanderMertens/flecs/runs/6040391354?check_suite_focus=true

**Comment by SanderMertens** [comment]
Fixed!

**Comment by eziasolsky** [comment]
cheers :)
