### ISSUE TITLE
Implementing request/reply in ECS

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#71]
From @teksoc-1's comment in #21 :

> @SanderMertens Do you have any particular suggestions for implementing client/server patterns in Flecs i.e. Module X provides some service say for example HandleRequestSystem(Request) where the implementation may either add a Response component to entities, or generate new entities with Response components - service side implementation is really orthogonal to the 'problem'. This 'problem' that we see is ensuring the correct client (system) only receives the appropriate filtered Responses for the Requests that it made - doesn't care about any other Responses to Requests it didn't generate. Our naive approach to this problem is to leverage unique Tags that we would add to entities, and thus filtering for MyResponseSystem(Response, MyUniqueTag) ... is there a better way to do this, are we not thinking about this the ECS way, etc?

**Comment by SanderMertens** [comment]
Let's see I understand you correctly; you have a module with one system that can issue a request (`SendRequestSystem`), and with another system that is listening for requests (`HandleRequestSystem`) and another system that listens for replies (`HandleReplySystem`), where the latter is only interested in replies to requests sent by the `SendRequestSystem`.

If this is the case, then I think the approach you suggested works. You add a tag unique to the `SendRequestSystem` - `HandleReplySystem` combination to the entity with the request component, and in the `HandleReplySystem` you subscribe for this tag.

It does sound a bit contrived, but I can't say based on this information whether it's the right or wrong approach. Other than that, I don't see anything inherently wrong with it.

**Comment by teksoc-1** [comment]
@SanderMertens Yes, you have problem framed the issue well. And yes, that is the approach we are taking - I knew a callback like implementation for the response was not really ECSy ... so went with this ... I guess I wasn't necessarily happy with the solution, so was just kind of thinking out loud I guess, trying to reach for inspiration/alternatives and/or affirmation that we weren't doing anything inherently wrong.

**Comment by SanderMertens** [comment]
@teksoc-1 I'm closing this question, feel free to reopen if you want to discuss further!
