### ISSUE TITLE
std::vector and other STL types are not supported by reflection 

### ISSUE THREAD

**Issue by bbdb68** [SanderMertens/flecs#712]
try to create a Component with an std::vector<double> member
```
struct Component
 {
      std::vector<double> data;
 };
```
registering the meta api works fine, but a runtime you get

```
error: flecs.c: 22716: missing EcsMetaType for type std.vector<double,class std::allocator<double> >'
```

**Comment by SanderMertens** [comment]
Serialization support is implemented by https://github.com/SanderMertens/flecs/pull/924

**Comment by SanderMertens** [comment]
Deserialization is implemented by https://github.com/SanderMertens/flecs/pull/925

Done!
