### ISSUE TITLE
Quickstart lines 425 and 426 have errors

### ISSUE THREAD

**Issue by cptnapalm** [SanderMertens/flecs#724]
According to my compiler, ecs_vector_first(vector, T), but:
425: ecs_id_t *ids = ecs_vector_first(type);

ecs_vector_count() takes a const ecs_vector_t *, but type is a const ecs_type_t *.
426: for (int i = 0; i < ecs_vector_count(type; i ++) {

Presumably it should be:
for (int i = 0; ecs_vector_count(ecs_vector_t *something); i++) {

**Comment by SanderMertens** [comment]
Nice catch, fixed!
