### ISSUE TITLE
Faster table sorting for queries

### ISSUE THREAD

**Issue by bazhenovc** [SanderMertens/flecs#731]
# The problem
Following our Discord discussion:

Currently `ecs_order_by_action_t` is defined as a function pointer that operates on two individual elements, then there is a `sort_tables()` function that sorts the data and calls this function by pointer.

In this case the compiler cannot inline the comparator function and will always be calling it by pointer, so it's basically an equivalent of a C++ virtual function call for each element - it is very slow.

# Proposed solution
Define `ecs_order_by_action_t` as a function pointer that sorts the entire table, then define `FLECS_DECLARE_ORDER_BY_ACTION` helper macro that produces this sorting function. The macro should be similar to how `datastructures/qsort` works.

For example:

```c
FLECS_DECLARE_ORDER_BY_ACTION(MyCustomOrderingFunction, CompareTwoElements);

ecs_query_desc_t desc = {};
desc.order_by = MyCustomOrderingFunction;
```

## Helper macro
Macro `FLECS_DECLARE_ORDER_BY_ACTION` will define the entire sorting function named `MyCustomOrderingFunction` that will call `CompareTwoElements` directly, so that the compiler will see all the definitions and properly optimize and inline everything.

## Sort function signature

There currently is a minor issue with `sort_tables()` - it accesses the members of `ecs_table_t`, which is an internal opaque type. Proposed solution: define `ecs_order_by_action_t` like this and expose `ecs_column_t` to the user:

```c
void (*ecs_order_by_action_t)(
  int32_t count,                // number of elements to sort
  ecs_entity_t *entities,       // entity ids
  ecs_column_t *columns,        // component arrays
  ecs_type_info_t **type_info,  // array with type info structs
  int32_t column_count,         // total number of columns
  int32_t column_to_sort)       // column with component to sort
```

The signature should be completely irrelevant for the user because the helper macro will take care of it. However it will have binary compatibility implications.

## C++ bindings

The C++ bindings should use a templated version of `ecs_order_by_action_t`. Comparing two elements can be implemented either using `std::less` that the user will provide specializations for the component type or by passing a sorting closure by value.

With C++ bindings it is currently unclear how to handle swapping and iteration of the arrays, the C interface needs to be finalized before implementing it. I don't see any fundamental issues there, will figure it out once I get there.

**Comment by SanderMertens** [comment]
Looks good! Few thoughts:

- Can we initially implement this alongside the existing implementation, perhaps by providing an additional `order_by_table` function? That would make it possible to merge this faster without having to also do a port to the C++ API.

- I think I prefer  using `COMPARE` for the macro name. "order by" is how it relates to the query, whereas the function is a type-specific comparator (on par with constructors, destructors etc).

- I'd like to reuse the existing API conventions for type-specific convenience macro's, just as what happens for `ECS_CTOR`, `ECS_DTOR` & co. That would turn it into:

```c
ECS_COMPARE(Position, CompareTwoElements)

desc.order_by_table = ecs_compare(Position)
```

Thanks for the writeup! Look forward to being able to use it :)

**Comment by bazhenovc** [comment]
Makes sense, I'll do all 3 suggestions 🙂

**Comment by SanderMertens** [comment]
Merged!
