### ISSUE TITLE
Get component by base type or without knowing component's type

### ISSUE THREAD

**Issue by MohammadMDSA** [SanderMertens/flecs#745]
Hi! I am writing my game engine and I got into a problem with Flecs.
Each one of my components are inherited from a base type so they inherite `update`, `serialize`, `render`, and many other methods to implement. I need to call all components' `update` function every frame and there are a lot of other cases in which, I know a component has a specific method and I need to call it but I have no idea about the component type. I can't hardcode any component type because there will be a lot of user defined component types that I have no idea of. I also can't bind my methods to the library and have the library calling them every frame because in some cases like rendering, `render` method of different components of different entities will be called from my custum threads, so I need them to be explicitly called by my own program.

Is there any way so I can call those methods without knowing component types? Please help becase if there is no way, I may need to use another library. Also if you feel my design is wrong and have a better idea, I'll be super glad to hear it!

**Comment by SanderMertens** [comment]
Yep you can. The trick is that in Flecs components are _entities_, which means you can add components to components. Take this example:

```c
// add Serializable to Position component
world.component<Position>()
  .add<Serializable>();
```

You can then create a normal query for `Serializable`, and iterate entities like this:
```c
auto q = world.query<Serializable>();

q.each([&](flecs::entity component, Serializable) {
  cout << component.name() << std::endl; // prints Position

  // iterate all entities with the component
  world.each(component, [](flecs::entity e) {
  });
});
```

Component inheritance itself is also supported:
```c
world.component<Position>().is_a<Serializable>();
```

You can also query for the entities with serializable components directly:
https://www.flecs.dev/explorer/?q=FQAAADQkQywgU2VyaWFsaXphYmxlKCRDKQA-&p=ywAAAD91c2luZyBmbGVjcy5tZXRhCgovLyBzZXJpYWxpemFibB9lClN0cnVjdChQb3NpdGlvbikgewogIHggPSB7ZjMyfSALAHngAAsAfWA9Am5vdOAMQQNNYXNzgD0EdmFsdWXgAzXAXCATAFPgA3sBCmVgbeACHgZ7MTAsIDIwQHdATwsgPSB7MTAwfQp9CgA-

**Comment by MohammadMDSA** [comment]
Since I need to call component's methods, just having representation of the component with `flecs::entity` doesn't work for me and I need component's original type.
This is what I came up with based on your suggestions: Lets say we have base component type `A` and two components `B` and `C` which inherite from `A` (C++ inheritance, not flecs). Since those methods I need from `B` and `C` are inherited from `A`, even if all components were represented by type 'A', would be just fine. So I need to query all components and get them with type `A`. Based on what you said, if beside class type `B` and `C` inheritance from `A` I also make component `B` and `C`, `is_a<A>()` I can query for `A` and have all my components with their parent's type. This solves everything except one problem:
`B` and `C` already have `A`'s properties in their memory range by C++ inheritance. Applying flecs inheritane will add `A`'s property to `B` and `C`'s flecs' component. So `B` and `C` will have `A`'s data twice by C++ inheritance and flecs'. This is a serious memory issue and it'll get even worse when inheritance tree's hight gets longer.
Do you have any idea how can I overcome this?

**Comment by SanderMertens** [comment]
> Applying flecs inheritane will add A's property to B and C's flecs' component

That is not what happens. When you do `world.component<B>().is_a<A>()` flecs doesn't increase the component size of `B`, it always takes the actual size of the type. So if you do this, it should work:

```c
struct A { int foo; };
struct B { int bar; };

world.component<A>();
world.component<B>().is_a<>A();
```

**Comment by SanderMertens** [comment]
Closing the issue for now, feel free to reopen if you have follow up questions!
