### ISSUE TITLE
Use singletons with .each

### ISSUE THREAD

**Issue by SK83RJOSH** [SanderMertens/flecs#747]
**Describe the problem you are trying to solve.**
I was hoping to be able to use singleton data with `.each`

**Describe the solution you'd like**
I made the assumption that I could declare a system like so:

```cpp
void DoThings(const AppData&, const InstancedData&);

ecs.system<const AppData, const InstancedData>("DoThings")
   .term<AppData>().singleton()
   .each(DoThing),
```

Which ended up resulting in me trying to debug by this system was deactivated for a number of hours. I now see that there appears to be no way to use singleton data in an ergonomic way. Are there any plans to implement something like this? If not can you point me to some examples of how to implement this without too much iter boilerplate? 

Thanks in advance!

**Comment by SanderMertens** [comment]
You can do this with the current API, but instead of using `term` (which adds another term to the query) use `arg` which lets you change the parameters of an existing term:

```c
ecs.system<const AppData, const InstancedData>("DoThings")
   .arg(1).singleton()
   .each(DoThing),
```

**Comment by SK83RJOSH** [comment]
Aha! Thank you so much 😄

**Comment by SanderMertens** [comment]
Yw!
