### ISSUE TITLE
Explorer leaks memory

### ISSUE THREAD

**Issue by dsrour** [SanderMertens/flecs#751]
**Describe the bug**
As soon as explorer is connected, the client application will start leaking memory.

**To Reproduce**
1. Have a memory leak detector activated
2. Enable REST
3. Connect explorer with app
4. Shutdown client and notice that there are a bunch of leaks originating from flecs_iter_init and ecs_rule_iter

**Expected behavior**
No leaks.

**Additional context**
Issue seems to be coming from https://github.com/SanderMertens/flecs/blob/b0b6bb7892eaffa36555c616893f1c9891998600/src/addons/rest.c#L226  
Commenting out line 226, 227, 228 results in no leaks but obviously that isn't the proper fix.  It was only used to figure out where the leaks originate from.  I'll keep digging on my side but would be good to get some help resolving this.  

Thank you.

**Comment by SanderMertens** [comment]
Can you share more details about the leaks you're getting and if/what kind of query you're running in the explorer? I ran an application with asan and the explorer enabled, but am not seeing any leaks.

**Comment by dsrour** [comment]
I created a minimal repro console app in VS2017 using latest master.
It seems the issue can only be reproduced if you have created at least ~997 entities (not sure how that number is special).
The app creates 1K entities... but changing that to anything < 997 doesn't result in leaks.

The app has the CRT lib enabled to detect mem leaks.

[LeakRepro.zip](https://github.com/SanderMertens/flecs/files/8970899/LeakRepro.zip)


Leaks originate from ecs_rule_iter and flecs_iter_init.

Thanks!

**Comment by SanderMertens** [comment]
You were right, it was the page iterator not freeing up iterator resources when it hit the limit. Just checked in a fix!

**Comment by dsrour** [comment]
Thank you so much for the fix and for the efforts you put into this awesome library you've masterfully created!  I appreciate it.
