### ISSUE TITLE
invalid parameters on run

### ISSUE THREAD

**Issue by bshea5** [SanderMertens/flecs#76]
**Describe the bug**
Following the tutorials for flecs, I installed bake and flecs to my machine. Running with just flecs runs fine. However, when I install the repos required for the dashboard and create & run a new app, I recieve the following error:

![image](https://user-images.githubusercontent.com/3984775/66249810-ef6c4a80-e6ed-11e9-8899-533eabd45443.png)

**Expected behavior**
Program to run with no errors and the dashboard to be available on port 9090.

**Additional context**
OS: Windows 10 64 bit

**Comment by SanderMertens** [comment]
@bshea5 Does this only happen on Windows? I think you mentioned you were trying this out on multiple machines.

**Comment by bshea5** [comment]
Just my Windows machine. Runs fine on macOS.

**Comment by SanderMertens** [comment]
Ok, I'll try to reproduce it. It will take me a few days before I have access to a Windows machine.

**Comment by bshea5** [comment]
Thanks for investigating!

**Comment by SanderMertens** [comment]
I'm closing this issue as a lot has changed, and the current admin dashboard is being deprecated in favor of flecs.dash
