### ISSUE TITLE
Ability to Serialize / Deserialize a world snapshot to JSON

### ISSUE THREAD

**Issue by eanticev** [SanderMertens/flecs#762]
**Describe the problem you are trying to solve.**
USER STORY: As a developer trying to implement a snapshot save/restore system that is compatible with a REST API, I want to serialize a world snapshot to JSON and read it back.

**Describe the solution you'd like**
From Discord: It wouldn't be hard to extend the current ecs_iter_to_json to serialize all components vs. just the components a query asked for. That would make it possible to create an iterator from the snapshot, then serialize that iterator to json.

I'm unsure how to handle the de-serialization case.

This is sort of a duplicate of: https://github.com/SanderMertens/flecs/issues/114

**Comment by SanderMertens** [comment]
Feature has been implemented more than a year ago :) Forgot to close the issue.
