### ISSUE TITLE
Union Relationship Ref to Wildcard (Edge Case)

### ISSUE THREAD

**Issue by Epsola** [SanderMertens/flecs#765]
**Describe the bug**
Creating this as a bug so that it doesn't get forgotten. There is an issue with queries and union relationship enums. See chat for details...

**To Reproduce**
[See discord discussion](https://discord.com/channels/633826290415435777/991567648116719657/993698239201169439)

**Comment by SanderMertens** [comment]
Bit more context (before the github thread expires):

It looks like there is an issue with queries for union relationships, where the union relationship is resolved as a reference (from another entity, like a prefab or parent).

The issue shows up as a query attempting to resolve a wildcard id on a reference, which fails.

**Comment by KenthJohan** [comment]
A related issue when a query term uses parent union:
```c
ECS_ENTITY(world, Movement, EcsUnion);
ECS_TAG(world, Walking);
ECS_TAG(world, Running);
ecs_query_t *q = ecs_query_init(world, &(ecs_query_desc_t){
.filter.terms = {{.id = ecs_pair(Movement, Running), .src.trav = EcsChildOf, .src.flags = EcsUp}}
});
ecs_entity_t e0 = ecs_new_entity(world, "e0");
ecs_add_pair(world, e0, Movement, Running);
ecs_entity_t e1 = ecs_new_entity(world, "e1");
ecs_add_pair(world, e1, EcsChildOf, e0);
```
Gives: `fatal: flecs.c: 8122: assert: ecs_id_is_valid(world, id) INVALID_PARAMETER`

**Comment by SanderMertens** [comment]
Closing this issue, as in v4 union relationships are no longer handled by cached queries.
