### ISSUE TITLE
(Explorer) Union Component displaying it's current type/val

### ISSUE THREAD

**Issue by Epsola** [SanderMertens/flecs#766]
**Describe the problem you are trying to solve.**
With the old switch/case components we could see the current value of it in explorer, when it was replaced with Union components, this feature was lost. Creating this issue so it's not forgotten.

For reference:
[Discord Discussion](https://discord.com/channels/633826290415435777/731400638637932604/983197443061583902)

**Comment by SanderMertens** [comment]
Fixed!
