### ISSUE TITLE
Enable a system to listen to an event such like a defered observer until its phase

### ISSUE THREAD

**Issue by happyxianyu** [SanderMertens/flecs#768]
**Describe the problem you are trying to solve.**
To implement a state machine, we often need to track changes. It will be much easier to implement it If flecs supports to define a system which executes conditionally depending on one or more components changed during each frame. It can improve performance by excluding unnecessary execution of a system. And it can also improve performance of delayed observer because it allows bulk process of modified components like a system.

**Describe the solution you'd like**

To implement this, we need delayed bulk operation to notify events by a system's iter argument. Flecs is responsible to record the delayed bulk event notifications. Any notifed events should be observed in current and subsequent phases. At end of each phase, execute delayed observer according to the recorded events. And by the end of a frame (before end of the function progress), clear all event records.

Here's a example code for demostration.
```
// system
void update_origin(ecs_iter_t *iter) {
    notify(iter, Origin, EcsOnSet);  
   // This calling marks all Origin component of entities passed by iter are modifed. 
   // The operation will be recorded so that flecs can call observers at end of each phase.
    
}

// observer system
void update_position(ecs_iter_t *iter) {
    for (int i = 0; i < it->count; i ++) {
         // update positions here

    }
   // an observer could also notify events for subsequent processing.
   notify(iter, Position, EcsOnSet);
}

int main(){
...
//
ECS_SYSTEM(world, update_origin, ...);
ECS_SYSTEM(world, update_position, Position, event(EcsOnSet, Origin));



}

```

**Comment by SanderMertens** [comment]
Have you tried looking at observers (`ECS_OBSERVER`)? After you change a component in a system you can emit an `OnSet` event for it with `ecs_modified(it->world, ent, Position)`. This will invoke `OnSet` observers for the component when the command is merged:

```c
ECS_OBSERVER(world, my_observer, EcsOnSet, Position);
```

**Comment by happyxianyu** [comment]
> Have you tried looking at observers (`ECS_OBSERVER`)? After you change a component in a system you can emit an `OnSet` event for it with `ecs_modified(it->world, ent, Position)`. This will invoke `OnSet` observers for the component when the command is merged:
> 
> ```c
> ECS_OBSERVER(world, my_observer, EcsOnSet, Position);
> ```

Thank for your suggestion. I reconsider about it and I have a solution now. What I really want is something called "transicent" entity which would be removed at end of each frame. Such entity can represent an event. Then I can have a system to traverse them and update the world. For example, I can create entities which have "OnSet" realtion with setted entities and have a system to traverse them. And remove "transicent" entities at end of each from by recording created entities. Is such solution has any perfromance issue? Thank for your help.

**Comment by SanderMertens** [comment]
> Such entity can represent a delayed event.

Yep, that is a common pattern that other people have used as well. The performance should be good, as creating new entities and adding components to them is pretty fast :)

Sounds like you have a solution, feel free to reopen the issue if you have more questions!
