### ISSUE TITLE
Sync points for relations and prefabs 

### ISSUE THREAD

**Issue by aponomarev1408** [SanderMertens/flecs#769]
**Describe the problem you are trying to solve.**

I have a system that instantiates prefabs:
```c
ECS_DECLARE(MyPrefab);

void MySystem(ecs_iter_t* it)
{
    ecs_new_w_id(it->world, ecs_isa(MyPrefab));
}
```

Right now I don't see a way to create a sync point for such system. I tried following declarations:

1. Assertion error
    ```c
    ECS_SYSTEM(ecs, MySystem, EcsOnUpdate, [in] MySingletone, [out] (IsA, MyPrefab)());
    ```
    ```
    error: MySystem: expected end of expression or next term
    [in] MySingletone, [out] (IsA, MyPrefab)()
                                            ^
    ```
2. Sync point is not created
    ```c
    ECS_SYSTEM(ecs, MySystem, EcsOnUpdate, [in] MySingletone, [out] MyPrefab());
    ```
3. System is never invoked. Probably because it tries to match singletone with `(IsA, MyPrefab)`
    ```c
    ECS_SYSTEM(ecs, MySystem, EcsOnUpdate, [in] MySingletone, [out] (IsA, MyPrefab));
    ```
4. This works as expected. But to my understanding this will sync all tables instead of one.
    ```c
    ECS_SYSTEM(ecs, MySystem, EcsOnUpdate, [in] MySingletone, [out] *());
    ```

**Describe the solution you'd like**

I think that 1st declaration is the most logical one. Additionally, it would be nice if `[out] MyPrefab()` or `[out] MyPrefab[self|superset]()`  or `[out] MyPrefab (self|superset)()` could be used to say that the system can modify any table that contains components from prefab or the parent prefab.

**Comment by SanderMertens** [comment]
The correct notation for this is:
```
[out] IsA(0, MyPrefab)
```

Not super intuitive, the reason for this is that
```
Foo()
```
is actually short for
```
Foo(0)
```
and
```
(IsA, MyPrefab)
```
is actually short for
```
IsA(This, MyPrefab)
```

`This` and `0` here indicate the "source" of the term, and by setting it to `0` you indicate you don't want to match it on any entity, while `[out]` indicates that you are adding/writing it.

Closing this issue for now, feel free to reopen if this doesn't fix it!
