### ISSUE TITLE
Question about speed increase in component toggling methods from v2 to v3

### ISSUE THREAD

**Issue by Riari** [SanderMertens/flecs#772]
Not a bug report or feature request, just seeking clarity about a perf increase from Flecs v2 to Flecs v3.

I wrote some benchmarks using Google Benchmark to measure and compare the performance of **adding/removing** components against **enabling/disabling** them to get a more precise idea than given in the docs. Specifically, there is one benchmark for add/remove (using `ecs_add_id` and `ecs_remove_id`), one for enable/disable (using `ecs_enable_component_w_id`), and one variant of each of those that introduces extra systems to increase the number of reads/writes to the components being toggled.

The setup for the benchmarks is as follows:

* 1,000 entities are created
* Four initialised components are added to each entity:
  * `ComponentA`, which contains a string
  * `ComponentB`, `ComponentC`, and `ComponentD`, which each contain an int
* Each entity also receives four tags
* IDs for all of the available components and tags are stored in a `Context` instance, which is set as the world context via [ecs_set_context(world, context)](https://flecs.docsforge.com/master/api-c/ecs_set_context/) for later access by the benchmark systems
* Two tags are used to aid in execution:
  * A "process me" tag, which is applied to all of the entities to indicate that they should be processed by the main flecs system used for the benchmark (`add_remove` or `enable_disable`)
  * An "enable" tag, which is alternately added and removed from entities to indicate which operation should be done next (add/enable or remove/disable)
* For the 'extra systems' variants, a system is registered for each of the component types and simply modifies/increments their values per tick

I implemented these benchmarks with Flecs v2, then migrated them to v3 to compare. In both cases, I used the C API. The code is currently private, but I should be able to make a public copy if that would be useful.

You can see the results below, which indicate the following speed increases based on CPU time from v2 to v3:

| Benchmark                         | Change |
|-----------------------------------|--------|
| bm_add_remove/0                   | +50%   |
| bm_enable_disable/0               | +85%   |
| bm_add_remove-extra_systems/1     | +46%   |
| bm_enable_disable-extra_systems/1 | +86%   |

This is obviously great if it's accurate, but I was wondering if you could shed some light on what changes were made in v3 that would speed these operations up?

## Results

The build environment in both cases is an AMD Ryzen 5 5600X machine running Windows 11. Code compiled with Visual Studio Build Tools 2022.

### Flecs v2

```
Run on (12 X 3700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 512 KiB (x6)
  L3 Unified 32768 KiB (x1)
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
bm_add_remove/0                         2.48 ms         2.51 ms          280
bm_enable_disable/0                     2.04 ms         2.04 ms          345
bm_add_remove-extra_systems/1           2.60 ms         2.62 ms          280
bm_enable_disable-extra_systems/1       2.04 ms         2.05 ms          320
```
### Flecs v3

```
Run on (12 X 3700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 512 KiB (x6)
  L3 Unified 32768 KiB (x1)
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
bm_add_remove/0                         1.25 ms         1.26 ms          510
bm_enable_disable/0                    0.297 ms        0.300 ms         2133
bm_add_remove-extra_systems/1           1.41 ms         1.41 ms          378
bm_enable_disable-extra_systems/1      0.294 ms        0.292 ms         2358
```

**Comment by SanderMertens** [comment]
Glad to see you're seeing performance improvements! There have been _many_ performance related improvements between v2 and v3, it's hard to pinpoint which ones could be contributing to the increase (they probably all do a little bit).

Things that come to mind are:
- several improvements in the hashmap that had a measurable effect on overall perf
- faster table creation
- faster relationship searches (could matter when notifying observers)
- optimizations in the table graph (directly affects add/remove perf)
- refactor of add/remove code that removed a lot of redundant code
- faster component storage implementation

You could try to use a tool like `perf` to pinpoint where most of the gains are coming from.

**Comment by Riari** [comment]
Great, thanks! Understandable that you can't easily pinpoint the biggest gains, but that's some really good insight.

Much appreciated.
