### ISSUE TITLE
Component added in seperate worlds, as singleton and then as entity causes assert.

### ISSUE THREAD

**Issue by nicokruger** [SanderMertens/flecs#778]
**Describe the bug**
Adding a component in two different worlds, once as a singleton and once on an entity causes an assert, on latest master (after API change)

**To Reproduce**
```
#include "flecs.h"

struct Resources
{
  int _dummy = 0;
};

int main()
{
  flecs::world ecs1;
  ecs1.singleton<Resources>().set<Resources>({});

  flecs::world ecs2;
  ecs2.entity().set<Resources>({});

}

```

**Expected behavior**
Not sure if this is the exact assert as in my game, but hoping it is related. Specifically, after upgrading to latest master am seeing crashes on my upgrade screen where I instantiate a seperate world to show the user a preview as they select their upgrade.

**Additional context**
Probably a new issue introduced recently on master.

**Comment by SanderMertens** [comment]
Fixed!
