### ISSUE TITLE
Don't require a default constructor to emplace a component onto an entity

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#784]
**Describe the problem you are trying to solve.**
While trying to use `flecs::entity::emplace()`, I frequently get assertions triggered in `lifecycle_traits.hpp` for `invalid constructor (INVALID_OPERATION)`. After looking through the code, I found it's due to `= delete` on the default constructor of these classes. Replacing with `= default` works, but isn't really solving the issue. I delete the default constructors of these types because a default constructed instance makes no sense for them, either due to them requiring information such as field of view if they're a camera, or data if they're a texture/mesh/armature/etc.

**Describe the solution you'd like**
I'd like a way for a type with no default constructor to be emplaced without needing to initialize it to some default value, as the documentation for `flecs::entity_builder::emplace` doesn't say that it uses the default constructor.

**Comment by SanderMertens** [comment]
Can you share the code that triggers the assert? When I try to use `emplace` with a type that doesn't have a default ctor I don't get an assert:

```cpp
struct Position {
    Position(double x_, double y_) {
        x = x_, y = y_;
    }

    double x, y;
};

struct Tag { };

int main(int argc, char **argv) {
    flecs::world ecs;

    flecs::entity e = ecs.entity()
        .emplace<Position>(10.0, 20.0);
    e.add<Tag>(); // Move between archetypes also works

}
```

**Comment by Evangel63** [comment]
Looking into it more, it's a combination of deferred emplace combined with non-trivially constructible types.
```
#include "flecs.h"

#include <string>

struct TestStruct
{
//     double x;               // 1
//     TestStruct() = delete;  // 2

    std::string name_;      // 3
    TestStruct() = default; // 4

    TestStruct(const TestStruct&) = delete;
    TestStruct(TestStruct&&) = default;
    explicit TestStruct(double ci) {}

    TestStruct& operator=(const TestStruct&) = delete;
    TestStruct& operator=(TestStruct&&) = default;
};

int main()
{
    flecs::world ecs;

    ecs.defer_begin(); // 5
    flecs::entity e = ecs.entity();
    e.emplace<TestStruct>(1.0);
    ecs.defer_end(); // 6
}
```
Using lines 1 and 2, or 3 and 4 works, but using lines 2 and 3 causes the assert. Getting rid of lines 5 and 6 also works. Compiler is `gcc-12` for compiling `flecs.c` and `g++-12` for compiling this code.

**Comment by SanderMertens** [comment]
Ahh thanks! I'll take a look

**Comment by SanderMertens** [comment]
Fixed!
