### ISSUE TITLE
ecs_gauge_t uses float types but looks like it should use ecs_float_t

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#786]
**Describe the bug**
Compiling with `ecs_float_t` set to `double` causes warnings in calls to `flecs_rest_array_append` called from `flecs_rest_gauge_append` due to `flecs_rest_array_append` taking as its third argument a `const ecs_float_t*`, whereas `ecs_gauge_t` (and `ecs_counter_t`) has `float` arrays (`float[ECS_STAT_WINDOW]` specifically).

**To Reproduce**
Compile `flecs.c` with `ecs_float_t` defined to `double` (or any other type).

**Additional context**
OS: Ubuntu 22.04
Compiler: `gcc-12`

**Comment by SanderMertens** [comment]
Fixed!
