### ISSUE TITLE
C++ term builder discrepancy between documentation and code

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#787]
**Describe the bug**
C++ interface has a discrepancy between `term_builder_i::read()`'s documentation and implementation. Documentation mentions it's short for `term_builder_i::inout_stage(flecs::In)`, but code has it as `term_builder_i::inout_stage(flecs::Out)`. Looks like a copy/paste bug due to `write` just above it using `flecs::Out`.

Edit to add:
Another discrepancy, other way around though, for `term_builder_i::inout_none` which calls `term_builder_i::inout(flecs::InOutNone)`, but documentation says it's short for `term_builder_i::inout(flecs::In)`

**To Reproduce**
File `flecs/include/flecs/addons/cpp/mixins/term/builder_i.hpp`, line 277-282
File `flecs/include/flecs/addons/cpp/mixins/term/builder_i.hpp`, line 313-316

**Expected behavior**
Looks like documentation is correct and code is incorrect.

**Comment by SanderMertens** [comment]
Fixed!
