### ISSUE TITLE
ecs_set_scope does not work with ecs_new_id

### ISSUE THREAD

**Issue by sro5h** [SanderMertens/flecs#794]
**Describe the bug**
After setting a scope `s` with `ecs_set_scope` entities created with `ecs_new_id` won't have the `(EcsChildOf, s)` pair added. It works as expected if entities are created with  `ecs_entity_init`.

**To Reproduce**
Run the following example code:
```c
#include "flecs/flecs.h"
#include <stdio.h>

int main(void) {
        ecs_world_t* w = ecs_init();

        ecs_entity_t s = ecs_new_id(w);
        ecs_set_scope(w, s);

        ecs_entity_t e = ecs_new_id(w);
        if (ecs_has_pair(w, e, EcsChildOf, s)) {
                printf("e is child of s\n");
        }

        ecs_entity_t f = ecs_entity_init(w, &(ecs_entity_desc_t) { 0 });
        if (ecs_has_pair(w, f, EcsChildOf, s)) {
                printf("f is child of s\n");
        }

        return ecs_fini(w);
}
```

**Expected behavior**
Should print both 'e is child of s' and 'f is child of s'.

**Additional context**
I am on Fedora 36 compiling with gcc 12.2.1.

**Comment by SanderMertens** [comment]
This is expected behavior. `ecs_new_id` is a low level function that only creates an id and is called by other functions (like `ecs_entity_init`, `ecs_new_w_id`) that respect `ecs_set_scope` and `ecs_set_with`.

**Comment by sro5h** [comment]
Thanks for clearing things up in the doc comment :)
