### ISSUE TITLE
Ability to invoke non multi-threaded system from the main thread.

### ISSUE THREAD

**Issue by TheDrunkenBunny** [SanderMertens/flecs#798]
**Describe the problem you are trying to solve.**
Currently in Flecs's multithreaded pipeline execution, non multi-threaded systems are invoked from a first worker thread.
This behavior can prevent execution of a certain application code that relies on it being processed from the main thread / thread that invokes `world::progress`.

**Describe the solution you'd like**
Have an option to specify if non multi-threaded system should be invoked from the main thread or simply make this a default behavior.
Main thread could be acting as a first worker, not only processing (marked) non multi-threaded systems but also help with normal execution of pipeline systems, just like a worker thread.

**Comment by deus369** [comment]
This is really important for graphics based entity rendering systems!

**Comment by SanderMertens** [comment]
Done!
