### ISSUE TITLE
Select multiple sets of entities?

### ISSUE THREAD

**Issue by tomc1998** [SanderMertens/flecs#80]
I'm writing a game where a chunk of the terrain is an entity, and that entity has the 'tilemap' component. I want to check collisiosn with these entities separately, since it's such a distinct procedure, rather than figuring out a generic 'collider' class and adding it to each tilemap. In addition, treating it as a tilemap allows for some useful optimisations.

I want to loop over all the entities, and in a nested loop, loop over all the tilemaps. For this I'd want 2 distinct rows, for separate queries. For example, in pseudocode:

```
function collideWithTilemap(Rows entity_rows, Rows tilemap_rows) {
    for (int ii = 0; ii < entity_rows.count; ++ii) {
        for (int jj = 0; jj < tilemap_rows.count; ++jj) {
            // Check collisions here
        }
    }
}
```

Is something like this possible / easy to implement within the current flecs framework, is there a  workaround for my current situation? thanks.

**Comment by SanderMertens** [comment]
@tomc1998 You can create a manual system for your nested loop, and use `ecs_run` to invoke it. The `ecs_nbody` example shows you how to do it:

https://github.com/SanderMertens/ecs_nbody/blob/master/src/main.c#L182

The `Gravity` system runs the "outer" loop, whereas the `GravityComputeForce` system runs the inner loop.

**Comment by tomc1998** [comment]
Oh, i see. Unless i've missed it, this should be explicit in the docs
somewhere, I suppose this issue is good enough. running something n^2 times
for n entities is probably pretty common.

What's the overhead for running a system manually like this?

**Comment by SanderMertens** [comment]
@tomc1998 Yes I agree. I just noticed I should add an example of a Manual system to the repository. Hopefully that'll make it easier to discover.

The overhead is pretty minimal! A manual system is mostly the same as regular periodic systems, which means that everything is already preprocessed (tables have been prematched etc).

**Comment by SanderMertens** [comment]
This example shows how to run a manual system: https://github.com/SanderMertens/flecs/tree/master/examples/c/23_get_children

**Comment by 999pingGG** [comment]
@SanderMertens the link is broken now

**Comment by SanderMertens** [comment]
@999pingGG Yep, all the examples have moved since then. Check https://github.com/SanderMertens/flecs/blob/master/examples/cpp/systems/basics/src/main.cpp#L38
