### ISSUE TITLE
Observer with only Not terms asserts when triggered for prefab

### ISSUE THREAD

**Issue by TheDrunkenBunny** [SanderMertens/flecs#801]
**Describe the bug**
Tripping assert `ecs_assert(index >= 0, ECS_INVALID_PARAMETER, NULL)` in `ecs_table_type_to_storage_index`
when entity instantiated from prefab is deleted.
Specific Observer setup is necessary for this issue to appear. Observer has to have ` .term(flecs::System).not_()` or ` .term(flecs::Observer).not_()`.

**To Reproduce**

Following code reproduces issue on my end
```c
Ecs.observer<>()
    .term(flecs::Disabled) // not required to reproduce
    .term(flecs::System).not_()
    .term(flecs::Observer).not_()
    .event(flecs::OnAdd) // looks like event type doesn't matter here
    .each([](flecs::entity) {});

struct FEcsPrefab {};
Ecs.prefab<FEcsPrefab>();
Ecs.entity().is_a<FEcsPrefab>().destruct();
```

**Expected behavior**
To not assert.

**Comment by SanderMertens** [comment]
Fixed!
