### ISSUE TITLE
Replace ecs_*_illegal operations with templated versions for debugging info

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#802]
**Describe the problem you are trying to solve.**
When using the C++ interface with an invalid type, it compiles fine, but triggers an `ecs_abort` later when the `ecs_*_illegal` functions are called. I am then unable to find which type caused it to explode since the stack trace contains no type information, and running in a debugger only shows that it's an operation that happened during a merge.

**Describe the solution you'd like**
Replace the `ecs_*_illegal` operations with `template <typename T> ecs_*_illegal`. Ideally, this would be a compile time error via `static_assert` or something similar, but based on a bit of testing, this is likely to blow up in unintended ways.

**Comment by Evangel63** [comment]
Doesn't look like it could be turned into a `static_assert` due to the way `cpp_type_impl<T>` works. Adding a static assert causes it to break in (among other places) the `units` addon when registering  the module in C++. I believe it could be made to work by adding the required `constexpr` and making `cpp_type_impl<T>` `constexpr` friendly, but that could only be done by replacing the `ecs_assert` in there with something else that is `constexpr` friendly.

**Comment by SanderMertens** [comment]
A static assert wouldn't work, because whether something is illegal depends on which hooks (ctor/dtor..) are going to be invoked for a type, and this is not always known at compile time.

I do agree though that the error reporting has to be improved here. I'll look into whether I can at least add the type name to the error message, or throw it higher up the stack.

**Comment by SanderMertens** [comment]
Fixed! I ended up adding the typename to the error message.
