### ISSUE TITLE
Allow users to use c++ 17 features

### ISSUE THREAD

**Issue by happyxianyu** [SanderMertens/flecs#804]
> I can't use `std::is_invocable` because the API needs to be C++11 compatible. Adding a check on whether the code is compiled with C++17 is also not straightforward as all compilers require different ways to test for this.

Maybe we don't need to detect C++ version automatically. We can just use #ifdef directive so that the user can choose whether to enable C++17 feature or not.

For example,
```
#ifdef ENABLE_CPP_17
template<...>
using is_callable=std::is_invocable<...>;

#else 
...
#endif
```

_Originally posted by @happyxianyu in https://github.com/SanderMertens/flecs/issues/785#issuecomment-1232442778_

**Comment by happyxianyu** [comment]
I can create a pull request if the solution accepted.

**Comment by SanderMertens** [comment]
I don't want to merge this solution for a few reasons:

- I don't think this is a correct fix for the issue (multiple overloads of `()` on a type). There is no correct list of parameters to pass to `is_invocable`, as the API should accept multiple signatures:
```c
e.set([](Position& p) { });
e.set([](Position& p, Velocity& v) { });
// etc
```

- A type with multiple `()` overloads would be ambiguous in this context, as the code wouldn't know which one to call
- I don't want to add compile time flags for different language revisions. Having multiple build configurations for different language revisions would be difficult to test, especially against all the different compilers & compiler revisions.
- The problem would still persist in C++11 and C++14.

There are other potential solutions that require making changes to the API (like not overloading `set`, but use a different name for the function that accepts a function) that are portable. I want to take a bit more time to come up with a design that doesn't add this level of complexity, and addresses the issue for all language revisions.
