### ISSUE TITLE
How can I make OnLoad phases just run for once?

### ISSUE THREAD

**Issue by LooksForFuture** [SanderMertens/flecs#810]
I'm trying to make the OnLoad phase just run for once and not in every world progress. I mean something like unity "Start" function in monobehaviour. Would you please help me?

**Comment by SanderMertens** [comment]
You can't do that yet with pipelines. What you could do is create an `OnStart` tag yourself, add it to the relevant systems, and do a query for all `OnStart` systems before your first frame:

```c
flecs::entity OnStart = world.entity();

world.system("my_on_start_system")
  .kind(OnStart)
  .iter( ... );

flecs::query<> q = world.query_builder()
  .term(flecs::System)
  .term(OnStart)
  .build();

q.each([](flecs::entity e) {
  world.system(e).run();
});
```

I do agree having an `OnStart` phase as a builtin feature would be nice, I'll have a look at what it would take to implement it.

**Comment by LooksForFuture** [comment]
Thank you very much 👍
