### ISSUE TITLE
Undo destruction of entity

### ISSUE THREAD

**Issue by NukeBird** [SanderMertens/flecs#815]
Is there any way to revive dead entity? Including its original id?

I'm making an editor with undo/redo feature, every action is a Command that can be executed or undo its previous execution:
```cpp
class Command
{
public:
	virtual ~Command() = default;
	virtual void execute() = 0;
	virtual void undo() = 0;
	virtual bool merge(std::shared_ptr<Command> cmd);
};
```
I also have CommandHistory with a buffer of commands:
```cpp
class CommandHistory final
{
private:
	const int CAPACITY = 256;
	std::deque<std::shared_ptr<Command>> buffer;
	int32_t current = 0;
public:
	void add_command(std::shared_ptr<Command> cmd, bool execute = true);
	void undo();
	void redo();
};
```

Naive CreateEntityCommand like this, ofc, won't work:
```cpp
void CreateEntityCommand::execute()
{
	auto w = parent.world();
	created_entity = w.entity().child_of(parent).add<Transform>().set(Name{});
}

void CreateEntityCommand::undo()
{
	created_entity.destruct();
}
```
Because every ::execute() will make entity with different id. I tried to store "killed id" after every undo and then use it on every redo ("execute after undo"), but it didn't work well

Please help, I have a feeling that this can be implemented easily and I'm missing something important...

**Comment by NukeBird** [comment]
(same question about entities with childs, they may be deleted by DeleteEntityCommand. AFAIK, while destructing parent its childs will be destructed too)

**Comment by copygirl** [comment]
You can pass the entity ID in the entity description I believe.

**Comment by copygirl** [comment]
Okay maybe I'm incorrect, as the [source](https://github.com/SanderMertens/flecs/blob/master/include/flecs.h/#L612) says this:
```c
/** Used with ecs_entity_init */
typedef struct ecs_entity_desc_t {
    [...]
    ecs_entity_t id;     /* Set to modify existing entity (optional) */
```

**Comment by NukeBird** [comment]
@copygirl yeah, I fear that it isn't that simple

**Comment by SanderMertens** [comment]
@NukeBird You can use the solution that @copygirl suggested (specify the entity id in `ecs_entity_desc_t`), but you need to make sure to use the entity id with the old generation count. You can do this after deleting the entity with this function:

```c
ecs_ensure(world, entity_id_to_delete);
```

Feel free to reopen the issue if that didn't solve the problem!

**Comment by NukeBird** [comment]
@SanderMertens @copygirl oh! Yeah, it actually worked!

```cpp
#include "create_entity_command.h"
#include <engine/component/name.h>
#include <engine/component/transform.h>
#include <spdlog/spdlog.h>

CreateEntityCommand::CreateEntityCommand(flecs::entity parent): parent(parent)
{
}

void CreateEntityCommand::execute()
{
	auto w = parent.world();
	spdlog::info("parent_world: {}", w.id());

	if (!executed_once)
	{
		created_entity = w.entity().child_of(parent).add<Transform>().set(Name{});
		executed_once = true;
		return;
	}

	created_entity = w.ensure(created_entity).child_of(parent).add<Transform>().set(Name{});
}

void CreateEntityCommand::undo()
{
	created_entity.destruct();
}
```

I think it works fine for CreateEntityCommand since this command always creates default entities with default components. Though, I think that my code looks silly, I should get rid of ".child_of(parent).add<Transform>().set(Name{});" chain

BUT! Commands like "DeleteEntity" is a different story, because on its undo I need to:
1. Restore all the components (detroy vanishes them completely)
2. Revive not only deleted entity, but also its childs 

I have questions:
1. Will entity.clone(...) clone its childs?
2. By passing dst_id=0 to clone(...), does it mean I'm making invalid entity (but still copying all the components to it)?  
3. Is there any way to say "Hey! You are not valid anymore" without destroying its components? :D 
4. I still have no clue how to implement DeleteEntity::undo, intuition just tells me I need to use clone() before destroy. If you have any ideas, please share. Even pseudocode will help a lot, thank you!

**Comment by NukeBird** [comment]
@SanderMertens (I don't think I can re-open this issue, because I wasn't one who closed it. I can't see a button)

**Comment by NukeBird** [comment]
Some alternative thoughts in my mind: I can make struct DelayedDeletion mark and call actual destroy() if and only if destructor of Command getting called (this means it is not in history buffer anymore)

It sounds nice, but... It also mean that I need to check DelayedDeletion in my every system logic, yikes :(

**Comment by copygirl** [comment]
This might not be the perfect solution, but you do your own management of alive entities by having an `Alive` or `Destroyed` tag that you just explicitly add to all of your queries to filter out dead entities. Destroying and reviving entities would then simply involve adding and removing that tag. Though not sure how that could affect children.

**Comment by NukeBird** [comment]
@copygirl true, and I love your naming better, though it also mean that every system should ask "HEY! Entity, are you alive? Can I update you?"... Yeah, I can write a wrapper that will hide this check, but I still think there must be a more elegant way 

>  Though not sure how that could affect children.
I think, command can mark all children as "Destroyed" too and it will work fine

**Comment by SanderMertens** [comment]
> Will entity.clone(...) clone its childs?
The `clone` command doesn't, but you can use prefabs for this:
https://github.com/SanderMertens/flecs/blob/master/examples/cpp/prefabs/hierarchy/src/main.cpp

> By passing dst_id=0 to clone(...), does it mean I'm making invalid entity (but still copying all the components to it)?
If you pass `0` to `dst_id` the clone function creates a new entity vs. cloning to an existing id. It is the same as first creating a new (empty) entity, and then passing it to the clone function.

> Is there any way to say "Hey! You are not valid anymore" without destroying its components? :D
That's not possible. The closest thing to that would be to disable an entity with the `e.disable()` function.

> I still have no clue how to implement DeleteEntity::undo, intuition just tells me I need to use clone() before destroy. If you have any ideas, please share. Even pseudocode will help a lot, thank you!
Do you need to undo at the entity level? One thing you could consider using is snapshots, which restores the entire world to an earlier point in time.

**Comment by NukeBird** [comment]
> Do you need to undo at the entity level? One thing you could consider using is snapshots, which restores the entire world to an earlier point in time.

Yeah! I'm making small editor based on imgui and flecs, when I click on entity in HierarchyView, it becomes editable in Inspector. I'm doing Delete/Create of entities also in HierarchyView window. I was thinking for a long time do I really need any hierarchy and decided that yes, hierarchy makes a lot of sense 

Aren't snapshots heavy? If I want to undo deletion just of 2-3 entities, I don't think I need to make and store a snapshot of entire world...

**Comment by NukeBird** [comment]
That's implementation of my CommandHistory

```cpp
void CommandHistory::add_command(std::shared_ptr<Command> cmd, bool execute)
{
	if (!cmd)
	{
		return;
	}

	if (execute)
	{
		cmd->execute();
	}

	if (buffer.size() > 0 &&
		current >= 0)
	{
		if (buffer[current]->merge(cmd))
		{
			return;
		}
	}

	if (buffer.size() > 0)
	{
		buffer.erase(buffer.begin() + current + 1, buffer.end());
	}

	if (buffer.size() == CAPACITY)
	{
		buffer.pop_front();
	}

	buffer.emplace_back(cmd);
	current = buffer.size() - 1;
}

void CommandHistory::undo()
{
	if (current >= 0 && buffer.size() > 0)
	{
		buffer[current]->undo();
		current--;
	}
}

void CommandHistory::redo()
{
	if (current + 1 < buffer.size())
	{
		current++;
		buffer[current]->execute();
	}
}
```

To implement undo/redo, every action wrapped in a class inherited from Command. And so, command itself can remember what was changed/deleted and how to undo it. Well, theoretically at least. 

Disabled entities won't be iteratable by systems, right? I need to disable its children manually or will they be disabled by disabling their common parent? Anyways, I probably can try to use this feature, thanks for the hint

**Comment by NukeBird** [comment]
> The `clone` command doesn't, but you can use prefabs for this:
> https://github.com/SanderMertens/flecs/blob/master/examples/cpp/prefabs/hierarchy/src/main.cpp

Yeah, I was thinking about it too. Gotta write function "make prefab out of entity", guess it makes sense

**Comment by SanderMertens** [comment]
Closing this issue, as it looks like the question has been answered!
