### ISSUE TITLE
e.set_name() sometimes causes id collisions

### ISSUE THREAD

**Issue by NukeBird** [SanderMertens/flecs#816]
Why this happens? I litarally had 3-4 entities, and at runtime I tried to rename all of them to "A". First 2-3 entities allowed me to give them exactly the same names, but at 3-4  I'm getting crash with an id collision. Why? I'm not changing its id's, just its names. Are names getting hashed somehow? All names should be unique?

**Comment by SanderMertens** [comment]
The reason for this is that entities that have the same parent cannot have the same name (names do get hashed). Entities can have the same name as long as they have different parents, similar to how you can't have two files with the same name in the same directory.

**Comment by NukeBird** [comment]
Oh, I see now. Thanks for explanation!
So making "Name" component wasn't a bad idea at all, I was afraid I'm duplicating functionality lol

**Comment by SanderMertens** [comment]
@NukeBird you don't have to, the `FLECS_DOC` addon lets you add a user-friendly name to an entity that doesn't have to be unique:

```c
e.set_doc_name("my user friendly name");
```
