### ISSUE TITLE
Avoid the boilerplate of .module call inside each module constructor

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#818]
**Describe the problem you are trying to solve.**
When creating a C++ module, you have to write `world.module<ModuleTypeName>()` at the beginning, if you forget to do that, the systems will not be children of said module. There are no scenarios where you would not want to scope them like this that are known.

**Describe the solution you'd like**
`world.import<ModuleTypeName>` should automatically scope the systems and components inside the imported module.

**Comment by SanderMertens** [comment]
Fixed!
