### ISSUE TITLE
world.run_pipeline executes all queries and filters and other pipelines

### ISSUE THREAD

**Issue by LooksForFuture** [SanderMertens/flecs#825]
Every time I use world.run_pipeline all the pipelines, filters and queries run too

**Comment by SanderMertens** [comment]
Can you elaborate on you mean by running a filter or a query? If you can, attach a reproducer (snippet of code that reproduces the bug).

**Comment by SanderMertens** [comment]
I'm closing this issue as I don't have enough information to go on. One potential problem you could be running into is that multiple pipelines match the same systems.

A pipeline is a query (for systems) under the hood, and it is possible that multiple pipelines match the same set of systems. For example, the default pipeline doesn't just match builtin phases, it matches _any_ system that has a `DependsOn` relationship to an entity with the `Phase` tag.

When creating your pipeline queries, make sure that they match on something that's unique to that pipeline.
