### ISSUE TITLE
Rest API plugin crashes when trying to jsonify union with dead entity

### ISSUE THREAD

**Issue by Mrkol** [SanderMertens/flecs#828]
**Describe the bug**
Rest API plugin (not the website!) crashes whenever it tries to parse and jsonify an entity that has a union with a dead entity as a target.

**To Reproduce**
1. Create a union tag U
2. Do `entity.add<U>(otherEntity)`
3. Kill `otherEntity`
4. Try to request `entity` through the REST API
5. Boom!

**Expected behavior**
I expect the viewer to properly show me the `entity` and tell me that `otherEntity` died.

**Additional context**
Should be context-independent.

**Comment by SanderMertens** [comment]
Fixed!

I ended up skipping the relationship in the serializer altogether, as that is closest to what it would look like when union relationship cleanup is implemented.
