### ISSUE TITLE
Cannot Bulk Spawn in a System

### ISSUE THREAD

**Issue by deus369** [SanderMertens/flecs#837]
**Describe the bug**
A memory crash when calling ecs_bulk_init within a system.

**To Reproduce**
Run this script:
https://github.com/deus369/open-zoxel/blob/master/Tests/test_bulk_spawn.c

**Expected behavior**
No crashy!

**Additional context**
Ubuntu, amd cpu x86 64 bit..!

**Comment by SanderMertens** [comment]
The `ecs_bulk_init` operation cannot be called from regular systems. The reason for this is that the operation would have to be executed as command, but the resources passed to the function go out of scope after the system is called. This would require the operation to allocate temporary memory which is slow.

Maybe I'll find a way to support this in the future, but for now it's not possible. I added an `INVALID_PARAMETER` error that is thrown when you try to call it from a system, so you don't get unexpected crashes.

**Comment by deus369** [comment]
Hi Sander, I think this issue regressed. I am getting a crash on my test!

https://codeberg.org/deus/zoxel/src/branch/master/tests/flecs/bulk_spawn.c

 Process terminating with default action of signal 6 (SIGABRT)
==60905==    at 0x490926B: __pthread_kill_implementation (pthread_kill.c:44)
==60905==    by 0x490926B: __pthread_kill_internal (pthread_kill.c:78)
==60905==    by 0x490926B: pthread_kill@@GLIBC_2.34 (pthread_kill.c:89)
==60905==    by 0x48B2C45: raise (raise.c:26)
==60905==    by 0x48997FB: abort (abort.c:79)
==60905==    by 0x489971A: __assert_fail_base.cold (assert.c:92)
==60905==    by 0x48AA595: __assert_fail (assert.c:101)
==60905==    by 0x115A99: _ecs_poly_assert (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x11C1B9: ecs_bulk_init (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x1BECC5: SpawnSystem (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x1720B7: ecs_run_intern (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x13D225: flecs_run_pipeline (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x13AF22: flecs_workers_progress (in /home/deus/zoxel/tests/builds/bulk_spawn)
==60905==    by 0x13CF81: flecs_run_pipeline (in /home/deus/zoxel/tests/builds/bulk_spawn)

**Comment by SanderMertens** [comment]
> Maybe I'll find a way to support this in the future, but for now it's not possible

The assert you're getting is the one I added to make sure you don't get silent failures or segfaults.
