### ISSUE TITLE
bulk_init does not trigger custom on_add hooks.

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#839]
**Describe the bug**
bulk_init does not trigger custom on_add hooks.

**To Reproduce**
```c
struct Component{
  int Value;
};
..
world.component<Component>().on_add([](Component &){
  printf("Test");
});
..
bulk_init(.. Component ..); // nothing is printed to the console
```

**Comment by SanderMertens** [comment]
Fixed! I ended up adding the call to the `flecs_table_appendn` function, so that additional future callers of this function don't have to deal with calling the right hooks.
