### ISSUE TITLE
Deferred emplacing a component followed by removing a separate component does not add the first component

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#845]
**Describe the bug**
Basically the title. In the below code, commenting out line 1 adds the T2 just fine. It seems to somehow get an `EcsOpSkip` command kind which then discards the emplace, even though the remove is for a different component. Doing a remove followed by an emplace also doesn't work, ie in the code below, putting line 1 before line 2.

**To Reproduce**
```c++
#include "flecs.h"

#include <iostream>

struct T1 {};

struct T2
{
    uint32_t d;
};

int main()
{
    flecs::world ecs;
    auto e1 = ecs.entity("TestEntity1").add<T1>();

    auto str = ecs_entity_str(ecs, e1);
    std::cout << str << std::endl;

    ecs.defer_begin();
    e1.emplace<T2>(uint32_t(1)); // 2
    e1.remove<T1>(); // 1
    ecs.defer_end();

    str = ecs_entity_str(ecs, e1);
    std::cout << str << std::endl;
}
```

**Expected behavior**
Output should show as:
```
TestEntity1 [T1, (Identifier,Name)]
TestEntity1 [T2, (Identifier,Name)]
```

**Additional context**
Ubuntu 22.04, gcc-12 for flecs, g++-12 for above code
Actual output
```
TestEntity1 [T1, (Identifier,Name)]
TestEntity1 [(Identifier,Name)]
```

**Comment by SanderMertens** [comment]
Fixed!
