### ISSUE TITLE
Binding context in run action of multi threaded system

### ISSUE THREAD

**Issue by sro5h** [SanderMertens/flecs#849]
**Describe the bug**
Using a custom run action in a multi threaded system and setting `ecs_system_desc_t::binding_ctx`, the value of `it->binding_ctx` inside the run action is `NULL` until the first time `ecs_iter_next` is called.
If `ecs_system_desc_t::multi_threaded` is set to `false` the binding context will be available immediately.

**To Reproduce**
Run the follwing example:
```c
#include "flecs/flecs.h"
#include <assert.h>
#include <stdio.h>

void system_run(
                ecs_iter_t* iter) {
        // Uncommenting the next line will fix the assert
        //ecs_iter_next(iter);
        assert(iter->binding_ctx);
}

int main(void) {
        ecs_world_t* w = ecs_init();

        ecs_set_threads(w, 2);

        int32_t* context = ecs_os_calloc(sizeof(*context));
        *context = 42;

        ecs_system_init(w, &(ecs_system_desc_t) {
                .entity = ecs_entity_init(w, &(ecs_entity_desc_t) {
                        .name = "SystemCallback",
                        .add = { ecs_pair(EcsDependsOn, EcsOnUpdate), EcsOnUpdate },
                }),
                .query.filter.expr = "",
                .run = system_run,
                .binding_ctx = context,
                .multi_threaded = true,
        });

        ecs_progress(w, 0.0);

        return ecs_fini(w);
}
```

**Expected behavior**
I did expect the binding context to be available immediately inside the run action. It seems to be because the binding context is only set on the query iterator:
https://github.com/SanderMertens/flecs/blob/5e0f37a9a58626b5a93feeaf65dda94f4e535916/src/addons/system/system.c#L101

**Additional context**
I'm on Fedora 36 compiling with gcc 12.2.1.

**Comment by SanderMertens** [comment]
Fixed!
