### ISSUE TITLE
create macro ECS_ENTITY_WITH_COUNT where you can specify several components

### ISSUE THREAD

**Issue by WEREMSOFT** [SanderMertens/flecs#85]
**Describe the problem you are trying to solve.**
I'd like to create entities in bulk, adding multiple components in the same step.

**Describe the solution you'd like**
Since there is a function called "ecs_new_w_count", but that accepts only one component as a parameter before the count, I'd like to have a macro that allows to create entities in bulk, adding components, also in bulk. Proposed name ECS_ENTITY_WITH_COUNT.

Thanks

**Comment by SanderMertens** [comment]
@WEREMSOFT would this work for you as a solution?

```c
ECS_TYPE(world, MyType, Component1, Component2, ...);

ecs_new_w_count(world, Type, 100);
```

**Comment by WEREMSOFT** [comment]
It worked very well. Thanks
