### ISSUE TITLE
`emplace`, `set`, `get_mut`, and `get_ref` improvements

### ISSUE THREAD

**Issue by Evangel63** [SanderMertens/flecs#856]
**Describe the problem you are trying to solve.**
I have move only types that store resources. I normally use the `.emplace<T1>(args)` entity function to construct them in place, but that can't emplace a pair. I tried using `.set<T1, T2>({std::move(v)})`, but that tries to use the copy assignment operator, as does `.set<T1, T2>(std::move(v))` where `v` is a `T1`. I'd also like to do `get_ref<T1, T2>()` to get the main storage of a component pair, but this has a workaround in
```c++
auto first = flecs::_::cpp_type<A>::id(world);
auto second = flecs::_::cpp_type<B>::id(world);
auto pair = ecs_pair(first, second);
auto ref = ecs_ref_init_id(world, object, first);
auto& val = *static_cast<A*>(ecs_ref_get_id(world, &ref, pair));
```

The typed versions of `.get_mut<T>` could also be disallowed if there is no copy constructor for the type.

**Describe the solution you'd like**
I'd like to be able to do `.emplace<T1, T2>(args)` and get a `(T1, T2)` component pair, or `.set<T1, T2>(std::move(v))` that uses the move assignment operator. Also `.get_ref<T1, T2>()` and get a `ref<T1>` or `ref<T1, T2>`.

**Comment by SanderMertens** [comment]
Done!
