### ISSUE TITLE
INCONSISTENT_NAME using ecs_entity_init with symbols and IsA relationship

### ISSUE THREAD

**Issue by copygirl** [SanderMertens/flecs#858]
**Describe the bug**
The following error occurs when creating an entity using `ecs_entity_init` with a symbol if it has an `IsA` relationship when the target also has a symbol set. It appears `ecs_get_symbol` incorrectly returns the inherited symbol value in [`flecs_traverse_add`](https://github.com/SanderMertens/flecs/blob/e0b4c40156585648e5499b674fa6eac8bee2f5c8/src/entity.c#L1493-L1501) (for example), even though `Identifier` should be marked as `DontInherit` and thus never expose inherited values.

`fatal: flecs.c: 45328: assert: !ecs_os_strcmp(desc->symbol, sym) Texture (INCONSISTENT_NAME)`

**To Reproduce**
```cs
ecs_world_t *world = ecs_init();
ecs_entity_t Resource = ecs_entity_init(world, &(ecs_entity_desc_t){
    .name = "Resource",
    .symbol = "Resource"
});
ecs_entity_t Texture = ecs_entity_init(world, &(ecs_entity_desc_t){
    .name = "Texture",
    .symbol = "Texture",
    .add = { ecs_pair(EcsIsA, Resource) }
});
```

**Comment by SanderMertens** [comment]
Fixed!
