### ISSUE TITLE
Add context parameter to `ecs_module_action_t`

### ISSUE THREAD

**Issue by sro5h** [SanderMertens/flecs#862]
**Describe the problem you are trying to solve.**
There doesn't seem to be an easy option to pass data to a module's import function (e.g. some configuration parameters). I thought I could set some singleton component, but then there is the problem that the component needs to be registered first (which would happen in the module's import function).

**Describe the solution you'd like**
As far as i can tell it should be possible to add a context parameter to `ecs_import` and `ecs_module_action_t`.

**Comment by SanderMertens** [comment]
I used to have a context parameter in an old version of Flecs, but got rid of it for a few reasons:
- it added bloat to import calls which and was rarely used
- it no longer makes module importing idempotent

The latter is especially an issue in applications where modules import each other. Once a module is imported, its import function won't get called again, even if `ecs_import` / `ECS_IMPORT` / `world::import` is called multiple times for the module. If you'd have two `import` calls with different context, the second context would be ignored, which could lead to unexpected/undefined behavior.

If you intended to use the context just to decide which things to import, you can workaround this by defining multiple import functions that import different/overlapping components and/or systems. If you're looking to do something else (such as initializing a renderer, creating a window etc) I'd take a look at `OnSet` observers.

With observers you can register a component + `OnSet` observer in a module. If you then set the component after importing the module, the observer gets ran which can then execute the initialization code.

**Comment by sro5h** [comment]
Ok that seems like a good solution
