### ISSUE TITLE
Filter builder incorrect behavior with left operand as lvalue reference.

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#870]
**Describe the bug**
When result of `filter_builder.build()` is captured into an lvalue reference as left operand, it is not being initialized properly, and asserting it throws asserts.

**To Reproduce**
```c
auto Builder = World.filter_builder<>();
Builder.term(123).self().inout(flecs::In);
Builder.instanced();
flecs::filter<> Filter;
flecs::filter<> &FilterRef = Filter;
FilterRef = Builder.build();
FilterRef.iter([](flecs::iter &){}); // this asserts
```

**Expected behavior**
The code should not assert, and behave like following code:
```c
auto Builder = World.filter_builder<>();
Builder.term(123).self().inout(flecs::In);
Builder.instanced();
flecs::filter<> Filter;
Filter = Builder.build();
Filter.iter([](flecs::iter &){}); // this asserts
```

**Comment by Hexlord** [comment]
Workaround is to capture .build() into a temporary variable, and assign to lvalue reference afterwards.

**Comment by SanderMertens** [comment]
Fixed!
