### ISSUE TITLE
World.lookup(entityName) always returns nullable entity

### ISSUE THREAD

**Issue by DezlowNG** [SanderMertens/flecs#880]
**Describe the bug**
world.lookup(entityName) always returns nullable entity.

**Code**
![img1](https://user-images.githubusercontent.com/74720936/206891496-bd8391b6-8ee7-4c59-b09f-493d6125ef8f.png)
![img2](https://user-images.githubusercontent.com/74720936/206891508-66549115-933a-42b4-9161-3d8f8058b729.png)

**Expected behavior**
I think that world.lookup() must return a valid entity when world have it.

**Additional context**
So, I tried to log which entities world have, but it has no entities, but I'm creating entities with using world.entity().
![img3](https://user-images.githubusercontent.com/74720936/206891832-cbd5d9cd-7a00-4a4a-8206-b62ec491c248.png)
![img4](https://user-images.githubusercontent.com/74720936/206891858-ed1c2022-bd7a-4458-a72e-6674392bd116.png)

P.S. Sorry for my English, lol

**Comment by SanderMertens** [comment]
Thanks for creating the issue! Could you create an isolated code example that reproduces the issue? The code looks OK at first glance, but doesn't seem to be doing anything special that I don't already have tests for.

A good example for an issue with a reproducing code example is this one:
https://github.com/SanderMertens/flecs/issues/855

Thanks!

**Comment by DezlowNG** [comment]
Soo... I wrote this code:
```
#include "flecs.h"

#include <iostream>

int main()
{
    flecs::world world{};
    auto root = world.entity("Root");
    auto first = world.entity("First").child_of(root);
    auto second = world.entity("Second").child_of(first);

    world.each([](flecs::entity entity) {
        std::cout << entity.name() << '\n';
    });

    std::cout << world.lookup("Root").id() << std::endl;
    std::cout << world.lookup("First").id() << std::endl;
    std::cout << world.lookup("Second").id() << std::endl;
}
```
Result of code:
532
0
0

I rewrote code to this:
```
#include "flecs.h"

#include <iostream>

int main()
{
    flecs::world world{};
    auto root = world.entity("Root");
    auto first = world.entity("First").child_of(root);
    auto second = world.entity("Second").child_of(first);

    world.each([](flecs::entity entity) {
        std::cout << entity.name() << '\n';
    });

    std::cout << world.lookup("Root").id() << std::endl;
    std::cout << world.lookup("Root::First").id() << std::endl;
    std::cout << world.lookup("Root::First::Second").id() << std::endl;
}
```
And it works fine.
Result:
532
533
534

I think you need to create a new function which could find entities in child entities... Or you need to add to doc that user need to write full path to entity...
![img](https://user-images.githubusercontent.com/74720936/206895766-0ae765b7-7d1a-42aa-aba9-f31b4e085606.png)

About each function:
It works fine when I add second arg to lambda.
Code:
```
#include "flecs.h"

#include <iostream>

struct Test
{
    int test{};
};

int main()
{
    flecs::world world{};
    auto root = world.entity("Root");
    auto first = world.entity("First").child_of(root);
    auto second = world.entity("Second").child_of(first);

    first.add<Test>();
    second.add<Test>();

    world.each([](flecs::entity entity, Test& test) {
        std::cout << entity.name() << '\n';
    });
}
```

**Comment by DezlowNG** [comment]
I rewrote my code and it works fine! But I think that using each for finding entity by name in world is uncomfortable... Maybe there is a good solution?
![img](https://user-images.githubusercontent.com/74720936/206896735-6642df93-856f-4664-8fee-97e7f2eea106.png)

**Comment by copygirl** [comment]
Are you aware of the difference between names and symbols?

Names only uniquely identify an entity in its place in the hierarchy, so you can have both a "Player.Inventory" entity and a "Chest.Inventory" entity without them conflicting. Symbols are globally unique, and don't consider hierarchy whatsoever.

In C, the function `ecs_lookup_symbol` is used to lookup an entity by its symbol.
Not sure how set the symbol in the C++ API however.

**Comment by SanderMertens** [comment]
@DezlowNG there is a lookup function on the entity, so you can do `root.lookup("First")`. Glad you found the issue!
