### ISSUE TITLE
API documentation (Docsforge) page is down. Docsforge is discontinued.

### ISSUE THREAD

**Issue by PreyK** [SanderMertens/flecs#887]
**Describe the bug**
When opening the link for the API in the [Readme.md](https://github.com/SanderMertens/flecs/blob/master/README.md?plain=1#L13) document I get a DNS_PROBE_FINISHED_NXDOMAIN error.

Upon looking into Docsforge it seems to be permanently discontinued [by the creator](https://github.com/erez-o/docsforge)

**To Reproduce**
1. Go to [The project's github page](https://github.com/SanderMertens/flecs)
2. Click on [C++11 API](https://flecs.docsforge.com/master/api-cpp/) or [C99 API](https://flecs.docsforge.com/master/api-c/)
3. See error

**Expected behavior**
A page appears where you can explore the API

**Additional context**
The [docsforge repo](https://github.com/erez-o/docsforge/commit/82ef027e4d39ed191dc8daab1cca60b0fba916a0) was updated yesterday to display "Project discontinued, thanks to all who contributed ❤️"
A [down detector](https://downforeveryoneorjustme.com/flecs.docsforge.com?proto=http) also displays the URL is down and also an [ad that the domain is for sale
](https://www.afternic.com/forsale/docsforge.com?traffic_id=GoDaddy_DLS&traffic_type=TDFS&utm_campaign=TDFS_GoDaddy_DLS&utm_medium=sn_affiliate_click&utm_source=TDFS)

**Comment by SanderMertens** [comment]
Yep, I'm aware 😔

Looking at alternatives for documentation at the moment

**Comment by SanderMertens** [comment]
Documentation is back up! https://www.flecs.dev/flecs/docs/api/html/index.html
