### ISSUE TITLE
ecs_entity_init with ChildOf pair but no name while deferred results in no ChildOf relation

### ISSUE THREAD

**Issue by copygirl** [SanderMertens/flecs#888]
### Description
When deferred, creating an entity with `ecs_entity_init` where a `ChildOf` relation is specified, but no name, the `ChildOf` relation doesn't actually end up being present on the entity. It appears to not matter if anything else is added to the entity. Just the lack of a name causes this issue. Adding the `ChildOf` relation after the call to `ecs_entity_init` also works.

### To Reproduce
```c
int main(int argc, char *argv[]) {
    ecs_world_t *world = ecs_init();

    ecs_entity_t parent = ecs_new_id(world);

    ecs_defer_begin(world);
    ecs_entity_t child = ecs_entity_init(world, &(ecs_entity_desc_t){
        // This can be uncommented to fix the issue.
        // .name = "Child",
        .add = { ecs_pair(EcsChildOf, parent) }
    });
    ecs_defer_end(world);

    printf("%s\n", ecs_entity_str(world, child));
}
```

**Actual behavior:** `511 []` is printed.
**Expected behavior:** For `510.511 [(ChildOf,510)]` to be printed.

**Comment by SanderMertens** [comment]
Fixed!
