### ISSUE TITLE
Documentation site problem

### ISSUE THREAD

**Issue by hw762** [SanderMertens/flecs#894]
The new doc site isn't working either: https://www.flecs.dev/flecs/docs/api/html/index.html

Also, `Docs.md`'s  reference to API Reference documentations are broken.

**Comment by SanderMertens** [comment]
I moved the documentation site today to https://www.flecs.dev/flecs/md_docs_Docs.html & was fixing links. If you click on the links on that page they will work.

The "Docs" button in the README points to the correct documentation page.
