### ISSUE TITLE
Logging segmentation fault

### ISSUE THREAD

**Issue by hw762** [SanderMertens/flecs#895]
**Describe the bug**
ECS logging either produces nothing or crashes.

**To Reproduce**
```
#include <flecs.h>
int main()
{
    ecs_log_set_level(3);
    ecs_trace("Hello world.");
}
```

Compile and run, segmentation fault. An additional problem is that if I remove the `set_level` call, logging does not happen, despite API doc saying default level is 3.

**Expected behavior**
Prints `Hello world.`.

**Additional context**
Pop OS 22.04

**Comment by SanderMertens** [comment]
This happens when the OS API isn't initialized yet. When you create a Flecs world, it automatically initializes the OS API, but if you don't have a Flecs world and you want to use logging/other OS API functions, you need to call this first:

```c
ecs_os_set_api_defaults();
```

**Comment by hw762** [comment]
Great, but still the default logging level seems inconsistent with the documentation. Should I open another issue or did I make a mistake?

**Comment by SanderMertens** [comment]
Which part of the documentation is inconsistent?
