### ISSUE TITLE
Use ecs_entity_init with empty ecs_entity_desc_t.sep

### ISSUE THREAD

**Issue by copygirl** [SanderMertens/flecs#897]
**Describe the problem you are trying to solve.**
When setting `ecs_entity_desc_t.sep` to an empty string to indicate that `ecs_entity_init` should not split the name given into parts, Flecs seems to fail at "parsing" the name, instead of simply treating the given string as a whole. I have to give it a character that I know won't be used within the string. In my case I opted for `\x03` ([ETX](https://en.wikipedia.org/wiki/End-of-text_character)).
This could also be considered a bug but since it's trivial to work around, I put it in as a feature request.

**Describe the solution you'd like**
I would be nice if Flecs would simply not attempt to split the given name if an empty string was given as the separator. If I understand correctly, `null` cannot be given, since that would result in the default behavior and use a dot instead.

**Comment by SanderMertens** [comment]
Done!
