### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#9]
Topics to cover:
- Design goals
- Naming conventions
- Error handling
- Memory management
- Debugging
- Common patterns
- Good practices
- System signatures
- System stages
- System ordering
- Automatic system invocation
- Manual system invocation
- Periodic systems
- Reactive systems
- Manual systems
- Tasks
- System API
- Modules
- Shared components
  - Prefab
  - Singleton
  - Container
  - System
- Builtin components
- Initializing entities
- Data structures
- Internals
- Staging
- Threading

**Comment by SanderMertens** [comment]
Describe in docs whether API allocates strings & other pointers passed into it.

**Comment by xgalaxy** [comment]
Something I'm not clear on is stages and merging. It appears as though you defer changes of entities (additions, deletions, adding components, removing components) until a merge. Is that accurate? Is there an api to control when and where that happens or is it tied specifically to certain stages?

Docs and clarification on that would be great.

**Comment by SanderMertens** [comment]
@xgalaxy I added a chapter on staging: https://github.com/SanderMertens/flecs/blob/master/Manual.md#staging

> It appears as though you defer changes of entities (additions, deletions, adding components, removing components) until a merge. Is that accurate?

Yes, that is correct. Any mutations that (potentially) require a realloc of the array, or moving entities around are staged, and by default these mutations are merged at the end of each phase (https://github.com/SanderMertens/flecs/blob/master/Manual.md#system-phases, https://github.com/SanderMertens/flecs/blob/master/Manual.md#staging-and-system-phases)

> Is there an api to control when and where that happens or is it tied specifically to certain stages?
There is, but this API is still experimental as it is a bit of a crude "all or nothing" approach at the moment: https://github.com/SanderMertens/flecs/blob/master/Manual.md#manually-merging-stages

**Comment by xgalaxy** [comment]
Wow you work quick :D 👍

**Comment by ArnCarveris** [comment]
@SanderMertens missing info about `ecs_import_from_library`

**Comment by ArnCarveris** [comment]
@SanderMertens Hmm, Manual getting pretty big, maybe you should split into `wiki` pages?

**Comment by ArnCarveris** [comment]
@SanderMertens Missing info about this section: https://github.com/SanderMertens/flecs/blame/master/Manual.md#L87

**Comment by SanderMertens** [comment]
@ArnCarveris thanks for spotting that.

Re the manual: I agree that it is getting a bit large. There are also some good markdown-to-HTML generators that could make the manual easier to navigate. What I like about having it all in one file is that it can be easily searched with CTRL-F.

**Comment by ArnCarveris** [comment]
@SanderMertens Create wiki.

**Comment by SanderMertens** [comment]
How about a format like this: https://www.corto.io/doc/guide.html

**Comment by SanderMertens** [comment]
Closing this issue as documentation covers the above sections. Future updates will be done as changes are implemented.
