### ISSUE TITLE
Use more descriptive error messages when signature parsing fails

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/flecs#90]
**Describe the problem you are trying to solve.**
When parsing of a system signature fails, Flecs will return an "invalid system signature" message, often not specifying what is not valid about the signature. This makes debugging such errors much more difficult.

**Describe the solution you'd like**
More descriptive error messages for the signature (and type) parser.

**Comment by WEREMSOFT** [comment]
Can you give a step-by-step way to reproduce an error to start with?  Ideally a piece of code. Thanks

**Comment by SanderMertens** [comment]
Sure thing. Right now, all error handling in Flecs is done with error codes (https://github.com/SanderMertens/flecs/blob/master/include/flecs.h#L2122) that are passed to either `ecs_abort` or `ecs_assert`. This guarantees consistent error messages, but the API has as downside that there is not much room for additional context.

This is especially annoying with the parser of system signatures. Consider the following code example:

```c
void Move(ecs_rows_t *rows) { }

int main(int argc, char *argv[]) {
    ecs_world_t *world = ecs_init_w_args(argc, argv);
    ECS_SYSTEM(world, Move, EcsOnUpdate, Position, Velocity);
}
```

This yields the following error:
```
[err] abort .../flecs/src/system.c:437: invalid component id (Position)
```

While it correctly reports that `Position` is not defined, it does not tell me for which system. When you have lots of systems, this can be tricky to debug.

In some cases, like this one, it will throw a generic "invalid expression" error:

```c
typedef struct Position {float x, y; } Position;

void Move(ecs_rows_t *rows) { }

int main(int argc, char *argv[]) {
    ecs_world_t *world = ecs_init_w_args(argc, argv);
    ECS_COMPONENT(world, Position);
    ECS_SYSTEM(world, Move, EcsOnUpdate, .);
}
```

It would be nice if these errors would be extended with at least the system name and the position in the signature at which the error occurred. I think it would be best if this functionality would be built specifically for the parser, to prevent bloating the existing error APIs.

**Comment by WEREMSOFT** [comment]
I'm going to start to work in this issue today. Can we flag it as "taken" or "in process"? Thanks.

**Comment by WEREMSOFT** [comment]
I created a PR. Please take a look:

https://github.com/SanderMertens/flecs/pull/99

**Comment by WEREMSOFT** [comment]
I updated the PR. Can you please take a look before I update the tests? 

https://github.com/SanderMertens/flecs/pull/99

Thanks.

**Comment by SanderMertens** [comment]
I checked it out and posted comments, thanks!
