### ISSUE TITLE
--interactive mode ignore certain files/folders

### ISSUE THREAD

**Issue by BlueRedBrackets** [SanderMertens/flecs#910]
**Describe the problem you are trying to solve.**
Editing files with vi creates a `.swp` file which causes bake to restart my app before I save my file.

1. `bake run my_app --interactive` 
1. `vi src/main.c`
1. make an edit *without* saving
1. vi creates a `.swp` file
1. bake restarts the app

**Describe the solution you'd like**
Some way to tell bake to ignore certain files/folders/patterns when determining if it should rebuild/restart the app.

Something akin to nodemon's `nodemon --ignore PATTERN [--ignore PATTERN2]`.

**Comment by SanderMertens** [comment]
This is a bake issue, not flecs! Feel free to create this issue here: https://github.com/SanderMertens/bake
