### ISSUE TITLE
Make outer loop available to systems

### ISSUE THREAD

**Issue by WowSuchName** [SanderMertens/flecs#914]
Hi everybody,

I'm rather new to using flecs, so please feel free to make this quick if I overlooked something.

**Describe the problem you are trying to solve.**
I'm trying to linearize all values of a component by copying whole tables at once (e.g. send mesh transforms to the GPU). While queries allow me to access the outer loop and therefore compute the offset into the large array by summing up the table sizes, systems can only access the inner loop (cf. documentation regarding systems). Beside increasing the offset's lifetime and visibility, this means that I have to reset the variable in each frame by installing an additional system with an empty query in the pipeline.

**Describe the solution you'd like**
To my understanding and assumptions about the inner workings, complementing systems with an additional function (C) / overload (C++) which gives access to the query underlying the system could clean up the scenario described above by introducing little complexity to flecs.

As a bonus, queries provide a convenience function for counting the entities across all non-empty tables (ecs_query_entity_count()), which would in turn allow the user to resize buffers as needed.

Adding this feature sounds rather simple to me, but again please correct me, if I'm mistaken.

Anyway, thanks for considering!

**Comment by SanderMertens** [comment]
This feature already exists! You can specify a custom run function for systems that lets you iterate both outer and inner loop. See this example for more details: https://github.com/SanderMertens/flecs/blob/master/examples/cpp/systems/custom_runner/src/main.cpp

**Comment by SanderMertens** [comment]
No problem!
