### ISSUE TITLE
Process all the hierarchy in one go.

### ISSUE THREAD

**Issue by WEREMSOFT** [SanderMertens/flecs#92]
**Describe the problem you are trying to solve.**
I'm trying to implement a scene graph using the hierarchy example as a base.

I'm using tigr library as a renderer.

The problem is that the program is calling 4 times the function that calculate the world transform, 4 times the renderer and It's forcing me to call the update screen routine in the "EcsPostUpdate" event.

This is the output of the program:

```
moving
transforming parent
transforming childs
transforming childs
transforming childs
Rendering.
Rendering.
Rendering.
Rendering.
Updating screen
######### mainLoop Called #######
```
This is the program:

https://github.com/WEREMSOFT/FlecsTests/blob/hierarchy/src/main.c

**Describe the solution you'd like**
I'd like to have a way to iterate the DACs in one go. Not in differents calls to the system. What happens if I have 1000 childs? It will not be efficient. I'd like to have (or learn) the way to have the following update from the program:

```
moving
transforming parent
transforming childs
Rendering and updating screen //Render and update screen should be in one single function.
######### mainLoop Called #######
```

Thanks, the frameworks is a lot of fun.

**Comment by SanderMertens** [comment]
First of all, that code looks great- could be readily used as an example.

The reason the function is called 4 times is because of the way data & hierarchies are stored in Flecs. For each combination of components ("archetype") Flecs will create a table which contains the component data for the entities with those components. When you run a system, it will be invoked once for every combination. What you're seeing here is because parents are considered part of that combination.

The good news: I am currently working on Flecs v2 which will address this specific problem (hierarchies getting fragmented). The bad news: it may take some time for that to get ready.. sorry :/

**Comment by SanderMertens** [comment]
A few more notes:

- Even with v2, your system may still be invoked multiple times. If you have children with different components, it will still create different archetypes, and a system will be invoked for each archetype  (with as only difference that parents are no longer part of the archetype)

- You can call the UpdateScreen routine in EcsOnUpdate. Systems are executed in order of declaration

**Comment by WEREMSOFT** [comment]
Why the "Render" system is called once per entity? I have 2 entities in root. Shouldn't be called once per parent?.

**Comment by SanderMertens** [comment]
The Render system is not called once per entity for as far as I can see. The two root entities are processed in the same call. When I add some tracing to the Render system, I get this:

```
######### mainLoop Called #######
moving
transforming parent
transforming childs
transforming childs
transforming childs
-- rendering --
Rendering 23 (EcsId,Position,WorldPosition,Velocity)
-- rendering --
Rendering 24 (EcsId,Position,WorldPosition,CHILDOF|Root)
Rendering 26 (EcsId,Position,WorldPosition,CHILDOF|Root)
-- rendering --
Rendering 25 (EcsId,Position,WorldPosition,CHILDOF|Child1)
-- rendering --
Rendering 27 (EcsId,Position,WorldPosition,CHILDOF|Child2)
Updating screen
```

for this code:

```c
    printf("-- rendering --\n");

    for (int i = 0; i < rows->count; i ++) {
        printf("Rendering %d (%s)\n", rows->entities[i],
            ecs_type_to_expr(rows->world, ecs_get_type(rows->world, rows->entities[i])));
    }
```

**Comment by WEREMSOFT** [comment]
I see. Thanks!
