### ISSUE TITLE
Documentation mentions removed function argument

### ISSUE THREAD

**Issue by Tisten** [SanderMertens/flecs#920]
**Describe the bug**
The documentation of `ecs_get_mut_id()` says that `... the component will be added by this operation. In this case the is_added out parameter will be set to true.` here:
https://github.com/SanderMertens/flecs/blob/b55a883015840bbdc1297aba170d8b180484b7bd/include/flecs.h#L2369

But the `is_added` argument is no longer there.

Also started a discussion about if the removal of this argument was the right thing to do here: https://github.com/SanderMertens/flecs/discussions/728#discussioncomment-4797717

**Comment by SanderMertens** [comment]
Fixed!
