### ISSUE TITLE
Example of singleton usage in C

### ISSUE THREAD

**Issue by lyonbeckers** [SanderMertens/flecs#926]
**Describe the problem you are trying to solve.**
I am struggling to understand how singletons can be used in systems with other entities in v3. I can compose a system which iterates over a singleton, and I can compose a system which iterates over a regular component, but I cannot get a system which needs access to the singleton as well as components on other entities. I can see there was previously an example here, https://github.com/SanderMertens/flecs/blob/v2.4.8/examples/c/49_singleton/src/main.c, but even taking into account the API changes from v2.4.8, the usage of `$` in the same way causes a runtime error in v3.1.4.

**Describe the solution you'd like**
I would love to see an example in v3 which covers the same scenario as the example in v2.4.8, but ported to v3 and above, in which a system has access to a singleton as well as other entities. It would also be nice for any special treatment of singletons by systems or filters to be documented in the quickstart guide.

EDIT: I've just been pointed to the tests, where the usage is covered, but it might be nice to have something more accessible?

**Comment by SanderMertens** [comment]
Done! I added an example for C and C++:

https://github.com/SanderMertens/flecs/blob/master/examples/c/queries/singleton/src/main.c
https://github.com/SanderMertens/flecs/blob/master/examples/cpp/queries/singleton/src/main.cpp
