### ISSUE TITLE
Destructor not called for deferred set/emplace calls

### ISSUE THREAD

**Issue by Thinkofname** [SanderMertens/flecs#927]
**Describe the bug**
When deferring `set`/`emplace` calls flecs writes the component to a temporary buffer before moving into the table later. This temporary buffer never has the destructor called on it however once the data is moved out of it. This can cause leaks in types that still retain allocations after a move (e.g. `std::vector` in debug on MSVC).

**To Reproduce**

```c++
#include "./flecs.h"

int ctorCount = 0;
int dtorCount = 0;

struct SomeType {
    int val{ 0 };

    SomeType() {
        ctorCount++;
    }
    SomeType(const SomeType& other) {
        ctorCount++;
    }
    SomeType(SomeType&& other) {
        ctorCount++;
    }

    SomeType& operator=(const SomeType& other) {
        return *this;
    }
    SomeType& operator=(SomeType&& other) {
        return *this;
    }

    ~SomeType() {
        dtorCount++;
    }
};

int main()
{
    {
        flecs::world ecs{};

        ecs.component<SomeType>();

        auto e = ecs.entity();
        auto e2 = ecs.entity();

        ecs.defer([&]() {
            e.emplace<SomeType>();
            e2.set<SomeType>({});
        });
    }

    printf("CTOR: %d vs DTOR: %d\n", ctorCount, dtorCount);
    // Prints: CTOR: 5 vs DTOR: 3
}
```

**Expected behavior**
The number of constructor calls to destructor calls should be equal in the above test case.

**Additional context**
Tested on MSVC 2022 and 2017.

**Comment by SanderMertens** [comment]
Fixed!
