### ISSUE TITLE
I'd like to participate with the project. Can you tag some bugs as "beginner" or "documentation"

### ISSUE THREAD

**Issue by WEREMSOFT** [SanderMertens/flecs#93]
**Describe the problem you are trying to solve.**
I'd like to contribute with the project but I don't know where to start. C/C++ is kind of just a hobby for me, but I have some experience programming games on different languages/tools.

**Describe the solution you'd like**
I'd like to be able to pick easy stuff to start. Like documentation or silly bugs that doesn't require much experience or that are not critical for the framework.

For that reason I'd like to have tags "beginner" and "documentation/tutorial required" (actual tag name may vary) to be able to identify this opportunities.

Thanks

**Comment by SanderMertens** [comment]
Good idea! I will look for some issues :)

**Comment by WEREMSOFT** [comment]
Thanks!
