### ISSUE TITLE
In the manual, there is a dead link

### ISSUE THREAD

**Issue by Tisten** [SanderMertens/flecs#935]
**Describe the bug**
In [the manual under the Hierarchical queries section](https://github.com/SanderMertens/flecs/blob/master/docs/Manual.md#hierarchical-queries) there is a link called the [query manual](https://github.com/SanderMertens/flecs/blob/master/docs/Query.md) which is dead. The correct path is https://github.com/SanderMertens/flecs/blob/master/docs/Queries.md

**Comment by SanderMertens** [comment]
Fixed!
