### ISSUE TITLE
Id record refcount goes below 0 in world fini after adding pairs with arbitrary target ids

### ISSUE THREAD

**Issue by Hexlord** [SanderMertens/flecs#951]
**Describe the bug**
When using arbitraty id-s as targets of the relationship, corruptions occur in some scenarios, this is a 100% repro.
World destruction is not succesful, idr ref count reaches -1.

**To Reproduce**
The repro is located at https://github.com/Hexlord/flecs_test/blob/master/main.cpp
It is important that following defines are set in CMake:
```c
add_compile_definitions(
    ECS_HI_COMPONENT_ID=512
    FLECS_CUSTOM_BUILD FLECS_STATS FLECS_CPP FLECS_MODULE FLECS_TIMER FLECS_SYSTEM FLECS_PIPELINE FLECS_EXPR FLECS_PARSER FLECS_LOG FLECS_MONITOR FLECS_REST
)
```

**Expected behavior**
No asserts should happen.

**Comment by SanderMertens** [comment]
Pasted the code here for visibility:

**Comment by SanderMertens** [comment]
I can't reproduce the issue, made sure to build the project with the defines.

**Comment by SanderMertens** [comment]
Fixed!
