### ISSUE TITLE
Better system builder for C++?

### ISSUE THREAD

**Issue by chengts95** [SanderMertens/flecs#962]
**Describe the problem you are trying to solve.**
A clear and concise description of what the problem is. 
The current system-building C++ API is called from the world before the system is actually declared. 
 For example
```c++
 auto sys = ecs.system<const Position, const Radius>("Collide");
```

Currently, in order to write a collection of systems, i wrote many `auto system_register(flecs::world& world) -> flecs::system` to spawn systems (and maybe it is not a good idea?).
However, it is more convenient to completely define and describe a system (declare `ctx` or other `inout` parameters) with a plain datatype before adding them to ecs.  In this case, we can make reusable system functions and call `add_system` from `ecs` to automatically register them.

**Describe the solution you'd like**

For something like [this rust Bevy example](https://github.com/bevyengine/bevy/blob/main/examples/ecs/component_change_detection.rs).
```rust
fn change_component(time: Res<Time>, mut query: Query<(Entity, &mut MyComponent)>)
``` 
The data access to ecs is defined in function parameter lists. The actual running system is built when `ecs.add_system` is called.
Singleton such as `world.get<Time>()` can be automatically called and passed to `Res<Time>` parameter.
Early experiments:
Currently, I managed to generate a system builder from a plain `system_function` or lambda with automatic template inference.
```c++
        constexpr auto args = get_system_arguments(system_function);
        auto systembuilder  = create_system_builder(world, args);
```
It has shown that it is possible to generate specialized code for each function parameter so no runtime cost is added. This also indicates that we can build a query from function parameters.

I think the first useful feature can be to decouple the system builder from ecs world, and only wire it to a world when we add the system. If this is not a good idea, maybe someone can provide me with a better solution for flecs.

**Comment by SanderMertens** [comment]
> Currently, I managed to generate a system builder from a plain system_function or lambda with automatic template inference.

Right, I think that is the correct solution to use, at least for now. For trivial systems, you can use the function arguments of a function/lambda to derive the components to query for. I might eventually add API support for this, but I'm not 100% sure what this is going to look like yet.

The system builder (which inherits from the query builder) API can't be wholly replaced by this, because queries can have plenty of parameters that can't be specified at compile time, such as:

```
.with<Position>().parent()
.with<Eats>(flecs::Wildcard)
```

Closing this issue for now, as there's a functional workaround.
