### ISSUE TITLE
Querying for flattened relationship

### ISSUE THREAD

**Issue by Tisten** [SanderMertens/flecs#967]
**Describe the bug**
The flatten function sets invalid ChildOf relationships, so when using `ecs_children()` of the root after flattening we get all entities in the world.

**To Reproduce**
I wrote a test for it:
```
void FixedHierarchies_make_fixed_1_lvl_children_iter() {
    ecs_world_t *world = ecs_mini();

    ecs_entity_t p = ecs_new_id(world);
    
    ecs_entity_t p_1 = ecs_new_w_pair(world, EcsChildOf, p);
    ecs_entity_t p_1_1 = ecs_new_w_pair(world, EcsChildOf, p_1);

    ecs_entity_t p_2 = ecs_new_w_pair(world, EcsChildOf, p);
    ecs_entity_t p_2_1 = ecs_new_w_pair(world, EcsChildOf, p_2);
	
    ecs_iter_t it = ecs_children(world, p);
    test_bool(true, ecs_children_next(&it));
    test_int(it.count, 2);
    test_uint(p_1, it.entities[0]);
    test_uint(p_2, it.entities[1]);
    test_bool(false, ecs_children_next(&it));

    ecs_flatten(world, ecs_pair(EcsChildOf, p), NULL);
	
    it = ecs_children(world, p);
    test_bool(true, ecs_children_next(&it));
    test_int(it.count, 2);
    test_uint(p_1, it.entities[0]);
    test_uint(p_2, it.entities[1]);
    // This is what we currently get. p_1_1 and p_2_1 now have (ChildOf, p) set.
    //test_bool(true, ecs_children_next(&it));
    //test_int(it.count, 2);
    //test_uint(p_1_1, it.entities[0]);
    //test_uint(p_2_1, it.entities[1]);
    test_bool(false, ecs_children_next(&it));

    ecs_fini(world);
}
```

**Comment by SanderMertens** [comment]
Iterating using a flattened relationship is currently only supported by queries. Support for filters (which is what `ecs_children` uses under the hood) is planned, but may take a while to get implemented.

**Comment by Tisten** [comment]
Okay.

Are there any other known limitations for flattening than that filters is not supported, plus the things documented at https://www.flecs.dev/flecs/group__entity__info.html#gaa15f32a7016cfe84291207e209ba7a1a

Could you guess at an ETA based on how you prioritize this filter work? Perhaps done Q2 this year? Or before end of year?

Also, in what way is the commit above related to this issue?

**Comment by Tisten** [comment]
I reimplemented the test using a query instead and got the same results. Are queries using filters when iterating over their results? Or how would I write a query which works?
Test code:
```
void FixedHierarchies_make_fixed_1_lvl_children_query() {
    ecs_world_t *world = ecs_mini();

    ECS_ENTITY(world, P, 0);
    ECS_ENTITY(world, P_1, (ChildOf, P));
    ECS_ENTITY(world, P_1_1, (ChildOf, P.P_1));
    ECS_ENTITY(world, P_2, (ChildOf, P));
    ECS_ENTITY(world, P_2_1, (ChildOf, P.P_2));
	
    ecs_query_t *q = ecs_query_new(world, "(ChildOf, P)");
    ecs_iter_t it = ecs_query_iter(world, q);
    test_bool(true, ecs_query_next(&it));
    test_int(it.count, 2);
    test_uint(P_1, it.entities[0]);
    test_uint(P_2, it.entities[1]);
    test_bool(false, ecs_query_next(&it));

    ecs_flatten(world, ecs_pair(EcsChildOf, P), NULL);
	
    it = ecs_query_iter(world, q);
    test_bool(true, ecs_query_next(&it));
    test_int(it.count, 2);
    test_uint(P_1, it.entities[0]);
    test_uint(P_2, it.entities[1]);
    // This is what we currently get. p_1_1 and p_2_1 now have (ChildOf, p) set.
    //test_bool(true, ecs_query_next(&it));
    //test_int(it.count, 2);
    //test_uint(P_1_1, it.entities[0]);
    //test_uint(P_2_1, it.entities[1]);
    test_bool(false, ecs_query_next(&it));

    ecs_fini(world);
}
```

**Comment by SanderMertens** [comment]
Yeah the challenge is that in a flattened tree the index that stores where the children of a parent are located no longer exists. To make querying for children of a specific flattened parent work will require a new data structure that's stored alongside the flattened tree. 

I'll have to think a bit about what this would look like. One of the benefits of a flattened tree is that it can significantly reduce RAM utilization because the lookup indices are no longer stored for each flattened parent, I don't want to undo that.

**Comment by SanderMertens** [comment]
Relationship flattening has been removed from v4, and will eventually be replaced with a mechanism that is more flexible.
