### ISSUE TITLE
Single Parent Adopting Multiple Children & Multi-Staging ecs_get_parent()

### ISSUE THREAD

**Issue by teksoc-1** [SanderMertens/flecs#97]
**1. Single Parent Multiple Children Assertion Failure**
Assertion failure occurs when verifying a parent has adopted more than (1) child. Unsure if this is a bug, or a noted constraint that was missed in the documentation.

**To Reproduce**
1. Using sample code provided, change TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE to 1
2. Execute

**Expected Results**
Program should successfully execute and gracefully terminate.

**Actual Results**
Assertion failure when verifying adopted child has a parent.

**2. Multi-Staged Assertion Failure when verifying parent of adopted child**
Assertion failure occurs when verifying a parent of an adopted child when using multi staging.

**To Reproduce**
1. Using sample code provided, change TRIGGER_MULTI_STAGED_ASSERTION_FAILURE to 1
2. Execute

**Expected Results**
Program should successfully execute and gracefully terminate.

**Actual Results**
Assertion failure (sometimes crashes inside `_ecs_map_has()` from `_ecs_get_parent()` call stack) when verifying adopted child has a parent.

**Sample Code**
```
#include "flecs.h"
#include "apple_osapi.h"

#define TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE 0
#define TRIGGER_MULTI_STAGED_ASSERTION_FAILURE 0

#if TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE
#define CHILDREN_COUNT 2
#else
#define CHILDREN_COUNT 1
#endif

// Child Component
typedef int A;

// Parent Component
typedef int B;

void
CreateAChildren( ecs_rows_t * rows )
{
    ECS_COLUMN_COMPONENT( rows, A, 1 );
    
    ecs_new_w_count( rows->world, A, CHILDREN_COUNT );
    
    ecs_os_log( "Created (%i) A child%s", CHILDREN_COUNT, CHILDREN_COUNT > 1 ? "ren" : "" );
}

void
BAdoptAChildren( ecs_rows_t * rows )
{
    ECS_COLUMN_COMPONENT( rows, B, 2 );

    ecs_entity_t parent = ecs_new( rows->world, B );
    
    ecs_os_log( "Parent entity %llu adopting (%i) A child%s ...", parent, rows->count, rows->count > 1 ? "ren" : "" );

    for ( unsigned int i = 0; i < rows->count; i++ )
    {
        ecs_adopt( rows->world, rows->entities[ i ], parent );
        
        ecs_os_log( "Parent entity %llu adopted A child entity %llu", parent, rows->entities[ i ] );
    }
}

void
VerifyAChildrenAdopted( ecs_rows_t * rows )
{
    ECS_COLUMN_COMPONENT( rows, B, 2 );
    
    ecs_os_log( "Verifying %i A child%s adopted ...", rows->count, rows->count > 1 ? "ren" : "" );
    
    for ( unsigned int i = 0; i < rows->count; i++ )
    {
        ecs_entity_t parent = ecs_get_parent( rows->world, rows->entities[ i ], B );
        
        ecs_os_log( "A child entity %llu, parent entity: %llu", rows->entities[ i ], parent );

        ecs_assert( ECS_INVALID_ENTITY != parent, ECS_UNSUPPORTED, NULL );
    }
}

int main( int argc, char ** argv )
{
    int rc = -1;
    
    ecs_world_t * world = ecs_init();

    // Platform specific threading, etc.
    set_api();
    
    ecs_set_target_fps( world, 1 );

#if TRIGGER_MULTI_STAGED_ASSERTION_FAILURE
    ecs_set_threads( world, 4);
#endif
    
    ECS_COMPONENT( world, A );
    ECS_COMPONENT( world, B );

    ECS_SYSTEM( world, CreateAChildren, EcsOnLoad, .A );
    ECS_SYSTEM( world, BAdoptAChildren, EcsPostLoad, A, .B );
    ECS_SYSTEM( world, VerifyAChildrenAdopted, EcsOnUpdate, A, .B );
    
    ecs_progress( world, 0 );

    rc = ecs_fini( world );
    
    return rc;
}
```

**Comment by SanderMertens** [comment]
I have the issue reproduced and am looking into it. Will post more details if I know more.

**Comment by SanderMertens** [comment]
@teksoc-1 I think I found your issue, with this fix I can run the example and it works. Can you validate if the fix also works on your end?

**Comment by teksoc-1** [comment]
@SanderMertens Here's the status on my end:

Works:
```
#define TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE 0
#define TRIGGER_MULTI_STAGED_ASSERTION_FAILURE 0
```

Works:
```
#define TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE 0
#define TRIGGER_MULTI_STAGED_ASSERTION_FAILURE 1
```

Fails:
#define TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE 1
#define TRIGGER_MULTI_STAGED_ASSERTION_FAILURE 0
```

Fails:
```
#define TRIGGER_MULTI_CHILDREN_ASSERTION_FAILURE 1
#define TRIGGER_MULTI_STAGED_ASSERTION_FAILURE 1
```

**Comment by teksoc-1** [comment]
@SanderMertens Do you have the same results using the permutations above?

**Comment by teksoc-1** [comment]
@SanderMertens - Revisited this, and noticed there  was typo ( bug ) in my test code  above;  fixed  the test code  and all seems to work now.

**Comment by SanderMertens** [comment]
Hi @teksoc-1, sounds great! I'll close this issue.
